<a href="https://colab.research.google.com/github/awildt01/Credit-Scoring/blob/main/3__select_feature.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Zumanenfassung

## **Verwendete Methode zur Feature-Auswahl**

In diesem Schritt wird eine Kombination aus manueller Feature-Selektion und der Vermeidung der Dummy-Variablen-Falle angewendet.

- **Manuelle Feature-Selektion**
Die Auswahl der über 100 genutzten Variablen basiert nicht auf einem automatisierten Algorithmus, sondern auf einer vorangegangenen Analyse (z. B. explorative Datenanalyse, Berechnung von Information Value oder Weight of Evidence). Ein Analyst hat entschieden, welche Merkmale für das Modell am relevantesten sind.

- **Vermeidung der Dummy-Variablen-Falle**
Bei kategorialen Variablen mit k Kategorien entstehen nach dem One-Hot-Encoding k Dummy-Variablen. Werden alle verwendet, führt dies zu perfekter **Multikollinearität**, was insbesondere bei linearer und logistischer Regression problematisch ist.

**Lösung:** Aus jeder Gruppe von Dummy-Variablen wird eine Kategorie entfernt. Diese Referenzkategorie dient als Vergleichsbasis.
Beispiel: Im Code wird term:60 (Laufzeit: 60 Monate) entfernt. Der Koeffizient von term:36 misst dann den Unterschied im Kreditrisiko im Vergleich zur Referenz term:60.

Fazit:
Die eigentliche Feature-Auswahl erfolgt bereits vor diesem Schritt. Der hier gezeigte Code bereitet die ausgewählten Variablen für die Modellierung vor, indem er Multikollinearität durch die Wahl einer Referenzkategorie verhindert.

## **Vorbereitung der Eingabedaten: Feature-Auswahl und Referenzkategorien für die logistische Regression**

**1- Auswahl der Features (Variablenauswahl):** Zuerst wird ein neuer DataFrame **inputs_train_with_ref_cat** erstellt. Dieser enthält nur eine spezifische Auswahl von Spalten (Features) aus dem ursprünglichen Trainingsdatensatz **loan_data_inputs_train**. Die ausgewählten Spalten sind bereits in "Dummy-Variablen" umgewandelt worden. Das bedeutet, dass kategoriale Variablen wie grade (Kreditwürdigkeitsstufe) oder home_ownership (Wohneigentum-Status) in mehrere binäre (0/1) Spalten aufgeteilt wurden.

**2- Definition der Referenzkategorien:** Eine Liste namens **ref_categories** wird erstellt. Diese Liste enthält die Namen von Dummy-Variablen, die als "Referenzkategorien" dienen sollen. Für jede ursprüngliche kategoriale Variable (z.B. grade) wird eine ihrer Dummy-Variablen (hier grade:G) in diese Liste aufgenommen.

**3- Entfernen der Referenzkategorien:** Die in der **ref_categories-Liste** definierten Spalten werden aus dem DataFrame inputs_train_with_ref_cat entfernt. Das Ergebnis ist ein neuer, finaler DataFrame inputs_train, der für das Modelltraining verwendet wird.
Zusammenfassend lässt sich sagen: Der Code selektiert eine Reihe von vorverarbeiteten Features und entfernt dann aus jeder kategorialen Gruppe eine Referenzkategorie, um Multikollinearität zu vermeiden.

Zusammenfassend ist die Definition einer Referenzkategorie eine technische Notwendigkeit, um **Multikollinearität zu vermeiden**, und gleichzeitig ein mächtiges Werkzeug für die Interpretation, da sie den Bezugsrahmen für die Bewertung aller anderen Kategorien festlegt.

## **Was ist eine Referenzkategorie?**

Eine Referenzkategorie ist die Basiskategorie, mit der alle anderen Kategorien einer kategorialen Variable verglichen werden, wenn sie in einem statistischen Modell (wie der logistischen oder linearen Regression) verwendet wird.
Stellen Sie sich vor, Sie möchten den Einfluss der home_ownership (Wohneigentum-Status) auf das Kreditrisiko untersuchen. Diese Variable hat drei mögliche Ausprägungen (Kategorien): MORTGAGE (Hypothek), OWN (Eigentum) und RENT (Miete).
Ein Computer kann mit den Textwerten "MORTGAGE" oder "RENT" nicht direkt rechnen. Deshalb wandeln wir sie in Dummy-Variablen um. Das sieht so aus:

| home_ownership | home_ownership:MORTGAGE | home_ownership:OWN | home_ownership:RENT |
|----------------|-------------------------|--------------------|---------------------|
| MORTGAGE       | 1                       | 0                  | 0                   |
| OWN            | 0                       | 1                  | 0                   |
| RENT           | 0                       | 0                  | 1                   |



**Das Problem: Die "Dummy-Variablen-Falle" (Multikollinearität)**

Wenn wir alle drei Dummy-Variablen in ein Regressionsmodell aufnehmen, stoßen wir auf ein Problem namens perfekte Multikollinearität. Das bedeutet, dass eine Variable perfekt aus den anderen vorhergesagt werden kann.
  - Beispiel: Wenn home_ownership:MORTGAGE = 0 und home_ownership:OWN = 0 ist, dann muss home_ownership:RENT = 1 sein. Es gibt keine andere Möglichkeit.

Diese redundante Information verwirrt das Modell. Es kann keine eindeutigen Koeffizienten für jede Kategorie berechnen, weil ihre Effekte nicht voneinander zu trennen sind. Mathematisch führt dies zu einem Fehler.

**Die Lösung:**

Eine Kategorie als Referenzpunkt festlegen
Um dieses Problem zu lösen, lassen wir einfach eine der Dummy-Variablen weg. Die weggelassene Kategorie wird zur Referenzkategorie.
In Ihrem Code wurde für home_ownership die Kategorie RENT_OTHER_NONE_ANY als Referenz gewählt. Nehmen wir an, wir vereinfachen das auf RENT. Dann sieht der Datensatz, den das Modell tatsächlich verwendet, so aus:

| home_ownership | home_ownership:MORTGAGE | home_ownership:OWN |
|----------------|-------------------------|--------------------|
| MORTGAGE       | 1                       | 0                  |
| OWN            | 0                       | 1                  |
| RENT           | 0                       | 0                  |

**Wie wird das jetzt interpretiert?**

- Ein Kreditnehmer mit MORTGAGE wird durch home_ownership:MORTGAGE = 1 identifiziert.
- Ein Kreditnehmer mit OWN wird durch home_ownership:OWN = 1 identifiziert.
- Ein Kreditnehmer mit RENT (die Referenzkategorie) wird dadurch identifiziert, dass beide anderen Spalten 0 sind. Er ist der "Standardfall".

**Die Bedeutung im Modell:** Alles ist relativ

Wenn das Modell trainiert wird, berechnet es Koeffizienten (Gewichte) für home_ownership:MORTGAGE und home_ownership:OWN. Diese Koeffizienten beschreiben den Unterschied im Effekt im Vergleich zur Referenzkategorie (RENT).
Angenommen, das Modell liefert folgende (fiktive) Koeffizienten für die Wahrscheinlichkeit eines Kreditausfalls:
- home_ownership:MORTGAGE: -0.25
- home_ownership:OWN: -0.10

**Interpretation:**

- Der negative Koeffizient von -0.25 für MORTGAGE bedeutet: Kreditnehmer mit einer Hypothek haben ein geringeres Kreditausfallrisiko als Kreditnehmer, die zur Miete wohnen.
- Der Koeffizient von -0.10 für OWN bedeutet: Kreditnehmer mit Eigenheim haben ebenfalls ein geringeres Risiko als Mieter, aber der risikomindernde Effekt ist nicht so stark wie bei Hypothekennehmern.

Die Referenzkategorie (RENT) hat keinen eigenen Koeffizienten. Ihr Effekt ist sozusagen im "Grundrauschen" des Modells (dem Intercept oder Achsenabschnitt) enthalten. Sie ist der Nullpunkt, von dem aus die anderen Effekte gemessen werden.

## **Wie wählt man die Referenzkategorie aus?**

Die Wahl der Referenzkategorie ist eine strategische Entscheidung. Übliche Vorgehensweisen sind:
1. **Die häufigste Kategorie:** Das macht die Interpretation der anderen Koeffizienten oft intuitiv, da sie den Unterschied zur "normalsten" Gruppe zeigen.
2. **Die Kategorie mit dem geringsten Risiko (oder Erfolg):** Wenn man z.B. grade:G (die schlechteste Bonitätsnote) als Referenz wählt, werden alle anderen Koeffizienten (grade:A, grade:B etc.) positiv sein und zeigen, um wie viel besser diese Noten im Vergleich zur schlechtesten sind. Dies ist in Ihrem Code der Fall und eine sehr gängige Praxis in der Kreditrisikomodellierung.
3. **Eine logische "Basis"-Kategorie:** Zum Beispiel könnte man bei einer medizinischen Studie die "Placebo"-Gruppe als Referenz wählen.

# Import Libraries

In [1]:
import numpy as np
import pandas as pd

from google.colab import drive
import os

In [2]:
# Google Drive mounten
drive.mount('/content/drive')

# Zielordner definieren
folder_path = '/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks'
os.makedirs(folder_path, exist_ok=True)  # Ordner erstellen, falls nicht vorhanden

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
loan_data_inputs_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_train.csv', index_col = 0,)

In [4]:
loan_data_targets_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_train.csv', index_col = 0,header=0)

In [5]:
loan_data_inputs_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_test.csv',index_col = 0,)

In [6]:
loan_data_targets_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_test.csv',index_col = 0, header=0)

# Loading the Data and Selecting the Features

In [7]:
#loan_data_inputs_train = pd.read_csv('loan_data_inputs_train.csv', index_col = 0)
# loan_data_targets_train = pd.read_csv('loan_data_targets_train.csv', index_col = 0, header = None)
# loan_data_inputs_test = pd.read_csv('loan_data_inputs_test.csv', index_col = 0)
# loan_data_targets_test = pd.read_csv('loan_data_targets_test.csv', index_col = 0, header = None)

### Explore Data

In [8]:
pd.set_option('display.max_info_rows', 300)
loan_data_inputs_train.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,dti:21.7-22.4,dti:22.4-35,dti:>35,mths_since_last_record:Missing,mths_since_last_record:0-2,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
427211,292984,29074404,31607606,11250,11250,11250.0,60 months,16.99,279.54,D,...,0,0,0,1,0,0,0,0,0,0
206088,57793,9026077,10838105,8000,8000,8000.0,36 months,18.55,291.44,D,...,0,1,0,1,0,0,0,0,0,0
136020,140700,4865088,6157358,6000,6000,6000.0,36 months,10.16,194.06,B,...,0,0,0,1,0,0,0,0,0,0
412305,297571,28764454,31297687,8000,8000,8000.0,36 months,9.17,255.04,B,...,0,0,0,1,0,0,0,0,0,0
36159,5264,985083,1208540,5000,5000,5000.0,36 months,11.71,165.38,B,...,0,0,0,1,0,0,0,0,0,0

In [9]:
loan_data_targets_train.shape

(373028, 1)

In [10]:
loan_data_inputs_train.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,dti:21.7-22.4,dti:22.4-35,dti:>35,mths_since_last_record:Missing,mths_since_last_record:0-2,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
427211,292984,29074404,31607606,11250,11250,11250.0,60 months,16.99,279.54,D,...,0,0,0,1,0,0,0,0,0,0
206088,57793,9026077,10838105,8000,8000,8000.0,36 months,18.55,291.44,D,...,0,1,0,1,0,0,0,0,0,0
136020,140700,4865088,6157358,6000,6000,6000.0,36 months,10.16,194.06,B,...,0,0,0,1,0,0,0,0,0,0
412305,297571,28764454,31297687,8000,8000,8000.0,36 months,9.17,255.04,B,...,0,0,0,1,0,0,0,0,0,0
36159,5264,985083,1208540,5000,5000,5000.0,36 months,11.71,165.38,B,...,0,0,0,1,0,0,0,0,0,0

In [11]:
loan_data_targets_train.head()

        good_bad
427211         1
206088         1
136020         1
412305         1
36159          0

In [12]:
loan_data_inputs_test.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,dti:21.7-22.4,dti:22.4-35,dti:>35,mths_since_last_record:Missing,mths_since_last_record:0-2,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
362514,343487,21211587,23514367,6400,6400,6400.0,36 months,8.39,201.71,A,...,1,0,0,1,0,0,0,0,0,0
288564,415939,12656479,14658633,18700,18700,18700.0,36 months,18.92,684.72,D,...,0,0,0,1,0,0,0,0,0,0
213591,65794,8618870,10390702,16000,16000,16000.0,36 months,6.03,486.97,A,...,0,0,0,1,0,0,0,0,0,0
263083,426133,13045554,15077755,15000,15000,15000.0,60 months,17.57,377.41,D,...,1,0,0,1,0,0,0,0,0,0
165001,100410,6826607,8448689,16000,16000,16000.0,36 months,15.22,556.38,C,...,0,0,0,1,0,0,0,0,0,0

In [27]:
loan_data_targets_test.head()

        good_bad
362514         1
288564         1
213591         1
263083         1
165001         1

In [28]:
for i, col in enumerate(loan_data_inputs_train.columns, 1):
    print(f"{i}. {col}")

1. Unnamed: 0
2. id
3. member_id
4. loan_amnt
5. funded_amnt
6. funded_amnt_inv
7. term
8. int_rate
9. installment
10. grade
11. sub_grade
12. emp_title
13. emp_length
14. home_ownership
15. annual_inc
16. verification_status
17. issue_d
18. loan_status
19. pymnt_plan
20. url
21. desc
22. purpose
23. title
24. zip_code
25. addr_state
26. dti
27. delinq_2yrs
28. earliest_cr_line
29. inq_last_6mths
30. mths_since_last_delinq
31. mths_since_last_record
32. open_acc
33. pub_rec
34. revol_bal
35. revol_util
36. total_acc
37. initial_list_status
38. out_prncp
39. out_prncp_inv
40. total_pymnt
41. total_pymnt_inv
42. total_rec_prncp
43. total_rec_int
44. total_rec_late_fee
45. recoveries
46. collection_recovery_fee
47. last_pymnt_d
48. last_pymnt_amnt
49. next_pymnt_d
50. last_credit_pull_d
51. collections_12_mths_ex_med
52. mths_since_last_major_derog
53. policy_code
54. application_type
55. annual_inc_joint
56. dti_joint
57. verification_status_joint
58. acc_now_delinq
59. tot_coll_amt
60. tot_cur_bal
61. open_acc_6m
62. open_il_6m
63. open_il_12m
64. open_il_24m
65. mths_since_rcnt_il
66. total_bal_il
67. il_util
68. open_rv_12m
69. open_rv_24m
70. max_bal_bc
71. all_util
72. total_rev_hi_lim
73. inq_fi
74. total_cu_tl
75. inq_last_12m
76. emp_length_missing
77. emp_length_int
78. term_int
79. earliest_cr_line_date
80. months_since_earliest_cr_line
81. issue_d_date
82. mths_since_issue_d
83. grade:A
84. grade:B
85. grade:C
86. grade:D
87. grade:E
88. grade:F
89. grade:G
90. sub_grade:A1
91. sub_grade:A2
92. sub_grade:A3
93. sub_grade:A4
94. sub_grade:A5
95. sub_grade:B1
96. sub_grade:B2
97. sub_grade:B3
98. sub_grade:B4
99. sub_grade:B5
100. sub_grade:C1
101. sub_grade:C2
102. sub_grade:C3
103. sub_grade:C4
104. sub_grade:C5
105. sub_grade:D1
106. sub_grade:D2
107. sub_grade:D3
108. sub_grade:D4
109. sub_grade:D5
110. sub_grade:E1
111. sub_grade:E2
112. sub_grade:E3
113. sub_grade:E4
114. sub_grade:E5
115. sub_grade:F1
116. sub_grade:F2
117. sub_grade:F3
118. sub_grade:F4
119. sub_grade:F5
120. sub_grade:G1
121. sub_grade:G2
122. sub_grade:G3
123. sub_grade:G4
124. sub_grade:G5
125. home_ownership:ANY
126. home_ownership:MORTGAGE
127. home_ownership:NONE
128. home_ownership:OTHER
129. home_ownership:OWN
130. home_ownership:RENT
131. verification_status:Not Verified
132. verification_status:Source Verified
133. verification_status:Verified
134. loan_status:Charged Off
135. loan_status:Current
136. loan_status:Default
137. loan_status:Does not meet the credit policy. Status:Charged Off
138. loan_status:Does not meet the credit policy. Status:Fully Paid
139. loan_status:Fully Paid
140. loan_status:In Grace Period
141. loan_status:Late (16-30 days)
142. loan_status:Late (31-120 days)
143. purpose:car
144. purpose:credit_card
145. purpose:debt_consolidation
146. purpose:educational
147. purpose:home_improvement
148. purpose:house
149. purpose:major_purchase
150. purpose:medical
151. purpose:moving
152. purpose:other
153. purpose:renewable_energy
154. purpose:small_business
155. purpose:vacation
156. purpose:wedding
157. addr_state:AK
158. addr_state:AL
159. addr_state:AR
160. addr_state:AZ
161. addr_state:CA
162. addr_state:CO
163. addr_state:CT
164. addr_state:DC
165. addr_state:DE
166. addr_state:FL
167. addr_state:GA
168. addr_state:HI
169. addr_state:IA
170. addr_state:ID
171. addr_state:IL
172. addr_state:IN
173. addr_state:KS
174. addr_state:KY
175. addr_state:LA
176. addr_state:MA
177. addr_state:MD
178. addr_state:ME
179. addr_state:MI
180. addr_state:MN
181. addr_state:MO
182. addr_state:MS
183. addr_state:MT
184. addr_state:NC
185. addr_state:NE
186. addr_state:NH
187. addr_state:NJ
188. addr_state:NM
189. addr_state:NV
190. addr_state:NY
191. addr_state:OH
192. addr_state:OK
193. addr_state:OR
194. addr_state:PA
195. addr_state:RI
196. addr_state:SC
197. addr_state:SD
198. addr_state:TN
199. addr_state:TX
200. addr_state:UT
201. addr_state:VA
202. addr_state:VT
203. addr_state:WA
204. addr_state:WI
205. addr_state:WV
206. addr_state:WY
207. initial_list_status:f
208. initial_list_status:w
209. home_ownership:RENT_OTHER_NONE_ANY
210. addr_state:ND
211. addr_state:ND_NE_IA_NV_FL_HI_AL
212. addr_state:OK_LA_NC_NM_MO_VA_NJ
213. addr_state:MD_TN_AZ_PA_MI
214. addr_state:DE_AR
215. addr_state:UT_MN_OH_IN_GA_ RI_WA
216. addr_state:OR_KY_MA
217. addr_state:MT_MS_SD
218. addr_state:WI_IL_CT_AK
219. addr_state:CO_SC
220. addr_state:KS_NH_WV_VT_ID
221. addr_state:WY_DC_ME
222. purpose:educ__sm_b__wedd__ren_en__mov__house
223. purpose:oth__med__vacation
224. purpose:major_purch__car__home_impr
225. term:36
226. term:60
227. emp_length:0
228. emp_length:1
229. emp_length:2-4
230. emp_length:5-6
231. emp_length:7-9
232. emp_length:10
233. mths_since_issue_d_factor
234. mths_since_issue_d:<38
235. mths_since_issue_d:38-39
236. mths_since_issue_d:40-41
237. mths_since_issue_d:42-48
238. mths_since_issue_d:49-52
239. mths_since_issue_d:53-64
240. mths_since_issue_d:65-84
241. mths_since_issue_d:>84
242. int_rate_factor
243. int_rate:<9.548
244. int_rate:9.548-12.025
245. int_rate:12.025-15.74
246. int_rate:15.74-20.281
247. int_rate:>20.281
248. funded_amnt_factor
249. mths_since_earliest_cr_line_factor
250. mths_since_earliest_cr_line:<140
251. mths_since_earliest_cr_line:141-164
252. mths_since_earliest_cr_line:165-247
253. mths_since_earliest_cr_line:248-270
254. mths_since_earliest_cr_line:271-352
255. mths_since_earliest_cr_line:>352
256. delinq_2yrs:0
257. delinq_2yrs:1-3
258. delinq_2yrs:4-16
259. delinq_2yrs:>=17
260. inq_last_6mths:0
261. inq_last_6mths:1-2
262. inq_last_6mths:3-6
263. inq_last_6mths:>6
264. open_acc:0
265. open_acc:1-3
266. open_acc:4-12
267. open_acc:13-17
268. open_acc:18-22
269. open_acc:23-25
270. open_acc:26-30
271. open_acc:>=31
272. pub_rec:0-2
273. pub_rec:3-4
274. pub_rec:>=5
275. total_acc_factor
276. total_acc:0-15
277. total_acc:16-70
278. total_acc:71-90
279. total_acc:>90
280. acc_now_delinq:0
281. acc_now_delinq:>=1
282. total_rev_hi_lim_factor
283. total_rev_hi_lim:<=5K
284. total_rev_hi_lim:5K-10K
285. total_rev_hi_lim:10K-20K
286. total_rev_hi_lim:20K-30K
287. total_rev_hi_lim:30K-40K
288. total_rev_hi_lim:40K-55K
289. total_rev_hi_lim:55K-95K
290. installment_factor
291. installment:<=800
292. installment:801-1100
293. installment:1101-1250
294. installment:>1250
295. annual_inc_factor
296. annual_inc:<20K
297. annual_inc:20K-30K
298. annual_inc:30K-40K
299. annual_inc:40K-50K
300. annual_inc:50K-60K
301. annual_inc:60K-70K
302. annual_inc:70K-80K
303. annual_inc:80K-90K
304. annual_inc:90K-100K
305. annual_inc:100K-120K
306. annual_inc:120K-140K
307. annual_inc:>140K
308. mths_since_last_delinq:Missing
309. mths_since_last_delinq:0-3
310. mths_since_last_delinq:4-30
311. mths_since_last_delinq:31-56
312. mths_since_last_delinq:>=57
313. dti_factor
314. dti:<=1.4
315. dti:1.4-3.5
316. dti:3.5-7.7
317. dti:7.7-10.5
318. dti:10.5-16.1
319. dti:16.1-20.3
320. dti:20.3-21.7
321. dti:21.7-22.4
322. dti:22.4-35
323. dti:>35
324. mths_since_last_record:Missing
325. mths_since_last_record:0-2
326. mths_since_last_record:3-20
327. mths_since_last_record:21-31
328. mths_since_last_record:32-80
329. mths_since_last_record:81-86
330. mths_since_last_record:>86

### Selecting the Features

In [29]:
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',

'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',

'addr_state:ND',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:OK_LA_NC_NM_MO_VA_NJ',
'addr_state:MD_TN_AZ_PA_MI',
'addr_state:DE_AR',
'addr_state:UT_MN_OH_IN_GA_ RI_WA',
'addr_state:OR_KY_MA',
'addr_state:MT_MS_SD',
'addr_state:WI_IL_CT_AK',
'addr_state:CO_SC',
'addr_state:KS_NH_WV_VT_ID',
'addr_state:WY_DC_ME',

'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',

'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',

'initial_list_status:f',
'initial_list_status:w',

'term:36',
'term:60',

'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',

'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',

'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',

'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',


'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:4-16',
'delinq_2yrs:>=17',


'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',


'open_acc:0',
'open_acc:1-3',
'open_acc:4-12',
'open_acc:13-17',
'open_acc:18-22',
'open_acc:23-25',
'open_acc:26-30',
'open_acc:>=31',

'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',

'total_acc:0-15',
'total_acc:16-70',
'total_acc:71-90',
'total_acc:>90',

'acc_now_delinq:0',
'acc_now_delinq:>=1',

'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',



'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',

'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',


'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',

'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',

]]

In [30]:
# Here we store the names of the reference category dummy variables in a list.
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
#'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:ND',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:0',
'inq_last_6mths:>6',
'open_acc:0',
'pub_rec:0-2',
'total_acc:0-15',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [39]:
pd.set_option('display.max_info_rows', 100)
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
# From the dataframe with input variables, we drop the variables with variable names in the list with reference categories.
inputs_train.sample(100)

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:ND_NE_IA_NV_FL_HI_AL,addr_state:OK_LA_NC_NM_MO_VA_NJ,...,dti:22.4-35,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
372480,False,False,False,True,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
57781,False,True,False,False,False,False,False,False,1,0,...,0,1,0,0,0,0,0,0,0,0
29824,False,True,False,False,False,False,True,False,0,0,...,0,1,0,0,0,0,0,0,0,0
399016,False,False,True,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
214453,False,False,False,True,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,1
274390,False,False,False,True,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
322372,False,False,True,False,False,False,False,False,0,1,...,1,0,1,0,0,0,0,1,0,0
271935,False,False,True,False,False,False,False,False,0,0,...,0,0,0,0,1,0,0,0,0,0
284892,True,False,False,False,False,False,False,False,1,0,...,1,1,0,0,0,0,0,0,0,0
4842,False,False,True,False,False,False,False,True,0,1,...,0,0,0,1,0,0,0,0,0,0
259471,False,True,False,False,False,False,False,True,0,0,...,1,0,1,0,0,0,0,0,0,0
325854,False,True,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
12968,False,True,False,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
174206,False,False,True,False,False,False,False,False,0,1,...,1,1,0,0,0,0,0,0,0,0
363158,False,False,True,False,False,False,False,True,0,1,...,0,1,0,0,0,0,0,0,0,0
298172,False,False,True,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
382517,False,False,True,False,False,False,False,True,1,0,...,0,0,1,0,0,0,0,0,0,0
180740,False,True,False,False,False,False,False,False,1,0,...,0,0,0,1,0,0,0,0,0,0
417974,False,False,False,False,False,True,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
346695,False,False,True,False,False,False,False,True,0,0,...,0,0,0,1,0,0,0,0,0,0
16598,False,False,True,False,False,False,False,False,0,1,...,0,1,0,0,0,0,0,0,0,0
79143,False,True,False,False,False,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
85409,False,False,False,True,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
184025,False,False,True,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
138359,False,False,False,False,True,False,False,True,0,0,...,1,0,1,0,0,0,0,0,0,0
29340,False,False,False,False,False,True,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
63794,False,True,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
152256,False,False,True,False,False,False,True,False,0,0,...,0,1,0,0,0,0,0,0,0,0
35382,False,False,True,False,False,False,False,False,0,0,...,1,0,0,1,0,0,0,0,0,0
66474,False,False,True,False,False,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
441882,False,True,False,False,False,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
347325,False,False,False,False,True,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
289592,False,True,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
119225,False,True,False,False,False,False,True,False,0,0,...,0,0,0,1,0,0,0,0,0,1
278756,False,True,False,False,False,False,False,True,0,0,...,1,0,1,0,0,0,0,0,0,0
421345,True,False,False,False,False,False,False,True,0,0,...,1,1,0,0,0,0,0,0,0,0
173377,False,False,False,True,False,False,False,True,1,0,...,1,1,0,0,0,0,0,0,0,0
378594,False,True,False,False,False,False,False,True,0,0,...,0,0,0,1,0,0,0,0,0,0
91141,False,True,False,False,False,False,False,True,0,0,...,1,0,0,1,0,0,0,0,0,0
167328,False,False,True,False,False,False,True,False,0,0,...,0,1,0,0,0,0,0,1,0,0
421746,True,False,False,False,False,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
333194,False,False,True,False,False,False,False,False,1,0,...,0,1,0,0,0,0,0,0,0,0
240154,True,False,False,False,False,False,False,True,0,0,...,1,1,0,0,0,0,0,0,0,0
112608,False,False,False,True,False,False,False,False,0,0,...,1,1,0,0,0,0,0,0,0,0
92752,False,True,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,1
466159,False,True,False,False,False,False,False,True,0,0,...,0,0,0,0,1,0,0,0,0,0
27694,True,False,False,False,False,False,False,True,1,0,...,0,1,0,0,0,0,0,0,0,0
434333,False,True,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
221190,True,False,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
185952,False,False,False,True,False,False,False,True,0,0,...,0,0,0,1,0,0,0,0,0,0
379179,False,True,False,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
121829,True,False,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
430330,False,False,False,True,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
338442,False,False,False,False,False,True,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
375152,False,False,False,False,False,True,False,False,0,0,...,0,1,0,0,0,0,0,0,0,1
438160,False,False,False,False,True,False,False,False,0,0,...,0,0,0,0,1,0,0,0,0,0
150413,False,False,False,False,True,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
278147,False,False,True,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,1,0,0
355786,False,True,False,False,False,False,False,False,0,0,...,1,0,0,1,0,0,0,0,0,0
395541,False,True,False,False,False,False,False,True,0,0,...,1,0,0,0,1,0,0,0,0,0
39887,False,False,False,False,True,False,False,True,1,0,...,0,1,0,0,0,0,0,0,0,0
310475,False,False,True,False,False,False,False,False,1,0,...,1,1,0,0,0,0,0,0,0,0
5984,True,False,False,False,False,False,False,True,1,0,...,0,1,0,0,0,0,0,0,0,0
108716,False,True,False,False,False,False,False,True,0,1,...,0,1,0,0,0,0,0,0,0,0
57742,True,False,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
309315,False,False,False,True,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
377069,False,False,True,False,False,False,False,True,0,1,...,0,1,0,0,0,0,0,0,0,0
209693,False,True,False,False,False,False,False,True,0,0,...,1,1,0,0,0,0,0,0,0,0
390197,False,False,False,True,False,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
391120,False,False,False,True,False,False,False,False,0,1,...,0,0,1,0,0,0,0,0,0,0
37877,False,False,False,False,True,False,False,False,0,0,...,1,0,1,0,0,0,0,0,0,0
355146,False,False,False,True,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
170219,False,False,False,True,False,False,False,False,0,0,...,0,0,0,0,1,0,0,0,0,1
241771,True,False,False,False,False,False,False,True,1,0,...,0,0,0,1,0,0,0,0,0,0
65172,False,True,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
436626,False,False,True,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,1,0,0
186452,True,False,False,False,False,False,False,True,0,2,...,0,1,0,0,0,0,0,0,0,0
105336,False,False,True,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
61236,False,False,False,True,False,False,False,True,0,0,...,1,1,0,0,0,0,0,0,0,0
226277,False,True,False,False,False,False,False,True,1,0,...,0,0,1,0,0,0,0,0,0,0
223513,False,True,False,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
20186,False,False,False,False,True,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
136167,False,False,True,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
306909,False,True,False,False,False,False,True,False,0,1,...,0,1,0,0,0,0,0,0,0,0
342806,False,True,False,False,False,False,True,False,0,0,...,0,0,0,1,0,0,0,0,0,0
447286,False,False,True,False,False,False,False,False,0,1,...,0,0,1,0,0,0,0,0,0,0
380237,False,False,False,False,True,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
93870,False,False,True,False,False,False,False,False,0,0,...,0,0,0,1,0,0,0,0,0,0
44076,True,False,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
315167,False,False,False,False,False,True,False,False,0,1,...,1,0,1,0,0,0,0,0,0,0
50324,False,True,False,False,False,False,False,False,0,0,...,0,0,0,0,1,0,0,0,0,0
180443,False,False,False,True,False,False,False,False,0,0,...,1,0,0,0,1,0,0,0,0,0
389809,False,True,False,False,False,False,False,True,0,1,...,0,0,1,0,0,0,0,0,0,0
249035,False,True,False,False,False,False,False,True,0,0,...,1,1,0,0,0,0,0,0,0,0
327665,False,True,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
316461,False,False,True,False,False,False,True,False,0,0,...,0,0,0,0,0,0,0,0,0,0
217435,False,False,False,True,False,False,False,False,0,1,...,0,0,0,1,0,0,0,0,0,0
72396,True,False,False,False,False,False,False,True,0,0,...,0,0,0,0,1,0,0,0,0,0
423169,False,True,False,False,False,False,False,False,0,0,...,0,0,0,1,0,0,0,0,0,0
119411,True,False,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0

In [40]:
for i, col in enumerate(inputs_train.columns, 1):
    print(f"{i}. {col}")

1. grade:A
2. grade:B
3. grade:C
4. grade:D
5. grade:E
6. grade:F
7. home_ownership:OWN
8. home_ownership:MORTGAGE
9. addr_state:ND_NE_IA_NV_FL_HI_AL
10. addr_state:OK_LA_NC_NM_MO_VA_NJ
11. addr_state:MD_TN_AZ_PA_MI
12. addr_state:DE_AR
13. addr_state:UT_MN_OH_IN_GA_ RI_WA
14. addr_state:OR_KY_MA
15. addr_state:MT_MS_SD
16. addr_state:WI_IL_CT_AK
17. addr_state:CO_SC
18. addr_state:KS_NH_WV_VT_ID
19. addr_state:WY_DC_ME
20. verification_status:Not Verified
21. verification_status:Source Verified
22. purpose:credit_card
23. purpose:debt_consolidation
24. purpose:oth__med__vacation
25. purpose:major_purch__car__home_impr
26. initial_list_status:w
27. term:36
28. emp_length:1
29. emp_length:2-4
30. emp_length:5-6
31. emp_length:7-9
32. emp_length:10
33. mths_since_issue_d:<38
34. mths_since_issue_d:38-39
35. mths_since_issue_d:40-41
36. mths_since_issue_d:42-48
37. mths_since_issue_d:49-52
38. mths_since_issue_d:53-64
39. mths_since_issue_d:65-84
40. int_rate:<9.548
41. int_rate:9.548-12.025
42. int_rate:12.025-15.74
43. int_rate:15.74-20.281
44. mths_since_earliest_cr_line:141-164
45. mths_since_earliest_cr_line:165-247
46. mths_since_earliest_cr_line:248-270
47. mths_since_earliest_cr_line:271-352
48. mths_since_earliest_cr_line:>352
49. delinq_2yrs:1-3
50. delinq_2yrs:4-16
51. delinq_2yrs:>=17
52. inq_last_6mths:0
53. inq_last_6mths:1-2
54. inq_last_6mths:3-6
55. open_acc:1-3
56. open_acc:4-12
57. open_acc:13-17
58. open_acc:18-22
59. open_acc:23-25
60. open_acc:26-30
61. open_acc:>=31
62. pub_rec:3-4
63. pub_rec:>=5
64. total_acc:16-70
65. total_acc:71-90
66. total_acc:>90
67. acc_now_delinq:>=1
68. total_rev_hi_lim:5K-10K
69. total_rev_hi_lim:10K-20K
70. total_rev_hi_lim:20K-30K
71. total_rev_hi_lim:30K-40K
72. total_rev_hi_lim:40K-55K
73. total_rev_hi_lim:55K-95K
74. annual_inc:20K-30K
75. annual_inc:30K-40K
76. annual_inc:40K-50K
77. annual_inc:50K-60K
78. annual_inc:60K-70K
79. annual_inc:70K-80K
80. annual_inc:80K-90K
81. annual_inc:90K-100K
82. annual_inc:100K-120K
83. annual_inc:120K-140K
84. annual_inc:>140K
85. dti:<=1.4
86. dti:1.4-3.5
87. dti:3.5-7.7
88. dti:7.7-10.5
89. dti:10.5-16.1
90. dti:16.1-20.3
91. dti:20.3-21.7
92. dti:21.7-22.4
93. dti:22.4-35
94. mths_since_last_delinq:Missing
95. mths_since_last_delinq:4-30
96. mths_since_last_delinq:31-56
97. mths_since_last_delinq:>=57
98. mths_since_last_record:3-20
99. mths_since_last_record:21-31
100. mths_since_last_record:32-80
101. mths_since_last_record:81-86
102. mths_since_last_record:>86

In [41]:
import seaborn as sns
import matplotlib.pyplot as plt

matrix = inputs_train.corr()

matrix

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:ND_NE_IA_NV_FL_HI_AL,addr_state:OK_LA_NC_NM_MO_VA_NJ,...,dti:22.4-35,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
grade:A,1.000000,-0.281766,-0.264622,-0.193788,-0.126141,-0.074456,-0.005355,0.065822,-0.011226,-0.001681,...,-0.086285,0.128550,-0.089807,-0.043991,-0.030146,-0.014320,-0.020827,-0.072079,-0.023405,-0.053254
grade:B,-0.281766,1.000000,-0.391304,-0.286559,-0.186528,-0.110100,-0.001790,0.005986,-0.000170,-0.002915,...,-0.036319,0.009747,-0.009788,0.001302,0.001143,-0.009835,-0.004384,-0.015251,-0.003582,0.018410
grade:C,-0.264622,-0.391304,1.000000,-0.269123,-0.175179,-0.103401,0.000212,-0.016001,0.004297,0.001653,...,0.032247,-0.038853,0.029646,0.010905,0.010037,0.009784,0.009233,0.040123,0.009529,0.017134
grade:D,-0.193788,-0.286559,-0.269123,1.000000,-0.128287,-0.075723,0.003670,-0.035240,0.006286,0.001370,...,0.048506,-0.049909,0.032027,0.019243,0.010826,0.009879,0.010159,0.030623,0.011940,0.006545
grade:E,-0.126141,-0.186528,-0.175179,-0.128287,1.000000,-0.049290,0.003561,-0.015168,-0.001328,0.001286,...,0.041550,-0.038756,0.027700,0.010752,0.007767,0.004840,0.007125,0.015033,0.004892,0.002659
grade:F,-0.074456,-0.110100,-0.103401,-0.075723,-0.049290,1.000000,0.000995,-0.014655,0.001718,0.002427,...,0.022871,-0.025030,0.022792,0.003814,0.000479,0.001742,0.000164,-0.000684,0.000945,0.003665
home_ownership:OWN,-0.005355,-0.001790,0.000212,0.003670,0.003561,0.000995,1.000000,-0.316735,0.015010,0.004878,...,0.024337,0.002729,-0.004635,0.001113,0.000265,0.002403,0.001415,0.003611,0.001795,-0.000842
home_ownership:MORTGAGE,0.065822,0.005986,-0.016001,-0.035240,-0.015168,-0.014655,-0.316735,1.000000,-0.000715,0.041385,...,-0.014438,-0.056982,0.052135,0.008760,0.003075,0.006023,-0.000543,-0.014373,-0.004101,0.013401
addr_state:ND_NE_IA_NV_FL_HI_AL,-0.011226,-0.000170,0.004297,0.006286,-0.001328,0.001718,0.015010,-0.000715,1.000000,-0.127503,...,0.016919,-0.002788,0.000973,0.001981,0.001891,-0.008869,-0.009749,0.000375,-0.001867,-0.004992
addr_state:OK_LA_NC_NM_MO_VA_NJ,-0.001681,-0.002915,0.001653,0.001370,0.001286,0.002427,0.004878,0.041385,-0.127503,1.000000,...,0.008275,-0.002663,0.000934,0.000200,0.001951,-0.005617,-0.003450,-0.006139,-0.003866,-0.002917
addr_state:MD_TN_AZ_PA_MI,-0.007343,-0.003230,0.002688,0.002945,0.006287,0.000298,0.011240,0.045172,-0.122512,-0.141093,...,0.013128,-0.011323,0.005646,0.007143,0.002916,0.000769,0.003794,0.014571,0.006589,0.010379
addr_state:DE_AR,-0.003246,-0.002474,0.001707,0.006248,-0.001155,-0.001880,0.008152,0.029474,-0.033796,-0.038921,...,0.015817,-0.000811,-0.000270,0.001108,0.000552,0.007674,0.006838,-0.001275,-0.002189,0.006646
addr_state:UT_MN_OH_IN_GA_ RI_WA,-0.004469,-0.003753,0.006173,0.000880,-0.000025,0.000308,-0.013105,0.074885,-0.129083,-0.148661,...,0.022412,0.007026,-0.004459,-0.004701,0.000639,0.014136,0.012952,0.027219,0.010724,0.029610
addr_state:OR_KY_MA,0.015130,0.001400,-0.005411,-0.006435,-0.003444,-0.003823,-0.008303,-0.001611,-0.073014,-0.084088,...,-0.013766,0.005884,-0.004689,-0.002725,-0.001289,-0.004341,-0.002183,-0.007210,0.000356,0.001497
addr_state:MT_MS_SD,-0.005239,-0.000930,0.002186,0.003956,0.002512,-0.003241,0.011497,0.018468,-0.029170,-0.033594,...,0.020169,-0.005180,0.003087,0.000196,0.003376,0.007502,0.001617,0.004363,0.001802,0.003423
addr_state:WI_IL_CT_AK,0.005644,0.003611,-0.001681,-0.004966,-0.003062,-0.001754,-0.004065,0.017305,-0.091789,-0.105710,...,-0.013190,0.006663,-0.002246,-0.005570,-0.001090,-0.005699,-0.001110,0.000240,0.003813,0.000308
addr_state:CO_SC,0.005877,-0.001689,-0.000567,-0.003481,-0.000114,0.001539,-0.010695,0.036022,-0.061376,-0.070685,...,0.008763,0.001157,-0.003030,-0.002650,0.005677,0.002455,-0.000512,-0.002475,0.002222,0.008478
addr_state:KS_NH_WV_VT_ID,0.001520,0.000370,0.001976,-0.004297,0.001223,-0.000375,0.008265,0.030923,-0.048603,-0.055974,...,0.016189,0.001720,-0.000454,-0.003987,0.001623,0.001945,0.000367,0.000136,0.002146,0.008057
addr_state:WY_DC_ME,0.008621,-0.001837,-0.004085,-0.002849,0.002404,-0.000452,-0.004919,-0.008674,-0.024759,-0.028514,...,-0.001564,0.002157,-0.001916,-0.001392,0.000756,0.000133,-0.001968,-0.005587,-0.002154,-0.003290
verification_status:Not Verified,0.117284,0.101620,-0.040989,-0.071541,-0.106169,-0.077112,-0.005273,-0.064449,0.003800,-0.004233,...,-0.089238,0.008808,-0.006713,-0.001169,-0.007491,-0.022900,-0.022439,-0.079500,-0.019674,0.015520
verification_status:Source Verified,-0.017459,-0.035396,0.014266,0.029125,0.022870,-0.002244,0.015338,-0.019430,0.001134,0.001386,...,-0.010421,-0.025176,0.017295,0.008658,0.006840,0.017816,0.017785,0.060661,0.015368,-0.009792
purpose:credit_card,0.093869,0.078382,-0.022000,-0.075580,-0.076305,-0.057012,-0.003671,-0.010384,-0.009849,-0.006401,...,0.007552,0.042107,-0.024151,-0.020072,-0.008341,-0.005648,-0.005213,-0.020689,-0.005010,0.004674
purpose:debt_consolidation,-0.081171,-0.015253,0.041273,0.030582,0.024818,0.005066,-0.026413,-0.000507,-0.004494,0.006133,...,0.061570,-0.023975,0.013285,0.010673,0.009324,-0.004559,-0.006387,0.004906,0.003938,0.002686
purpose:oth__med__vacation,-0.042132,-0.061537,-0.011456,0.060306,0.055617,0.054408,0.013065,-0.055636,0.001889,-0.003091,...,-0.023976,-0.008115,0.004040,0.003759,0.000407,0.006225,0.006542,0.004138,0.002655,-0.004876
purpose:major_purch__car__home_impr,0.049291,-0.008355,-0.013468,-0.013175,-0.008685,-0.005959,0.042744,0.095336,0.012948,0.003830,...,-0.067190,-0.015065,0.009948,0.009559,-0.001251,0.008986,0.009615,0.022037,0.000598,0.000244
initial_list_status:w,0.007314,-0.036410,0.022688,0.011794,0.009429,-0.014352,0.008875,0.025263,-0.002068,-0.001948,...,0.039554,-0.034388,0.027863,0.011184,0.003653,0.011740,0.015082,0.053622,0.009629,0.001589
term:36,0.243392,0.221367,-0.063725,-0.152148,-0.243585,-0.186832,0.016805,-0.119319,0.009753,-0.019440,...,-0.059098,0.003309,-0.008126,0.003489,0.002348,0.001549,0.007961,0.021407,0.005510,0.010813
emp_length:1,0.005866,0.002507,-0.004489,-0.000119,-0.002678,-0.003020,-0.007387,-0.070409,-0.000375,0.001817,...,-0.012844,0.014162,-0.001978,-0.012689,-0.007685,-0.001208,-0.001136,-0.011883,-0.004316,-0.017716
emp_length:2-4,0.008673,0.003898,-0.006334,-0.000382,-0.003755,-0.004585,-0.017342,-0.089140,0.002810,0.002032,...,-0.020679,0.018739,-0.012726,-0.000233,-0.011839,-0.000918,-0.000283,-0.011877,-0.005285,-0.029958
emp_length:5-6,0.003082,0.003304,-0.001297,-0.003151,-0.002774,0.000557,-0.008165,-0.011042,0.007234,-0.004037,...,-0.006324,0.014994,-0.021622,-0.003049,0.012528,-0.006014,-0.004323,-0.006253,-0.001788,-0.009180
emp_length:7-9,-0.007384,0.002546,0.003003,-0.001458,0.001056,0.002471,-0.008755,0.026840,0.006570,-0.000592,...,0.007086,0.006551,-0.006635,-0.002958,0.003480,-0.000251,-0.004639,-0.000575,0.002562,0.015548
emp_length:10,-0.010252,-0.007137,0.006699,0.002339,0.006381,0.006508,0.010472,0.163970,-0.017405,0.003598,...,0.020841,-0.054411,0.045849,0.015967,0.004524,0.005775,0.005303,0.011416,0.000298,0.021549
mths_since_issue_d:<38,0.010748,-0.015908,0.010559,-0.001172,0.003440,-0.008279,0.015979,-0.005235,0.004665,-0.002334,...,0.024291,-0.032165,0.023216,0.011252,0.005036,0.013838,0.011945,0.040649,0.008897,-0.015485
mths_since_issue_d:38-39,0.023247,-0.036874,0.010181,0.007188,0.007612,-0.005568,0.013449,-0.007441,0.001408,-0.003915,...,0.034274,-0.034216,0.022587,0.011446,0.009897,0.015093,0.013840,0.058654,0.015831,-0.014917
mths_since_issue_d:40-41,-0.020638,-0.028802,0.000210,0.028904,0.026305,0.009896,0.004927,0.004287,0.000626,-0.001289,...,0.024944,-0.028516,0.023778,0.006672,0.006236,0.009765,0.010029,0.045126,0.009161,-0.003648
mths_since_issue_d:42-48,-0.032196,-0.021092,0.022651,0.030348,0.011247,-0.013435,0.010068,0.018031,-0.010657,0.000015,...,0.021556,-0.041825,0.032498,0.012673,0.006137,0.019857,0.028360,0.076654,0.015831,0.022878
mths_since_issue_d:49-52,-0.032031,0.024607,0.011511,-0.011997,-0.009721,0.013320,0.002772,0.021915,-0.002679,0.001830,...,0.001175,0.007459,0.000036,-0.002296,-0.004749,-0.010547,-0.015110,-0.034338,-0.005744,0.034356
mths_since_issue_d:53-64,-0.025259,0.054037,0.001270,-0.023501,-0.027819,0.006682,-0.022102,0.014403,0.003716,0.000192,...,0.018536,0.031241,-0.021574,-0.006945,-0.002879,-0.020195,-0.023792,-0.084060,-0.020388,0.003789
mths_since_issue_d:65-84,0.085087,0.016387,-0.055453,-0.032364,-0.007597,-0.000239,-0.015466,-0.036045,0.007791,0.006436,...,-0.085234,0.085580,-0.064398,-0.025845,-0.016044,-0.020747,-0.021953,-0.076088,-0.018479,-0.032876
int_rate:<9.548,0.929801,-0.188642,-0.283328,-0.207287,-0.134766,-0.079711,-0.002666,0.064849,-0.010054,-0.000906,...,-0.084935,0.120409,-0.084121,-0.041084,-0.029528,-0.012612,-0.018056,-0.065953,-0.022796,-0.053653
int_rate:9.548-12.025,-0.192665,0.686578,-0.265841,-0.199094,-0.129784,-0.076607,-0.003831,0.014251,-0.002397,-0.002206,...,-0.042431,0.011380,-0.010470,-0.001682,-0.001706,-0.008921,-0.004729,-0.019764,-0.002612,0.014946
int_rate:12.025-15.74,-0.320020,0.023899,0.582232,-0.192043,-0.204980,-0.123963,0.001363,-0.027918,0.003452,-0.001711,...,0.019797,-0.042347,0.027403,0.015822,0.013501,0.010940,0.012220,0.050087,0.012728,0.017343
int_rate:15.74-20.281,-0.234565,-0.346857,-0.051960,0.662205,0.131590,-0.065822,0.000789,-0.028709,0.007537,0.003450,...,0.062759,-0.048391,0.033778,0.016922,0.011205,0.004689,0.006101,0.019217,0.008290,0.014850
mths_since_earliest_cr_line:141-164,-0.025989,-0.000415,0.005356,0.012200,0.006113,0.005644,-0.005658,-0.098450,0.008821,-0.006148,...,-0.004882,0.070611,-0.045579,-0.026566,-0.019529,-0.006223,-0.009043,-0.042297,-0.011819,-0.010557
mths_since_earliest_cr_line:165-247,-0.013967,0.000015,0.004930,0.001412,0.006650,0.003034,-0.026974,-0.011665,-0.005579,0.000431,...,0.003102,-0.013503,-0.010236,0.014221,0.027663,-0.003947,-0.003899,-0.002618,0.009105,0.027415
mths_since_earliest_cr_line:248-270,0.009561,0.000480,-0.002286,-0.006885,-0.001990,0.001680,-0.003737,0.048677,-0.007500,0.005442,...,0.003069,-0.034692,0.019018,0.012788,0.015282,-0.002222,0.002447,0.012777,0.004308,0.009575
mths_since_earliest_cr_line:271-352,0.032293,0.005246,-0.011061,-0.015215,-0.007136,-0.008852,0.010237,0.100875,-0.005349,0.004317,...,0.003411,-0.064499,0.049825,0.017287,0.011000,0.006329,0.003497,0.029407,0.003616,-0.000932
mths_since_earliest_cr_line:>352,0.046564,0.011825,-0.013526,-0.023134,-0.019180,-0.014525,0.036795,0.073890,-0.001406,-0.000040,...,0.007413,-0.059795,0.044651,0.022714,0.002867,0.010764,0.019937,0.038872,0.000845,-0.008349
delinq_2yrs:1-3,-0.081807,-0.012779,0.027594,0.031142,0.026311,0.021986,-0.003912,0.057603,0.001230,-0.000267,...,-0.008497,-0.478903,0.775921,-0.184969,-0.136918,0.016600,0.013177,-0.020651,-0.007968,-0.021406
delinq_2yrs:4-16,-0.031275,-0.008129,0.011969,0.013168,0.011660,0.008504,0.001544,0.018624,-0.004438,0.003065,...,-0.000074,-0.109026,0.168630,-0.042820,-0.031951,0.018038,0.025564,-0.008303,-0.002690,-0.009911
delinq_2yrs:>=17,-0.002674,-0.002994,0.003196,0.000820,0.001511,0.001595,-0.001920,-0.001814,-0.000578,-0.001264,...,-0.001588,-0.006593,0.009574,-0.002542,-0.000343,-0.000401,0.005559,0.003968,-0.000505,-0.001484
inq_last_6mths:0,0.122272,0.089999,-0.043526,-0.081675,-0.075708,-0.074367,0.004970,-0.047198,0.003800,-0.001249,...,0.001371,0.040862,-0.019973,-0.024277,-0.013878,-0.006861,-0.011477,-0.047554,-0.006327,-0.005070
inq_last_6mths:1-2,-0.087526,-0.057321,0.041273,0.054531,0.043649,0.040230,-0.002821,0.025038,-0.000910,0.000377,...,0.000612,-0.029591,0.014104,0.019094,0.010388,0.004957,0.007888,0.028860,0.004319,0.003885
inq_last_6mths:3-6,-0.066156,-0.061123,0.006261,0.051590,0.059167,0.062729,-0.004152,0.042229,-0.005409,0.001691,...,-0.002804,-0.021480,0.012213,0.010113,0.006698,0.003799,0.006806,0.036377,0.003577,0.001775
open_acc:1-3,-0.018312,-0.011228,-0.000095,0.014401,0.014765,0.011729,0.014692,-0.069447,0.001592,-0.001294,...,-0.061688,0.030610,-0.024279,-0.010526,-0.010604,-0.004747,-0.003482,-0.016323,-0.000614,0.000371
open_acc:4-12,-0.006815,0.017931,0.006911,-0.003264,-0.014357,-0.013709,0.003452,-0.085574,0.011061,-0.004906,...,-0.146081,0.031677,-0.031336,-0.002277,0.002191,0.002082,0.011407,0.024971,0.010460,0.030090
open_acc:13-17,0.009927,-0.006052,-0.003178,-0.003950,0.003587,0.003729,-0.007228,0.074269,-0.008575,0.003343,...,0.095301,-0.027837,0.025577,0.004297,0.001438,0.000143,-0.007088,-0.008261,-0.007575,-0.016567
open_acc:18-22,0.006198,-0.008128,-0.004861,0.001840,0.005435,0.005392,-0.002751,0.051458,-0.005704,0.001804,...,0.093940,-0.018150,0.018233,0.001155,-0.000199,-0.001586,-0.005081,-0.015740,-0.004557,-0.019852
open_acc:23-25,-0.001364,-0.007869,-0.003349,0.005910,0.007357,0.005391,-0.000271,0.021423,-0.004576,0.004244,...,0.051300,-0.009654,0.010467,0.001058,-0.002397,-0.000624,-0.003610,-0.009876,-0.002337,-0.010056
open_acc:26-30,-0.000160,-0.009672,-0.002028,0.001538,0.006656,0.009096,-0.000221,0.016457,0.001495,0.001338,...,0.043714,-0.011018,0.009130,0.003421,-0.000053,0.001058,-0.001238,-0.007631,-0.000702,-0.006894
open_acc:>=31,-0.001546,-0.008444,-0.000441,0.000362,0.007688,0.008507,0.004918,0.008673,0.001258,-0.000893,...,0.031020,-0.004389,0.004567,-0.002057,0.001210,-0.000801,-0.001636,-0.003385,-0.002539,-0.003703
pub_rec:3-4,-0.020808,-0.007401,0.007258,0.013105,0.006823,0.005300,0.002171,-0.005493,-0.008434,-0.003705,...,-0.013455,-0.022484,-0.000190,0.012582,0.024730,0.137419,0.108377,0.179074,0.006924,-0.004932
pub_rec:>=5,-0.009768,-0.003683,0.002400,0.008785,0.003143,0.000210,0.004435,-0.001293,-0.005257,-0.002250,...,-0.006710,-0.014388,0.001611,0.006547,0.014959,0.123011,0.084994,0.066432,0.002850,-0.002581
total_acc:16-70,0.054111,0.005750,-0.015048,-0.030825,-0.011233,-0.007889,-0.022445,0.211572,-0.016276,0.016258,...,0.119341,-0.180970,0.118419,0.074936,0.044968,0.007894,0.010304,0.053156,-0.004481,-0.038898
total_acc:71-90,0.000005,-0.000010,-0.003860,0.000288,0.001459,0.006698,0.004680,0.007975,-0.001674,0.004170,...,0.011242,-0.011019,0.008183,0.004518,0.001123,-0.000805,0.001115,0.005665,-0.002637,-0.005542
total_acc:>90,-0.000135,-0.002804,-0.001153,0.003680,-0.001344,0.004017,-0.000877,0.001106,0.005308,-0.001791,...,0.005302,-0.000073,-0.000403,-0.000419,0.001796,-0.000719,0.002546,0.009532,-0.000906,-0.002660
acc_now_delinq:>=1,-0.022042,-0.008760,0.005425,0.011201,0.011125,0.009112,0.000702,0.015613,0.001025,-0.001431,...,0.004327,-0.066623,-0.032402,-0.025681,-0.019133,0.011291,0.003225,0.000046,-0.002450,-0.003398
total_rev_hi_lim:5K-10K,-0.024922,-0.014498,0.016853,0.024856,-0.002818,0.000588,0.000868,-0.095723,0.011041,-0.003657,...,-0.065623,-0.031622,0.012827,0.019530,0.014511,0.003361,0.017009,0.058758,0.016470,0.021760
total_rev_hi_lim:10K-20K,-0.090389,0.013009,0.026340,0.028156,0.014840,0.005992,-0.007562,-0.077370,0.010448,-0.009060,...,-0.033055,-0.037658,0.011269,0.025722,0.023165,0.003316,0.009463,0.064336,0.021317,0.057336
total_rev_hi_lim:20K-30K,-0.040127,0.011706,0.000832,0.000779,0.018081,0.019087,-0.003233,0.013167,0.000986,-0.001255,...,0.030806,-0.003610,-0.000484,0.005053,0.002974,-0.001602,-0.008510,-0.014556,-0.002909,0.017365
total_rev_hi_lim:30K-40K,0.011304,0.002827,-0.006198,-0.014063,0.003303,0.006809,-0.002657,0.054918,-0.006182,0.003490,...,0.043557,0.015654,-0.005851,-0.012339,-0.004977,-0.003444,-0.009208,-0.041868,-0.012425,-0.024263
total_rev_hi_lim:40K-55K,0.050612,0.001757,-0.013570,-0.020961,-0.010590,-0.014999,-0.000682,0.082751,-0.012691,0.006367,...,0.050165,0.030996,-0.010581,-0.019903,-0.016637,-0.002836,-0.011931,-0.051003,-0.017528,-0.042559
total_rev_hi_lim:55K-95K,0.113277,-0.000900,-0.031614,-0.038405,-0.030843,-0.022538,0.009419,0.102599,-0.015429,0.006589,...,0.038644,0.054970,-0.021982,-0.034167,-0.027410,-0.004893,-0.009940,-0.051124,-0.018864,-0.055683
annual_inc:20K-30K,-0.033537,-0.000090,0.021256,0.020301,-0.006969,-0.011099,0.056807,-0.150396,0.023293,-0.004768,...,0.044281,0.055543,-0.044023,-0.018459,-0.007352,-0.006272,-0.002641,0.007391,0.009296,0.016072
annual_inc:30K-40K,-0.044915,0.006501,0.022174,0.017651,-0.001560,-0.009563,0.038489,-0.135065,0.026063,-0.001670,...,0.070015,0.042795,-0.038321,-0.012760,0.002195,-0.006659,-0.001751,0.012403,0.007894,0.023913
annual_inc:40K-50K,-0.035728,0.008753,0.017126,0.009078,-0.000058,-0.007189,0.012432,-0.078989,0.013021,0.001467,...,0.058357,0.023581,-0.023725,-0.005146,0.004722,-0.005034,-0.000119,0.012971,0.007382,0.017529
annual_inc:50K-60K,-0.019747,0.003623,0.008713,0.004128,0.001953,0.000654,-0.003973,-0.009347,0.000712,-0.004816,...,0.036835,-0.000708,-0.007421,0.004025,0.010544,-0.002137,-0.001173,0.008424,0.001433,0.013686
annual_inc:60K-70K,-0.004636,0.002484,-0.002614,-0.001200,0.002631,0.006841,-0.017952,0.032219,-0.002939,-0.001713,...,0.007325,-0.015252,0.007504,0.008166,0.005875,-0.003380,-0.000980,0.002392,0.000941,0.001700
annual_inc:70K-80K,0.006725,-0.000583,-0.006649,-0.004650,0.002476,0.008621,-0.020320,0.054179,-0.007571,-0.000636,...,-0.012370,-0.017344,0.014530,0.004304,0.002598,0.000017,-0.001343,-0.007244,-0.002518,-0.002705
annual_inc:80K-90K,0.026093,-0.000032,-0.012342,-0.011291,-0.003609,0.002384,-0.022573,0.063524,-0.012160,0.000946,...,-0.028333,-0.022487,0.019352,0.006791,0.000096,0.000615,0.001829,-0.008011,-0.006781,-0.009903
annual_inc:90K-100K,0.033013,-0.004333,-0.014571,-0.010492,-0.003184,0.005841,-0.019964,0.071983,-0.010574,0.000354,...,-0.039392,-0.022821,0.022113,0.005301,-0.001911,0.001385,-0.000040,-0.011719,-0.004857,-0.015583
annual_inc:100K-120K,0.040503,-0.003417,-0.017895,-0.016542,0.000574,-0.000052,-0.023973,0.094160,-0.018715,0.004358,...,-0.058401,-0.027184,0.027760,0.006068,-0.003320,0.002247,0.001247,-0.011715,-0.008267,-0.023782
annual_inc:120K-140K,0.035168,-0.005654,-0.013991,-0.010807,-0.002335,0.000666,-0.016252,0.072656,-0.011532,0.004024,...,-0.055940,-0.019559,0.022658,0.005100,-0.008816,0.005594,-0.000993,-0.007362,-0.006179,-0.018742
annual_inc:>140K,0.049471,-0.011600,-0.020533,-0.015366,0.002907,0.000592,-0.012096,0.100800,-0.015003,0.007725,...,-0.100294,-0.032634,0.036609,0.006391,-0.012332,0.024153,0.008556,-0.011128,-0.009094,-0.033170
dti:<=1.4,0.041117,-0.005744,-0.017576,-0.010373,-0.003809,0.000459,0.005811,-0.010824,-0.003165,0.000238,...,-0.052400,0.010326,-0.008546,-0.002530,-0.008739,0.001116,0.002179,-0.001631,-0.001086,-0.009068
dti:1.4-3.5,0.039141,-0.000364,-0.016405,-0.011488,-0.008290,-0.001728,0.005216,-0.015895,-0.002194,-0.003708,...,-0.085472,0.001889,-0.003923,0.002563,-0.003014,0.004015,0.010995,0.016587,0.002439,0.001760
dti:3.5-7.7,0.056830,0.013204,-0.020792,-0.024049,-0.022656,-0.012835,-0.004554,-0.013330,-0.011633,-0.006807,...,-0.184593,-0.006364,0.002225,0.006684,-0.001857,0.008138,0.017569,0.026842,0.006291,0.015152
dti:7.7-10.5,0.040133,0.015927,-0.015421,-0.021328,-0.018471,-0.011876,-0.005653,0.002527,-0.006289,-0.003427,...,-0.191723,-0.012546,0.009091,0.009506,-0.001817,0.004520,0.008342,0.016907,0.004421,0.008325
dti:10.5-16.1,0.032221,0.019151,-0.009068,-0.020890,-0.022576,-0.012024,-0.019878,0.017451,-0.007988,-0.004451,...,-0.338354,-0.015777,0.010396,0.009780,0.000094,0.001598,0.000017,0.010420,0.001448,0.007001
dti:16.1-20.3,-0.011014,0.006390,0.005007,-0.003560,-0.000573,0.001382,-0.006422,0.016620,0.000741,0.002093,...,-0.282689,0.002009,0.000108,-0.003993,0.001368,-0.006506,-0.005180,-0.010591,-0.004834,-0.001628
dti:20.3-21.7,-0.017538,-0.000686,0.006655,0.004235,0.005564,0.003351,0.000674,0.000128,0.003105,0.000544,...,-0.143587,0.005664,-0.003304,-0.004078,0.001611,-0.002305,-0.007090,-0.010287,-0.002466,-0.004367

# PD Model Estimation

## Logistic Regression

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [43]:
reg = LogisticRegression()
# We create an instance of an object from the 'LogisticRegression' class.

In [44]:
pd.options.display.max_rows = None
# Sets the pandas dataframe options to display all columns/ rows.

In [45]:
reg.fit(inputs_train, loan_data_targets_train)
# Estimates the coefficients of the object from the 'LogisticRegression' class
# with inputs (independent variables) contained in the first dataframe
# and targets (dependent variables) contained in the second dataframe.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [46]:
reg.intercept_
# Displays the intercept contain in the estimated ("fitted") object from the 'LogisticRegression' class.

array([-0.23794822])

In [47]:
reg.coef_
# Displays the coefficients contained in the estimated ("fitted") object from the 'LogisticRegression' class.

array([[ 0.91776658,  0.69590012,  0.50025311,  0.33196487,  0.1956864 ,
         0.06780163,  0.0866661 ,  0.12361225, -0.10739435, -0.04164462,
        -0.02416677,  0.00335134,  0.04536689,  0.04584019,  0.108213  ,
         0.18148385,  0.20458932,  0.25389356,  0.59906368,  0.08940471,
        -0.01407579,  0.28370973,  0.17213477,  0.19892856,  0.23614486,
         0.04017614,  0.06217105,  0.12277695,  0.10871407,  0.06777127,
         0.06073242,  0.11799418,  0.9161122 ,  0.79375492,  0.71008392,
         0.53839591,  0.42156338,  0.20658153, -0.02179143,  0.99897184,
         0.6430071 ,  0.39831535,  0.16893927,  0.0857547 ,  0.07099143,
         0.11316473,  0.14987942,  0.1643695 , -0.06922189, -0.11778823,
        -0.02295317,  0.31461707,  0.17886653, -0.00977696,  0.04659772,
        -0.01631672, -0.031007  , -0.05771993, -0.05228246, -0.03670136,
        -0.03249014, -0.00842389,  0.08074442, -0.04991334, -0.09627516,
        -0.00664038,  0.18805794, -0.01213365, -0.01987495, -0.02116007,
        -0.01538357,  0.03192159,  0.02900604, -0.149047  , -0.08448131,
         0.01037424,  0.06474911,  0.15138078,  0.21020728,  0.25370672,
         0.26543715,  0.34652217,  0.44859333,  0.40281653,  0.06084198,
         0.20794798,  0.18376178,  0.12784087,  0.08629161, -0.01370096,
        -0.02412753, -0.07907949, -0.10546611,  0.07758577,  0.12514442,
         0.12119261,  0.10990139, -0.00738773,  0.03670485,  0.21345652,
        -0.10275447, -0.06361616]])

In [48]:
feature_name = inputs_train.columns.values
# Stores the names of the columns of a dataframe in a variable.

In [49]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
# Creates a dataframe with a column titled 'Feature name' and row values contained in the 'feature_name' variable.
summary_table['Coefficients'] = np.transpose(reg.coef_)
# Creates a new column in the dataframe, called 'Coefficients',
# with row values the transposed coefficients from the 'LogisticRegression' object.
summary_table.index = summary_table.index + 1
# Increases the index of every row of the dataframe with 1.
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
# Assigns values of the row with index 0 of the dataframe.
summary_table = summary_table.sort_index()
# Sorts the dataframe by index.
summary_table

                            Feature name  Coefficients
0                              Intercept     -0.237948
1                                grade:A      0.917767
2                                grade:B      0.695900
3                                grade:C      0.500253
4                                grade:D      0.331965
5                                grade:E      0.195686
6                                grade:F      0.067802
7                     home_ownership:OWN      0.086666
8                home_ownership:MORTGAGE      0.123612
9        addr_state:ND_NE_IA_NV_FL_HI_AL     -0.107394
10       addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.041645
11             addr_state:MD_TN_AZ_PA_MI     -0.024167
12                      addr_state:DE_AR      0.003351
13      addr_state:UT_MN_OH_IN_GA_ RI_WA      0.045367
14                   addr_state:OR_KY_MA      0.045840
15                   addr_state:MT_MS_SD      0.108213
16                addr_state:WI_IL_CT_AK      0.181484
17                      addr_state:CO_SC      0.204589
18             addr_state:KS_NH_WV_VT_ID      0.253894
19                   addr_state:WY_DC_ME      0.599064
20      verification_status:Not Verified      0.089405
21   verification_status:Source Verified     -0.014076
22                   purpose:credit_card      0.283710
23            purpose:debt_consolidation      0.172135
24            purpose:oth__med__vacation      0.198929
25   purpose:major_purch__car__home_impr      0.236145
26                 initial_list_status:w      0.040176
27                               term:36      0.062171
28                          emp_length:1      0.122777
29                        emp_length:2-4      0.108714
30                        emp_length:5-6      0.067771
31                        emp_length:7-9      0.060732
32                         emp_length:10      0.117994
33                mths_since_issue_d:<38      0.916112
34              mths_since_issue_d:38-39      0.793755
35              mths_since_issue_d:40-41      0.710084
36              mths_since_issue_d:42-48      0.538396
37              mths_since_issue_d:49-52      0.421563
38              mths_since_issue_d:53-64      0.206582
39              mths_since_issue_d:65-84     -0.021791
40                       int_rate:<9.548      0.998972
41                 int_rate:9.548-12.025      0.643007
42                 int_rate:12.025-15.74      0.398315
43                 int_rate:15.74-20.281      0.168939
44   mths_since_earliest_cr_line:141-164      0.085755
45   mths_since_earliest_cr_line:165-247      0.070991
46   mths_since_earliest_cr_line:248-270      0.113165
47   mths_since_earliest_cr_line:271-352      0.149879
48      mths_since_earliest_cr_line:>352      0.164369
49                       delinq_2yrs:1-3     -0.069222
50                      delinq_2yrs:4-16     -0.117788
51                      delinq_2yrs:>=17     -0.022953
52                      inq_last_6mths:0      0.314617
53                    inq_last_6mths:1-2      0.178867
54                    inq_last_6mths:3-6     -0.009777
55                          open_acc:1-3      0.046598
56                         open_acc:4-12     -0.016317
57                        open_acc:13-17     -0.031007
58                        open_acc:18-22     -0.057720
59                        open_acc:23-25     -0.052282
60                        open_acc:26-30     -0.036701
61                         open_acc:>=31     -0.032490
62                           pub_rec:3-4     -0.008424
63                           pub_rec:>=5      0.080744
64                       total_acc:16-70     -0.049913
65                       total_acc:71-90     -0.096275
66                         total_acc:>90     -0.006640
67                    acc_now_delinq:>=1      0.188058
68               total_rev_hi_lim:5K-10K     -0.012134
69              total_rev_hi_lim:10K-20K     -0.019875
70              total_rev_hi_lim:20K-30K     -0.021160
71              total_rev_hi_lim:30K-40K     -0.015384
72              total_rev_hi_lim:40K-55K      0.031922
73              total_rev_hi_lim:55K-95K      0.029006
74                    annual_inc:20K-30K     -0.149047
75                    annual_inc:30K-40K     -0.084481
76                    annual_inc:40K-50K      0.010374
77                    annual_inc:50K-60K      0.064749
78                    annual_inc:60K-70K      0.151381
79                    annual_inc:70K-80K      0.210207
80                    annual_inc:80K-90K      0.253707
81                   annual_inc:90K-100K      0.265437
82                  annual_inc:100K-120K      0.346522
83                  annual_inc:120K-140K      0.448593
84                      annual_inc:>140K      0.402817
85                             dti:<=1.4      0.060842
86                           dti:1.4-3.5      0.207948
87                           dti:3.5-7.7      0.183762
88                          dti:7.7-10.5      0.127841
89                         dti:10.5-16.1      0.086292
90                         dti:16.1-20.3     -0.013701
91                         dti:20.3-21.7     -0.024128
92                         dti:21.7-22.4     -0.079079
93                           dti:22.4-35     -0.105466
94        mths_since_last_delinq:Missing      0.077586
95           mths_since_last_delinq:4-30      0.125144
96          mths_since_last_delinq:31-56      0.121193
97           mths_since_last_delinq:>=57      0.109901
98           mths_since_last_record:3-20     -0.007388
99          mths_since_last_record:21-31      0.036705
100         mths_since_last_record:32-80      0.213457
101         mths_since_last_record:81-86     -0.102754
102           mths_since_last_record:>86     -0.063616

In [50]:
bool_cols = inputs_train.select_dtypes(include=['bool']).columns
inputs_train[bool_cols] = inputs_train[bool_cols].astype(int)

## Build a Logistic Regression Model with P-Values

In [51]:
# P values for sklearn logistic regression.

# Class to display p-values for logistic regression in sklearn.

from sklearn import linear_model
import scipy.stats as stat

class LogisticRegression_with_p_values:

    def __init__(self,*args,**kwargs):#,**kwargs):
        self.model = linear_model.LogisticRegression(*args,**kwargs)#,**args)

    def fit(self,X,y):
        self.model.fit(X,y)

        #### Get p-values for the fitted model ####
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(X))))
        denom = np.tile(denom,(X.shape[1],1)).T
        F_ij = np.dot((X / denom).T,X) ## Fisher Information Matrix
        Cramer_Rao = np.linalg.inv(F_ij) ## Inverse Information Matrix
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.model.coef_[0] / sigma_estimates # z-score for eaach model coefficient
        p_values = [stat.norm.sf(abs(x)) * 2 for x in z_scores] ### two tailed test for p-values

        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        self.p_values = p_values

In [52]:
reg = LogisticRegression_with_p_values()
# We create an instance of an object from the newly created 'LogisticRegression_with_p_values()' class.

In [53]:
loan_data_targets_train = loan_data_targets_train.values.ravel()

In [54]:
reg.fit(inputs_train, loan_data_targets_train)
# Estimates the coefficients of the object from the 'LogisticRegression' class
# with inputs (independent variables) contained in the first dataframe
# and targets (dependent variables) contained in the second dataframe.

In [55]:
# Same as above.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                            Feature name  Coefficients
0                              Intercept     -0.237948
1                                grade:A      0.917767
2                                grade:B      0.695900
3                                grade:C      0.500253
4                                grade:D      0.331965
5                                grade:E      0.195686
6                                grade:F      0.067802
7                     home_ownership:OWN      0.086666
8                home_ownership:MORTGAGE      0.123612
9        addr_state:ND_NE_IA_NV_FL_HI_AL     -0.107394
10       addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.041645
11             addr_state:MD_TN_AZ_PA_MI     -0.024167
12                      addr_state:DE_AR      0.003351
13      addr_state:UT_MN_OH_IN_GA_ RI_WA      0.045367
14                   addr_state:OR_KY_MA      0.045840
15                   addr_state:MT_MS_SD      0.108213
16                addr_state:WI_IL_CT_AK      0.181484
17                      addr_state:CO_SC      0.204589
18             addr_state:KS_NH_WV_VT_ID      0.253894
19                   addr_state:WY_DC_ME      0.599064
20      verification_status:Not Verified      0.089405
21   verification_status:Source Verified     -0.014076
22                   purpose:credit_card      0.283710
23            purpose:debt_consolidation      0.172135
24            purpose:oth__med__vacation      0.198929
25   purpose:major_purch__car__home_impr      0.236145
26                 initial_list_status:w      0.040176
27                               term:36      0.062171
28                          emp_length:1      0.122777
29                        emp_length:2-4      0.108714
30                        emp_length:5-6      0.067771
31                        emp_length:7-9      0.060732
32                         emp_length:10      0.117994
33                mths_since_issue_d:<38      0.916112
34              mths_since_issue_d:38-39      0.793755
35              mths_since_issue_d:40-41      0.710084
36              mths_since_issue_d:42-48      0.538396
37              mths_since_issue_d:49-52      0.421563
38              mths_since_issue_d:53-64      0.206582
39              mths_since_issue_d:65-84     -0.021791
40                       int_rate:<9.548      0.998972
41                 int_rate:9.548-12.025      0.643007
42                 int_rate:12.025-15.74      0.398315
43                 int_rate:15.74-20.281      0.168939
44   mths_since_earliest_cr_line:141-164      0.085755
45   mths_since_earliest_cr_line:165-247      0.070991
46   mths_since_earliest_cr_line:248-270      0.113165
47   mths_since_earliest_cr_line:271-352      0.149879
48      mths_since_earliest_cr_line:>352      0.164369
49                       delinq_2yrs:1-3     -0.069222
50                      delinq_2yrs:4-16     -0.117788
51                      delinq_2yrs:>=17     -0.022953
52                      inq_last_6mths:0      0.314617
53                    inq_last_6mths:1-2      0.178867
54                    inq_last_6mths:3-6     -0.009777
55                          open_acc:1-3      0.046598
56                         open_acc:4-12     -0.016317
57                        open_acc:13-17     -0.031007
58                        open_acc:18-22     -0.057720
59                        open_acc:23-25     -0.052282
60                        open_acc:26-30     -0.036701
61                         open_acc:>=31     -0.032490
62                           pub_rec:3-4     -0.008424
63                           pub_rec:>=5      0.080744
64                       total_acc:16-70     -0.049913
65                       total_acc:71-90     -0.096275
66                         total_acc:>90     -0.006640
67                    acc_now_delinq:>=1      0.188058
68               total_rev_hi_lim:5K-10K     -0.012134
69              total_rev_hi_lim:10K-20K     -0.019875
70              total_rev_hi_lim:20K-30K     -0.021160
71              total_rev_hi_lim:30K-40K     -0.015384
72              total_rev_hi_lim:40K-55K      0.031922
73              total_rev_hi_lim:55K-95K      0.029006
74                    annual_inc:20K-30K     -0.149047
75                    annual_inc:30K-40K     -0.084481
76                    annual_inc:40K-50K      0.010374
77                    annual_inc:50K-60K      0.064749
78                    annual_inc:60K-70K      0.151381
79                    annual_inc:70K-80K      0.210207
80                    annual_inc:80K-90K      0.253707
81                   annual_inc:90K-100K      0.265437
82                  annual_inc:100K-120K      0.346522
83                  annual_inc:120K-140K      0.448593
84                      annual_inc:>140K      0.402817
85                             dti:<=1.4      0.060842
86                           dti:1.4-3.5      0.207948
87                           dti:3.5-7.7      0.183762
88                          dti:7.7-10.5      0.127841
89                         dti:10.5-16.1      0.086292
90                         dti:16.1-20.3     -0.013701
91                         dti:20.3-21.7     -0.024128
92                         dti:21.7-22.4     -0.079079
93                           dti:22.4-35     -0.105466
94        mths_since_last_delinq:Missing      0.077586
95           mths_since_last_delinq:4-30      0.125144
96          mths_since_last_delinq:31-56      0.121193
97           mths_since_last_delinq:>=57      0.109901
98           mths_since_last_record:3-20     -0.007388
99          mths_since_last_record:21-31      0.036705
100         mths_since_last_record:32-80      0.213457
101         mths_since_last_record:81-86     -0.102754
102           mths_since_last_record:>86     -0.063616

In [56]:
# This is a list.
p_values = reg.p_values
# We take the result of the newly added method 'p_values' and store it in a variable 'p_values'.

In [57]:
# Add the intercept for completeness.
p_values = np.append(np.nan, np.array(p_values))
# We add the value 'NaN' in the beginning of the variable with p-values.

In [58]:
summary_table['p_values'] = p_values
# In the 'summary_table' dataframe, we add a new column, called 'p_values', containing the values from the 'p_values' variable.

In [ ]:
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>=86',
]]

In [ ]:
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [ ]:
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
inputs_train.head()

In [ ]:
# Here we run a new model.
reg2 = LogisticRegression_with_p_values()
reg2.fit(inputs_train, loan_data_targets_train)

In [ ]:
feature_name = inputs_train.columns.values

In [ ]:
# Same as above.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg2.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg2.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

In [ ]:
# We add the 'p_values' here, just as we did before.
p_values = reg2.p_values
p_values = np.append(np.nan,np.array(p_values))
summary_table['p_values'] = p_values
summary_table
# Here we get the results for our final PD model.

In [ ]:
import pickle

In [ ]:
pickle.dump(reg2, open('pd_model.sav', 'wb'))
# Here we export our model to a 'SAV' file with file name 'pd_model.sav'.