<a href="https://colab.research.google.com/github/awildt01/Credit-Scoring/blob/main/notebooks/3__select_feature.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Zumanenfassung

## **- Verwendete Methode zur Feature-Auswahl**

In diesem Schritt wird eine Kombination aus **manueller Feature-Selektion** und der **Vermeidung der Dummy-Variablen-Falle** angewendet.



### **Manuelle Feature-Selektion**

Die Auswahl der über 100 verwendeten Variablen wurde bereits in einem vorherigen Notebook durchgeführt.
Dabei kam kein automatisierter Algorithmus zum Einsatz, sondern eine gezielte Analyse durch den Analysten.
Zu den eingesetzten Methoden zählen unter anderem:

- **explorative Datenanalyse (EDA)**

- **Berechnung des Information Value (IV)**

- **Analyse des Weight of Evidence (WoE)**

Auf dieser Grundlage wurde entschieden, welche Variablen für das Modell am relevantesten sind.



### **Vermeidung der Dummy-Variablen-Falle**

Bei kategorialen Variablen mit *k* Kategorien entstehen nach dem One-Hot-Encoding *k* Dummy-Variablen.
Wenn **alle** Dummy-Variablen verwendet werden, führt das zu **perfekter Multikollinearität**.
Dies ist insbesondere bei **linearer** und **logistischer Regression** problematisch.

**Lösung:**
Aus jeder Gruppe von Dummy-Variablen wird **eine Kategorie entfernt**.
Diese entfernte Variable wird zur **Referenzkategorie**, die als Vergleichsbasis dient.

**Beispiel:**
Im Code wird die Variable **term:60** (Laufzeit: 60 Monate) entfernt.
Der Koeffizient von **term:36** misst dann den Unterschied im Kreditrisiko im Vergleich zur Referenz **term:60**.



**Fazit**

Die eigentliche Feature-Auswahl wurde bereits in einem vorherigen Schritt getroffen.
Der hier gezeigte Code sorgt dafür, dass die gewählten Variablen korrekt für die Modellierung vorbereitet werden, indem er **Multikollinearität vermeidet** und gleichzeitig eine **Referenzkategorie für die Interpretation** festlegt.

## **1. Vorbereitung der Eingabedaten**

**Feature-Auswahl und Referenzkategorien für die logistische Regression**

**1- Auswahl der Features (Variablenauswahl):** Zuerst wird ein neuer DataFrame **inputs_train_with_ref_cat** erstellt. Dieser enthält nur eine spezifische Auswahl von Spalten (Features) aus dem ursprünglichen Trainingsdatensatz **loan_data_inputs_train**. Die ausgewählten Spalten sind bereits in **"Dummy-Variablen"** umgewandelt worden. Das bedeutet, dass kategoriale Variablen wie grade (Kreditwürdigkeitsstufe) oder home_ownership (Wohneigentum-Status) in mehrere binäre (0/1) Spalten aufgeteilt wurden.

**2- Definition der Referenzkategorien:** Eine Liste namens **ref_categories** wird erstellt. Diese Liste enthält die Namen von Dummy-Variablen, die als "Referenzkategorien" dienen sollen. Für jede ursprüngliche kategoriale Variable (z.B. grade) wird eine ihrer Dummy-Variablen (hier grade:G) in diese Liste aufgenommen.

**3- Entfernen der Referenzkategorien:** Die in der **ref_categories-Liste** definierten Spalten werden aus dem DataFrame inputs_train_with_ref_cat entfernt. Das Ergebnis ist ein neuer, finaler DataFrame inputs_train, der für das Modelltraining verwendet wird.
Zusammenfassend lässt sich sagen: Der Code selektiert eine Reihe von vorverarbeiteten Features und entfernt dann aus jeder kategorialen Gruppe eine Referenzkategorie, um Multikollinearität zu vermeiden.

Zusammenfassend ist die Definition einer Referenzkategorie eine technische Notwendigkeit, um **Multikollinearität zu vermeiden**, und gleichzeitig ein mächtiges Werkzeug für die Interpretation, da sie den Bezugsrahmen für die Bewertung aller anderen Kategorien festlegt.

### **1.1 Was ist eine Referenzkategorie?**

Eine Referenzkategorie ist die Basiskategorie, mit der alle anderen Kategorien einer kategorialen Variable verglichen werden, wenn sie in einem statistischen Modell (wie der logistischen oder linearen Regression) verwendet wird.
Stellen Sie sich vor, Sie möchten den Einfluss der home_ownership (Wohneigentum-Status) auf das Kreditrisiko untersuchen. Diese Variable hat drei mögliche Ausprägungen (Kategorien): MORTGAGE (Hypothek), OWN (Eigentum) und RENT (Miete).
Ein Computer kann mit den Textwerten "MORTGAGE" oder "RENT" nicht direkt rechnen. Deshalb wandeln wir sie in Dummy-Variablen um. Das sieht so aus:

| home_ownership | home_ownership:MORTGAGE | home_ownership:OWN | home_ownership:RENT |
|----------------|-------------------------|--------------------|---------------------|
| MORTGAGE       | 1                       | 0                  | 0                   |
| OWN            | 0                       | 1                  | 0                   |
| RENT           | 0                       | 0                  | 1                   |



**Das Problem: Die "Dummy-Variablen-Falle" (Multikollinearität)**

Wenn wir alle drei Dummy-Variablen in ein Regressionsmodell aufnehmen, stoßen wir auf ein Problem namens perfekte Multikollinearität. Das bedeutet, dass eine Variable perfekt aus den anderen vorhergesagt werden kann.
  - Beispiel: Wenn home_ownership:MORTGAGE = 0 und home_ownership:OWN = 0 ist, dann muss home_ownership:RENT = 1 sein. Es gibt keine andere Möglichkeit.

Diese redundante Information verwirrt das Modell. Es kann keine eindeutigen Koeffizienten für jede Kategorie berechnen, weil ihre Effekte nicht voneinander zu trennen sind. Mathematisch führt dies zu einem Fehler.

**Die Lösung:**

Eine Kategorie als Referenzpunkt festlegen
Um dieses Problem zu lösen, lassen wir einfach eine der Dummy-Variablen weg. Die weggelassene Kategorie wird zur Referenzkategorie.
In Ihrem Code wurde für home_ownership die Kategorie RENT_OTHER_NONE_ANY als Referenz gewählt. Nehmen wir an, wir vereinfachen das auf RENT. Dann sieht der Datensatz, den das Modell tatsächlich verwendet, so aus:

| home_ownership | home_ownership:MORTGAGE | home_ownership:OWN |
|----------------|-------------------------|--------------------|
| MORTGAGE       | 1                       | 0                  |
| OWN            | 0                       | 1                  |
| RENT           | 0                       | 0                  |

**Wie wird das jetzt interpretiert?**

- Ein Kreditnehmer mit MORTGAGE wird durch home_ownership:MORTGAGE = 1 identifiziert.
- Ein Kreditnehmer mit OWN wird durch home_ownership:OWN = 1 identifiziert.
- Ein Kreditnehmer mit RENT (die Referenzkategorie) wird dadurch identifiziert, dass beide anderen Spalten 0 sind. Er ist der "Standardfall".

**Die Bedeutung im Modell:** Alles ist relativ

Wenn das Modell trainiert wird, berechnet es Koeffizienten (Gewichte) für home_ownership:MORTGAGE und home_ownership:OWN. Diese Koeffizienten beschreiben den Unterschied im Effekt im Vergleich zur Referenzkategorie (RENT).
Angenommen, das Modell liefert folgende (fiktive) Koeffizienten für die Wahrscheinlichkeit eines Kreditausfalls:
- home_ownership:MORTGAGE: -0.25
- home_ownership:OWN: -0.10

**Interpretation:**

- Der negative Koeffizient von -0.25 für MORTGAGE bedeutet: Kreditnehmer mit einer Hypothek haben ein geringeres Kreditausfallrisiko als Kreditnehmer, die zur Miete wohnen.
- Der Koeffizient von -0.10 für OWN bedeutet: Kreditnehmer mit Eigenheim haben ebenfalls ein geringeres Risiko als Mieter, aber der risikomindernde Effekt ist nicht so stark wie bei Hypothekennehmern.

Die Referenzkategorie (RENT) hat keinen eigenen Koeffizienten. Ihr Effekt ist sozusagen im "Grundrauschen" des Modells (dem Intercept oder Achsenabschnitt) enthalten. Sie ist der Nullpunkt, von dem aus die anderen Effekte gemessen werden.

### **1.2 Wie wählt man die Referenzkategorie aus?**

Die Wahl der Referenzkategorie ist eine strategische Entscheidung. Übliche Vorgehensweisen sind:
1. **Die häufigste Kategorie:** Das macht die Interpretation der anderen Koeffizienten oft intuitiv, da sie den Unterschied zur "normalsten" Gruppe zeigen.
2. **Die Kategorie mit dem geringsten Risiko (oder Erfolg):** Wenn man z.B. grade:G (die schlechteste Bonitätsnote) als Referenz wählt, werden alle anderen Koeffizienten (grade:A, grade:B etc.) positiv sein und zeigen, um wie viel besser diese Noten im Vergleich zur schlechtesten sind. Dies ist in Ihrem Code der Fall und eine sehr gängige Praxis in der Kreditrisikomodellierung.
3. **Eine logische "Basis"-Kategorie:** Zum Beispiel könnte man bei einer medizinischen Studie die "Placebo"-Gruppe als Referenz wählen.

**Zusammenfassung des Workflows: Von Koeffizienten zur Variablenselektion**

**Ziel:**  
Die Identifikation und Beibehaltung **nur der statistisch signifikanten Variablen** im finalen PD-Modell.

---

**Ablauf:**

1.  **Berechnung der Koeffizienten:**
    *   Der erste Schritt ist die Schätzung des Modells, um die **Koeffizienten** (Gewichte) für jede Dummy-Variable zu erhalten.
    *   Diese Koeffizienten zeigen Richtung und Stärke des Einflusses einer Variable auf die Ausfallwahrscheinlichkeit.

2.  **Berechnung der p-Werte:**
    *   Im nächsten Schritt werden die **multivariaten p-Werte** für jeden dieser Koeffizienten berechnet.
    *   Die p-Werte dienen als "Realitäts-Check". Sie quantifizieren, ob ein gefundener Effekt statistisch signifikant ist oder nur zufällig auftreten könnte.

3.  **Selektion der Variablengruppen (der entscheidende Schritt):**
    *   Anhand der p-Werte werden nicht einzelne Dummy-Variablen, sondern **ganze Gruppen** von Dummy-Variablen bewertet, die zusammen eine ursprüngliche Variable (z.B. `grade`) repräsentieren.
    *   **Entscheidungsregel:**
        *   **Behalten, wenn:** Mindestens eine Dummy-Variable in der Gruppe einen signifikanten p-Wert (p < 0.05) aufweist.
        *   **Entfernen, wenn:** **Keine einzige** Dummy-Variable in der Gruppe einen signifikanten Effekt hat.

---

**Warum dieser Ansatz?**  
Diese Methodik stellt sicher, dass das finale Modell nicht nur statistisch robust ist, sondern auch inhaltlich-logisch interpretierbar bleibt. Eine ursprüngliche Variable (wie das Einkommen) wird entweder vollständig im Modell behalten oder vollständig entfernt. Dies verhindert ein unvollständiges oder verzerrtes Bild der Realität.

**Ergebnis:**  
Ein schlankes, stabiles und aussagekräftiges Modell, das nur die stärksten und zuverlässigsten Prädiktoren für die Kreditausfallwahrscheinlichkeit enthält.

**Kurz gesagt:**  
Die Schätzung der Koeffizienten ist die Grundlage, um die p-Werte zu berechnen, welche uns wiederum die Selektionsentscheidung für die Variablengruppen erlauben.

 ### **1.3 Loading the data and selecting the features**

#### **1.3.1 Import Libraries**

In [ ]:
import numpy as np
import pandas as pd

from google.colab import drive
import os

In [ ]:
# Google Drive mounten
drive.mount('/content/drive')

# Zielordner definieren
folder_path = '/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks'
os.makedirs(folder_path, exist_ok=True)  # Ordner erstellen, falls nicht vorhanden

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
loan_data_inputs_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_train.csv', index_col = 0,)

In [ ]:
loan_data_targets_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_train.csv', index_col = 0,header=0)

In [ ]:
loan_data_inputs_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_test.csv',index_col = 0,)

In [ ]:
loan_data_targets_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_test.csv',index_col = 0, header=0)

#### **1.3.2 Explore Data**

In [ ]:
pd.set_option('display.max_info_rows', 300)

loan_data_inputs_train.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,dti:21.7-22.4,dti:22.4-35,dti:>35,mths_since_last_record:Missing,mths_since_last_record:0-2,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
427211,292984,29074404,31607606,11250,11250,11250.0,60 months,16.99,279.54,D,...,0,0,0,1,0,0,0,0,0,0
206088,57793,9026077,10838105,8000,8000,8000.0,36 months,18.55,291.44,D,...,0,1,0,1,0,0,0,0,0,0
136020,140700,4865088,6157358,6000,6000,6000.0,36 months,10.16,194.06,B,...,0,0,0,1,0,0,0,0,0,0
412305,297571,28764454,31297687,8000,8000,8000.0,36 months,9.17,255.04,B,...,0,0,0,1,0,0,0,0,0,0
36159,5264,985083,1208540,5000,5000,5000.0,36 months,11.71,165.38,B,...,0,0,0,1,0,0,0,0,0,0

In [ ]:
loan_data_targets_train.head()

        good_bad
427211         1
206088         1
136020         1
412305         1
36159          0

In [ ]:
loan_data_inputs_train.shape

(373028, 330)

In [ ]:
loan_data_targets_train.shape

(373028, 1)

In [ ]:
for i, col in enumerate(loan_data_inputs_train.columns, 1):
    print(f"{i}. {col}")

1. Unnamed: 0
2. id
3. member_id
4. loan_amnt
5. funded_amnt
6. funded_amnt_inv
7. term
8. int_rate
9. installment
10. grade
11. sub_grade
12. emp_title
13. emp_length
14. home_ownership
15. annual_inc
16. verification_status
17. issue_d
18. loan_status
19. pymnt_plan
20. url
21. desc
22. purpose
23. title
24. zip_code
25. addr_state
26. dti
27. delinq_2yrs
28. earliest_cr_line
29. inq_last_6mths
30. mths_since_last_delinq
31. mths_since_last_record
32. open_acc
33. pub_rec
34. revol_bal
35. revol_util
36. total_acc
37. initial_list_status
38. out_prncp
39. out_prncp_inv
40. total_pymnt
41. total_pymnt_inv
42. total_rec_prncp
43. total_rec_int
44. total_rec_late_fee
45. recoveries
46. collection_recovery_fee
47. last_pymnt_d
48. last_pymnt_amnt
49. next_pymnt_d
50. last_credit_pull_d
51. collections_12_mths_ex_med
52. mths_since_last_major_derog
53. policy_code
54. application_type
55. annual_inc_joint
56. dti_joint
57. verification_status_joint
58. acc_now_delinq
59. tot_coll_amt
60. tot_cur_bal
61. open_acc_6m
62. open_il_6m
63. open_il_12m
64. open_il_24m
65. mths_since_rcnt_il
66. total_bal_il
67. il_util
68. open_rv_12m
69. open_rv_24m
70. max_bal_bc
71. all_util
72. total_rev_hi_lim
73. inq_fi
74. total_cu_tl
75. inq_last_12m
76. emp_length_missing
77. emp_length_int
78. term_int
79. earliest_cr_line_date
80. months_since_earliest_cr_line
81. issue_d_date
82. mths_since_issue_d
83. grade:A
84. grade:B
85. grade:C
86. grade:D
87. grade:E
88. grade:F
89. grade:G
90. sub_grade:A1
91. sub_grade:A2
92. sub_grade:A3
93. sub_grade:A4
94. sub_grade:A5
95. sub_grade:B1
96. sub_grade:B2
97. sub_grade:B3
98. sub_grade:B4
99. sub_grade:B5
100. sub_grade:C1
101. sub_grade:C2
102. sub_grade:C3
103. sub_grade:C4
104. sub_grade:C5
105. sub_grade:D1
106. sub_grade:D2
107. sub_grade:D3
108. sub_grade:D4
109. sub_grade:D5
110. sub_grade:E1
111. sub_grade:E2
112. sub_grade:E3
113. sub_grade:E4
114. sub_grade:E5
115. sub_grade:F1
116. sub_grade:F2
117. sub_grade:F3
118. sub_grade:F4
119. sub_grade:F5
120. sub_grade:G1
121. sub_grade:G2
122. sub_grade:G3
123. sub_grade:G4
124. sub_grade:G5
125. home_ownership:ANY
126. home_ownership:MORTGAGE
127. home_ownership:NONE
128. home_ownership:OTHER
129. home_ownership:OWN
130. home_ownership:RENT
131. verification_status:Not Verified
132. verification_status:Source Verified
133. verification_status:Verified
134. loan_status:Charged Off
135. loan_status:Current
136. loan_status:Default
137. loan_status:Does not meet the credit policy. Status:Charged Off
138. loan_status:Does not meet the credit policy. Status:Fully Paid
139. loan_status:Fully Paid
140. loan_status:In Grace Period
141. loan_status:Late (16-30 days)
142. loan_status:Late (31-120 days)
143. purpose:car
144. purpose:credit_card
145. purpose:debt_consolidation
146. purpose:educational
147. purpose:home_improvement
148. purpose:house
149. purpose:major_purchase
150. purpose:medical
151. purpose:moving
152. purpose:other
153. purpose:renewable_energy
154. purpose:small_business
155. purpose:vacation
156. purpose:wedding
157. addr_state:AK
158. addr_state:AL
159. addr_state:AR
160. addr_state:AZ
161. addr_state:CA
162. addr_state:CO
163. addr_state:CT
164. addr_state:DC
165. addr_state:DE
166. addr_state:FL
167. addr_state:GA
168. addr_state:HI
169. addr_state:IA
170. addr_state:ID
171. addr_state:IL
172. addr_state:IN
173. addr_state:KS
174. addr_state:KY
175. addr_state:LA
176. addr_state:MA
177. addr_state:MD
178. addr_state:ME
179. addr_state:MI
180. addr_state:MN
181. addr_state:MO
182. addr_state:MS
183. addr_state:MT
184. addr_state:NC
185. addr_state:NE
186. addr_state:NH
187. addr_state:NJ
188. addr_state:NM
189. addr_state:NV
190. addr_state:NY
191. addr_state:OH
192. addr_state:OK
193. addr_state:OR
194. addr_state:PA
195. addr_state:RI
196. addr_state:SC
197. addr_state:SD
198. addr_state:TN
199. addr_state:TX
200. addr_state:UT
201. addr_state:VA
202. addr_state:VT
203. addr_state:WA
204. addr_state:WI
205. addr_state:WV
206. addr_state:WY
207. initial_list_status:f
208. initial_list_status:w
209. home_ownership:RENT_OTHER_NONE_ANY
210. addr_state:ND
211. addr_state:ND_NE_IA_NV_FL_HI_AL
212. addr_state:OK_LA_NC_NM_MO_VA_NJ
213. addr_state:MD_TN_AZ_PA_MI
214. addr_state:DE_AR
215. addr_state:UT_MN_OH_IN_GA_ RI_WA
216. addr_state:OR_KY_MA
217. addr_state:MT_MS_SD
218. addr_state:WI_IL_CT_AK
219. addr_state:CO_SC
220. addr_state:KS_NH_WV_VT_ID
221. addr_state:WY_DC_ME
222. purpose:educ__sm_b__wedd__ren_en__mov__house
223. purpose:oth__med__vacation
224. purpose:major_purch__car__home_impr
225. term:36
226. term:60
227. emp_length:0
228. emp_length:1
229. emp_length:2-4
230. emp_length:5-6
231. emp_length:7-9
232. emp_length:10
233. mths_since_issue_d_factor
234. mths_since_issue_d:<38
235. mths_since_issue_d:38-39
236. mths_since_issue_d:40-41
237. mths_since_issue_d:42-48
238. mths_since_issue_d:49-52
239. mths_since_issue_d:53-64
240. mths_since_issue_d:65-84
241. mths_since_issue_d:>84
242. int_rate_factor
243. int_rate:<9.548
244. int_rate:9.548-12.025
245. int_rate:12.025-15.74
246. int_rate:15.74-20.281
247. int_rate:>20.281
248. funded_amnt_factor
249. mths_since_earliest_cr_line_factor
250. mths_since_earliest_cr_line:<140
251. mths_since_earliest_cr_line:141-164
252. mths_since_earliest_cr_line:165-247
253. mths_since_earliest_cr_line:248-270
254. mths_since_earliest_cr_line:271-352
255. mths_since_earliest_cr_line:>352
256. delinq_2yrs:0
257. delinq_2yrs:1-3
258. delinq_2yrs:4-16
259. delinq_2yrs:>=17
260. inq_last_6mths:0
261. inq_last_6mths:1-2
262. inq_last_6mths:3-6
263. inq_last_6mths:>6
264. open_acc:0
265. open_acc:1-3
266. open_acc:4-12
267. open_acc:13-17
268. open_acc:18-22
269. open_acc:23-25
270. open_acc:26-30
271. open_acc:>=31
272. pub_rec:0-2
273. pub_rec:3-4
274. pub_rec:>=5
275. total_acc_factor
276. total_acc:0-15
277. total_acc:16-70
278. total_acc:71-90
279. total_acc:>90
280. acc_now_delinq:0
281. acc_now_delinq:>=1
282. total_rev_hi_lim_factor
283. total_rev_hi_lim:<=5K
284. total_rev_hi_lim:5K-10K
285. total_rev_hi_lim:10K-20K
286. total_rev_hi_lim:20K-30K
287. total_rev_hi_lim:30K-40K
288. total_rev_hi_lim:40K-55K
289. total_rev_hi_lim:55K-95K
290. installment_factor
291. installment:<=800
292. installment:801-1100
293. installment:1101-1250
294. installment:>1250
295. annual_inc_factor
296. annual_inc:<20K
297. annual_inc:20K-30K
298. annual_inc:30K-40K
299. annual_inc:40K-50K
300. annual_inc:50K-60K
301. annual_inc:60K-70K
302. annual_inc:70K-80K
303. annual_inc:80K-90K
304. annual_inc:90K-100K
305. annual_inc:100K-120K
306. annual_inc:120K-140K
307. annual_inc:>140K
308. mths_since_last_delinq:Missing
309. mths_since_last_delinq:0-3
310. mths_since_last_delinq:4-30
311. mths_since_last_delinq:31-56
312. mths_since_last_delinq:>=57
313. dti_factor
314. dti:<=1.4
315. dti:1.4-3.5
316. dti:3.5-7.7
317. dti:7.7-10.5
318. dti:10.5-16.1
319. dti:16.1-20.3
320. dti:20.3-21.7
321. dti:21.7-22.4
322. dti:22.4-35
323. dti:>35
324. mths_since_last_record:Missing
325. mths_since_last_record:0-2
326. mths_since_last_record:3-20
327. mths_since_last_record:21-31
328. mths_since_last_record:32-80
329. mths_since_last_record:81-86
330. mths_since_last_record:>86

#### 1.3.3 Selecting the Features

In [ ]:
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',

'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',

 #'addr_state:ND',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:OK_LA_NC_NM_MO_VA_NJ',
'addr_state:MD_TN_AZ_PA_MI',
'addr_state:DE_AR',
'addr_state:UT_MN_OH_IN_GA_ RI_WA',
'addr_state:OR_KY_MA',
'addr_state:MT_MS_SD',
'addr_state:WI_IL_CT_AK',
'addr_state:CO_SC',
'addr_state:KS_NH_WV_VT_ID',
'addr_state:WY_DC_ME',

'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',

'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',

'initial_list_status:f',
'initial_list_status:w',

'term:36',
'term:60',

'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',

'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',

'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',

'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',


'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:4-16',
'delinq_2yrs:>=17',


'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',


'open_acc:0',
'open_acc:1-3',
'open_acc:4-12',
'open_acc:13-17',
'open_acc:18-22',
'open_acc:23-25',
'open_acc:26-30',
'open_acc:>=31',

'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',

'total_acc:0-15',
'total_acc:16-70',
'total_acc:71-90',
'total_acc:>90',

'acc_now_delinq:0',
'acc_now_delinq:>=1',

'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',



'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',

'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',


'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',

'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',

]]

#### 1.3.4 Referenzkategorie-Dummyvariablen:

- Hier speichern wir die Namen der Referenzkategorie-Dummyvariablen in einer Liste.

In [ ]:
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
#'addr_state:ND',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:0',
'inq_last_6mths:>6',
'open_acc:0',
'pub_rec:0-2',
'total_acc:0-15',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

- Bei kategorialen Variablen mit k Kategorien entstehen nach dem One-Hot-Encoding k Dummy-Variablen.
- Wenn alle Dummy-Variablen beibehalten werden, führt das zu perfekter Multikollinearität, was insbesondere bei linearer und logistischer Regression problematisch ist.

- Aus jeder Gruppe von Dummy-Variablen wird eine Kategorie entfernt.
Diese entfernte Variable wird zur Referenzkategorie, die als Vergleichsbasis dient.

In [ ]:
# Referenzkategorie-Dummyvariablen werden raugenommen aus.
pd.set_option('display.max_info_rows', 100)
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
inputs_train.sample(100)

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:OK_LA_NC_NM_MO_VA_NJ,addr_state:MD_TN_AZ_PA_MI,...,dti:22.4-35,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
370664,False,True,False,False,False,False,False,True,0,1,...,0,1,0,0,0,0,0,0,0,0
196069,True,False,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
24565,False,True,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
416421,False,False,False,True,False,False,False,True,1,0,...,0,0,1,0,0,0,0,0,0,0
464892,False,False,False,False,True,False,True,False,1,0,...,0,0,0,1,0,0,0,0,0,0
116938,False,False,True,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,1
93923,False,False,True,False,False,False,False,False,0,0,...,0,0,0,1,0,0,0,0,0,0
396149,False,False,True,False,False,False,False,True,0,0,...,1,1,0,0,0,0,0,0,0,0
45438,True,False,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
65787,False,True,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
120250,False,True,False,False,False,False,True,False,1,0,...,0,0,0,0,1,0,0,0,0,0
85096,False,True,False,False,False,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
325968,False,False,True,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
271361,False,True,False,False,False,False,False,False,0,0,...,0,0,0,0,1,0,0,0,0,0
117542,False,True,False,False,False,False,False,True,0,0,...,1,1,0,0,0,0,0,0,0,0
83264,False,True,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
54838,True,False,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
61201,False,False,True,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
258875,False,False,True,False,False,False,False,True,0,1,...,0,1,0,0,0,0,0,0,0,0
364779,False,False,True,False,False,False,False,True,1,0,...,1,1,0,0,0,0,0,0,0,0
169358,False,True,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,1
283664,False,False,False,True,False,False,True,False,0,0,...,1,0,0,1,0,0,0,0,0,0
449191,False,False,False,True,False,False,False,True,0,0,...,0,0,0,1,0,0,0,0,0,1
265987,False,False,True,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,1,0
202468,True,False,False,False,False,False,False,True,1,0,...,0,1,0,0,0,0,0,0,0,0
71968,True,False,False,False,False,False,False,True,0,1,...,0,1,0,0,0,0,0,0,0,0
446927,False,False,True,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
82383,False,True,False,False,False,False,True,False,0,0,...,0,0,0,1,0,0,0,0,0,0
404587,False,False,True,False,False,False,False,True,0,1,...,1,1,0,0,0,0,0,1,0,0
213768,False,True,False,False,False,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
389590,False,False,False,True,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
240820,False,False,True,False,False,False,False,False,0,0,...,1,1,0,0,0,0,0,1,0,0
278432,False,False,False,True,False,False,False,True,0,1,...,0,1,0,0,0,0,0,0,0,1
380862,False,False,True,False,False,False,False,False,2,0,...,1,0,0,1,0,0,0,0,0,0
92745,False,True,False,False,False,False,False,True,0,0,...,1,0,1,0,0,0,0,0,0,0
318696,True,False,False,False,False,False,False,False,0,0,...,1,1,0,0,0,0,0,0,0,0
400448,False,False,True,False,False,False,True,False,0,0,...,0,0,0,0,1,0,0,0,0,0
422608,True,False,False,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
407786,False,True,False,False,False,False,False,True,0,0,...,1,0,0,1,0,0,0,0,0,0
1977,False,False,False,True,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
119565,False,False,True,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
413470,False,False,False,True,False,False,False,True,0,1,...,0,1,0,0,0,0,0,0,0,0
460685,False,False,True,False,False,False,False,True,0,1,...,0,0,1,0,0,0,0,0,0,0
248406,False,False,False,True,False,False,False,True,0,0,...,1,0,1,0,0,0,0,1,0,0
376125,False,True,False,False,False,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
305335,False,False,True,False,False,False,False,False,0,0,...,0,0,0,1,0,0,0,0,0,0
22991,False,False,True,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
70654,False,True,False,False,False,False,False,True,0,1,...,1,1,0,0,0,0,0,0,0,0
341021,False,True,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
204448,True,False,False,False,False,False,False,True,0,1,...,0,0,1,0,0,0,0,0,0,0
86724,False,False,True,False,False,False,False,False,0,1,...,0,0,0,0,1,0,0,0,0,0
158274,False,True,False,False,False,False,True,False,1,0,...,1,1,0,0,0,0,0,0,0,0
198773,False,False,False,True,False,False,False,False,0,0,...,1,0,1,0,0,0,0,0,0,0
199328,False,False,False,False,True,False,True,False,1,0,...,0,1,0,0,0,0,0,0,0,0
196330,True,False,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
275978,False,False,False,False,True,False,False,False,0,0,...,1,1,0,0,0,0,0,0,0,0
73389,True,False,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
318458,False,False,False,False,True,False,False,True,0,0,...,1,1,0,0,0,0,0,0,0,0
202048,False,False,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
378492,False,False,False,False,False,True,False,True,0,0,...,1,1,0,0,0,0,0,0,0,0
42592,True,False,False,False,False,False,False,True,2,0,...,0,1,0,0,0,0,0,0,0,0
329863,False,False,False,False,True,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,1
408443,False,False,True,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
382967,False,False,True,False,False,False,False,False,0,0,...,0,0,0,0,1,0,0,0,0,0
335624,False,True,False,False,False,False,True,False,0,0,...,0,1,0,0,0,0,0,0,0,0
216836,False,True,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
187871,False,False,True,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
109322,False,True,False,False,False,False,True,False,0,0,...,0,1,0,0,0,0,0,0,0,0
390890,False,False,False,False,False,True,False,True,0,0,...,0,0,0,1,0,0,0,0,0,0
464602,True,False,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
213833,False,False,False,True,False,False,False,False,0,0,...,1,1,0,0,0,0,0,0,0,0
36027,False,False,False,True,False,False,False,True,0,1,...,0,1,0,0,0,0,0,0,0,0
151847,False,False,False,False,False,True,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
43126,False,False,True,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
165683,False,False,False,True,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,1
103755,False,True,False,False,False,False,False,False,1,0,...,0,1,0,0,0,0,0,0,0,0
324689,False,True,False,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
124012,False,False,False,True,False,False,False,False,0,0,...,0,0,0,1,0,0,0,0,0,0
82586,False,False,False,True,False,False,False,False,0,0,...,1,0,0,1,0,0,0,0,0,0
39450,False,True,False,False,False,False,False,False,1,0,...,0,1,0,0,0,0,0,0,0,0
269080,False,False,True,False,False,False,False,True,0,0,...,0,0,0,1,0,0,0,0,0,0
196367,False,True,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
294045,False,False,True,False,False,False,False,True,0,0,...,0,0,0,1,0,0,0,0,0,0
78430,False,True,False,False,False,False,False,False,0,0,...,0,0,0,0,1,0,0,0,0,0
5038,True,False,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
426089,False,False,True,False,False,False,False,False,0,0,...,1,1,0,0,0,0,0,0,0,0
305169,False,False,True,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
267015,False,True,False,False,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
383397,False,False,False,False,True,False,True,False,0,0,...,1,1,0,0,0,0,0,0,0,0
381390,True,False,False,False,False,False,False,True,0,0,...,1,1,0,0,0,0,0,1,0,0
213992,False,True,False,False,False,False,False,True,0,0,...,0,1,0,0,0,0,0,0,0,0
48751,False,True,False,False,False,False,False,False,0,0,...,0,0,1,0,0,0,0,0,0,0
67146,False,True,False,False,False,False,False,True,0,0,...,0,0,1,0,0,0,0,0,0,0
333506,False,True,False,False,False,False,False,True,0,0,...,0,0,0,1,0,0,0,0,0,0
439715,True,False,False,False,False,False,False,False,0,0,...,0,0,0,0,0,0,0,0,0,0
344336,False,False,False,False,True,False,False,True,1,0,...,0,0,1,0,0,0,0,0,0,1
384101,False,False,True,False,False,False,False,True,0,1,...,0,0,0,0,1,0,0,1,0,0
367860,False,False,False,False,True,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
85966,False,False,False,True,False,False,False,False,0,0,...,0,1,0,0,0,0,0,0,0,0
233883,False,False,True,False,False,False,False,True,1,0,...,1,0,0,0,1,0,0,0,0,0

In [1]:
# Spalten Zeigen
#for i, col in enumerate(inputs_train.columns, 1):
   # print(f"{i}. {col}")

## **2. PD Model Estimation**

In diesem Schritt wird ein logistisches Regressionsmodell geschätzt, um die Wahrscheinlichkeit eines Kreditausfalls (Probability of Default, PD) zu modellieren.
Das Ziel ist nicht, bereits das finale Modell zu bauen, sondern die Koeffizienten (Gewichte) der ausgewählten Variablen zu berechnen und den Zusammenhang zwischen den Merkmalen und dem Ausfallrisiko sichtbar zu machen.
Die geschätzten Koeffizienten dienen als Grundlage für die spätere Modellvalidierung und für den Aufbau einer Scorecard.

**Interpretation der Koeffizienten:**

- Ein positiver Koeffizient bedeutet, dass mit zunehmendem Wert dieser Variable das Risiko eines Ausfalls steigt.
Beispiel: Wenn die Variable „delinq_2yrs“ (Anzahl früherer Zahlungsausfälle) einen positiven Koeffizienten hat, dann erhöht jeder zusätzliche Zahlungsausfall die Ausfallwahrscheinlichkeit.

- Ein negativer Koeffizient bedeutet, dass mit zunehmendem Wert dieser Variable das Risiko eines Ausfalls sinkt.
Beispiel: Hat die Variable „annual_inc“ (Jahreseinkommen) einen negativen Koeffizienten, so reduziert ein höheres Einkommen die Ausfallwahrscheinlichkeit.

Die Schätzung der Koeffizienten im PD-Modell ist ein wichtiger Schritt, da sie es uns ermöglicht, die Beziehung zwischen den unabhängigen Variablen (z. B. demographische Daten, Kreditmerkmale) und der Wahrscheinlichkeit eines Kreditausfalls zu quantifizieren.

Hier sind die Schritte, wie die Koeffizienten ermittelt werden:

1- **Logistische Regression:** Das PD-Modell wird in der Regel mit einer logistischen Regression geschätzt, da diese Methode gut geeignet ist, um Wahrscheinlichkeiten für binäre Ergebnisse (z. B. Ausfall oder kein Ausfall) vorherzusagen.

2- **Odss-Verhältnis:** Bei der logistischen Regression wird das Verhältnis der Wahrscheinlichkeiten (Odds) für die zwei möglichen Ergebnisse (z. B. Ausfall vs. Nicht-Ausfall) analysiert. Die logarithmische Umwandlung dieser Wahrscheinlichkeiten ermöglicht die Linearität, die für die Regression erforderlich ist.

3- **Koeffizienten:** Die Koeffizienten, die durch das Schätzen des Modells erhalten werden, repräsentieren die Veränderung des logarithmischen Odds der abhängigen Variable (z. B. Ausfall) entsprechend einer Einheit Veränderung der jeweiligen unabhängigen Variablen. Ein positiver Koeffizient deutet darauf hin, dass mit steigenden Werten der unabhängigen Variablen die Wahrscheinlichkeit eines Ausfalls steigt, während ein negativer Koeffizient das Gegenteil anzeigt.

**Interpretation der Koeffizienten:**

- Ein positiver Koeffizient bedeutet, dass mit zunehmendem Wert dieser Variable das Risiko eines Ausfalls steigt.
Beispiel: Wenn die Variable „delinq_2yrs“ (Anzahl früherer Zahlungsausfälle) einen positiven Koeffizienten hat, dann erhöht jeder zusätzliche Zahlungsausfall die Ausfallwahrscheinlichkeit.

- Ein negativer Koeffizient bedeutet, dass mit zunehmendem Wert dieser Variable das Risiko eines Ausfalls sinkt.
Beispiel: Hat die Variable „annual_inc“ (Jahreseinkommen) einen negativen Koeffizienten, so reduziert ein höheres Einkommen die Ausfallwahrscheinlichkeit.

Zusammengefasst dient die PD-Modellschätzung nicht nur der Vorhersage, sondern auch der Risikoanalyse und Entscheidungsfindung im Kreditgeschäft.

Vorgehensweise:

#### **2.1 Modellinitialisierung:**

- Import der Klasse **LogisticRegression** aus sklearn.linear_model.

- Erstellen einer Instanz dieser Klasse: **reg = LogisticRegression()**.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [ ]:
# Wir erstellen eine Instanz eines Objekts der Klasse 'LogisticRegression'
reg = LogisticRegression()


#### **2.2 Konfiguration der Anzeige:**

- Um die vollständige Ausgabe aller Ergebnisse sicherzustellen, wird die Anzeigeoption von pandas so eingestellt, dass alle Zeilen angezeigt werden (pd.set_option('display.max_rows', None)).

In [ ]:
# Anzeigebreite anpassen:
pd.options.display.max_rows = None

#### **2.3 Modellschätzung:**

- Das Modell wird mit den Trainingsdaten angepasst: reg.fit(inputs_train, loan_data_targets_train).

- **inputs_train** ist der DataFrame, der alle unabhängigen Dummy-Variablen ohne die Referenzkategorien enthält.

- loan_data_targets_train ist der DataFrame, der die abhängige Variable (Zielvariable) „good/bad“ enthält.

In [ ]:
# Schätzt die Koeffizienten des Objekts der 'LogisticRegression'-Klasse
# mit Eingabewerten (unabhängige Variablen) aus dem ersten DataFrame
# und Zielwerten (abhängige Variablen) aus dem zweiten DataFrame.
reg.fit(inputs_train, loan_data_targets_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

#### **2.4 Extraktion der Koeffizienten:**

- Der Achsenabschnitt (Intercept) wird mit reg.intercept_ abgerufen.

- Die Koeffizienten der unabhängigen Variablen werden mit reg.coef_ abgerufen. Diese sind in der gleichen Reihenfolge wie die Spalten in inputs_train angeordnet.

In [ ]:
# Zeigt den Achsenabschnitt, der im geschätzten ("angepassten") Objekt der 'LogisticRegression'-Klasse enthalten ist.
reg.intercept_

array([-0.22888533])

In [ ]:
reg.coef_
# Zeigt die Koeffizienten, die im geschätzten ("angepassten") Objekt der 'LogisticRegression'-Klasse enthalten sind.

array([[ 0.91379219,  0.6810852 ,  0.48525663,  0.31865566,  0.18176718,
         0.0539709 ,  0.08339154,  0.11849199, -0.01883835,  0.00495697,
         0.0277987 ,  0.07478424,  0.07778338,  0.14437675,  0.2077891 ,
         0.22516539,  0.28307281,  0.62601643,  0.08871873, -0.01444945,
         0.28992394,  0.17956721,  0.20506786,  0.24224472,  0.04019079,
         0.0611153 ,  0.1201992 ,  0.10780958,  0.06599999,  0.05984226,
         0.11821753,  0.91784983,  0.79520111,  0.71147941,  0.53797731,
         0.42347469,  0.20558765, -0.02189845,  0.99598279,  0.64695559,
         0.40138435,  0.17241209,  0.07867354,  0.06415454,  0.10513601,
         0.14344511,  0.15745962, -0.06782673, -0.12201778, -0.02130859,
         0.30871449,  0.17103258, -0.01903637,  0.03766524, -0.01562803,
        -0.02536233, -0.05196009, -0.0562118 , -0.03236376, -0.03047309,
        -0.00664533,  0.07801373, -0.04977451, -0.09052146, -0.00662704,
         0.18466315, -0.01664752, -0.02374649, -0.02325923, -0.017043  ,
         0.03269818,  0.03152765, -0.15670714, -0.09272089,  0.00372511,
         0.06013317,  0.14667223,  0.20674147,  0.25151699,  0.26329264,
         0.34508079,  0.43330102,  0.39597758,  0.05636225,  0.2057382 ,
         0.18545976,  0.12689253,  0.08361986, -0.01748772, -0.02827905,
        -0.0849081 , -0.11101718,  0.07068199,  0.11989603,  0.11624458,
         0.10527508, -0.00269612,  0.04101116,  0.21270516, -0.10649226,
        -0.0640969 ]])

#### **2.5 Erstellung einer Ergebnistabelle:**

- Die Namen der unabhängigen Variablen werden aus den Spalten von inputs_train in einer Variable feature_name gespeichert.

- Ein DataFrame summary_table wird erstellt, mit einer Spalte Feature name (aus feature_name) und einer Spalte Coefficients (die transponierten Koeffizienten aus reg.coef_ mittels numpy).

- **Hinzufügen des Intercepts:**

- Der Intercept wird als erste Zeile in die summary_table eingefügt. Dazu werden zunächst die Indizes aller vorhandenen Zeilen um 1 erhöht, um Platz für den Intercept-Eintrag mit dem Index 0 zu schaffen.

- Die erste Zeile (Index 0) wird mit den Werten Intercept und dem tatsächlichen Intercept-Wert befüllt.

- Abschließend wird die Tabelle nach dem Index sortiert, um den Intercept an erster Stelle zu halten.

In [ ]:
feature_name = inputs_train.columns.values
# Stores the names of the columns of a dataframe in a variable.

In [ ]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
# Speichert die Namen der Spalten eines Dataframes in einer Variable.
summary_table['Coefficients'] = np.transpose(reg.coef_)
# Erstellt einen Dataframe mit einer Spalte mit dem Titel 'Feature name' und Zeilenwerten aus der Variable 'feature_name'.
# Erstellt eine neue Spalte im Dataframe mit dem Namen 'Coefficients',
# deren Zeilenwerte die transponierten Koeffizienten aus dem 'LogisticRegression'-Objekt sind.
summary_table.index = summary_table.index + 1
# Erhöht den Index jeder Zeile des Dataframes um 1.
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
# Weist Werte der Zeile mit Index 0 des Dataframes zu.
summary_table = summary_table.sort_index()
# Sortiert den Dataframe nach Index.
#summary_table

In [ ]:
bool_cols = inputs_train.select_dtypes(include=['bool']).columns
inputs_train[bool_cols] = inputs_train[bool_cols].astype(int)

#### **2.6. Ergebnis:**

- Die summary_table bietet eine übersichtliche Darstellung aller Modellkoeffizienten (einschließlich Intercept) zusammen mit den zugehörigen Variablennamen und dient als Grundlage für die weitere Analyse und Interpretation des Modells.

In [ ]:
summary_table

                            Feature name  Coefficients
0                              Intercept     -0.228885
1                                grade:A      0.913792
2                                grade:B      0.681085
3                                grade:C      0.485257
4                                grade:D      0.318656
5                                grade:E      0.181767
6                                grade:F      0.053971
7                     home_ownership:OWN      0.083392
8                home_ownership:MORTGAGE      0.118492
9        addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.018838
10             addr_state:MD_TN_AZ_PA_MI      0.004957
11                      addr_state:DE_AR      0.027799
12      addr_state:UT_MN_OH_IN_GA_ RI_WA      0.074784
13                   addr_state:OR_KY_MA      0.077783
14                   addr_state:MT_MS_SD      0.144377
15                addr_state:WI_IL_CT_AK      0.207789
16                      addr_state:CO_SC      0.225165
17             addr_state:KS_NH_WV_VT_ID      0.283073
18                   addr_state:WY_DC_ME      0.626016
19      verification_status:Not Verified      0.088719
20   verification_status:Source Verified     -0.014449
21                   purpose:credit_card      0.289924
22            purpose:debt_consolidation      0.179567
23            purpose:oth__med__vacation      0.205068
24   purpose:major_purch__car__home_impr      0.242245
25                 initial_list_status:w      0.040191
26                               term:36      0.061115
27                          emp_length:1      0.120199
28                        emp_length:2-4      0.107810
29                        emp_length:5-6      0.066000
30                        emp_length:7-9      0.059842
31                         emp_length:10      0.118218
32                mths_since_issue_d:<38      0.917850
33              mths_since_issue_d:38-39      0.795201
34              mths_since_issue_d:40-41      0.711479
35              mths_since_issue_d:42-48      0.537977
36              mths_since_issue_d:49-52      0.423475
37              mths_since_issue_d:53-64      0.205588
38              mths_since_issue_d:65-84     -0.021898
39                       int_rate:<9.548      0.995983
40                 int_rate:9.548-12.025      0.646956
41                 int_rate:12.025-15.74      0.401384
42                 int_rate:15.74-20.281      0.172412
43   mths_since_earliest_cr_line:141-164      0.078674
44   mths_since_earliest_cr_line:165-247      0.064155
45   mths_since_earliest_cr_line:248-270      0.105136
46   mths_since_earliest_cr_line:271-352      0.143445
47      mths_since_earliest_cr_line:>352      0.157460
48                       delinq_2yrs:1-3     -0.067827
49                      delinq_2yrs:4-16     -0.122018
50                      delinq_2yrs:>=17     -0.021309
51                      inq_last_6mths:0      0.308714
52                    inq_last_6mths:1-2      0.171033
53                    inq_last_6mths:3-6     -0.019036
54                          open_acc:1-3      0.037665
55                         open_acc:4-12     -0.015628
56                        open_acc:13-17     -0.025362
57                        open_acc:18-22     -0.051960
58                        open_acc:23-25     -0.056212
59                        open_acc:26-30     -0.032364
60                         open_acc:>=31     -0.030473
61                           pub_rec:3-4     -0.006645
62                           pub_rec:>=5      0.078014
63                       total_acc:16-70     -0.049775
64                       total_acc:71-90     -0.090521
65                         total_acc:>90     -0.006627
66                    acc_now_delinq:>=1      0.184663
67               total_rev_hi_lim:5K-10K     -0.016648
68              total_rev_hi_lim:10K-20K     -0.023746
69              total_rev_hi_lim:20K-30K     -0.023259
70              total_rev_hi_lim:30K-40K     -0.017043
71              total_rev_hi_lim:40K-55K      0.032698
72              total_rev_hi_lim:55K-95K      0.031528
73                    annual_inc:20K-30K     -0.156707
74                    annual_inc:30K-40K     -0.092721
75                    annual_inc:40K-50K      0.003725
76                    annual_inc:50K-60K      0.060133
77                    annual_inc:60K-70K      0.146672
78                    annual_inc:70K-80K      0.206741
79                    annual_inc:80K-90K      0.251517
80                   annual_inc:90K-100K      0.263293
81                  annual_inc:100K-120K      0.345081
82                  annual_inc:120K-140K      0.433301
83                      annual_inc:>140K      0.395978
84                             dti:<=1.4      0.056362
85                           dti:1.4-3.5      0.205738
86                           dti:3.5-7.7      0.185460
87                          dti:7.7-10.5      0.126893
88                         dti:10.5-16.1      0.083620
89                         dti:16.1-20.3     -0.017488
90                         dti:20.3-21.7     -0.028279
91                         dti:21.7-22.4     -0.084908
92                           dti:22.4-35     -0.111017
93        mths_since_last_delinq:Missing      0.070682
94           mths_since_last_delinq:4-30      0.119896
95          mths_since_last_delinq:31-56      0.116245
96           mths_since_last_delinq:>=57      0.105275
97           mths_since_last_record:3-20     -0.002696
98          mths_since_last_record:21-31      0.041011
99          mths_since_last_record:32-80      0.212705
100         mths_since_last_record:81-86     -0.106492
101           mths_since_last_record:>86     -0.064097

## **3. Build a Logistic Regression Model with P-Values**

**Zusammenfassung: Variablenselektion im PD-Modell mittels statistischer Signifikanz**

### **3.1 Herausforderung und Zielsetzung**  
Nach der erstmaligen Schätzung des logistischen Regressionsmodells (PD-Modell) bestand die nächste Aufgabe darin, diejenigen unabhängigen Variablen zu identifizieren und zu entfernen, die **keinen statistisch signifikanten Beitrag** zur Vorhersage der Kreditausfallwahrscheinlichkeit leisten. Das Ziel war ein **schlankes und robustes Finalmodell**, das nur die aussagekräftigsten Prädiktoren enthält.

In [ ]:
# P-Werte für die logistische Regression in sklearn.
# Klasse zur Anzeige der P-Werte für die logistische Regression in sklearn.

from sklearn import linear_model
import scipy.stats as stat

class LogisticRegression_with_p_values:

    def __init__(self,*args,**kwargs):#,**kwargs):
        self.model = linear_model.LogisticRegression(*args,**kwargs)#,**args)

    def fit(self,X,y):
        self.model.fit(X,y)

        #### Get p-values for the fitted model ####
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(X))))
        denom = np.tile(denom,(X.shape[1],1)).T
        F_ij = np.dot((X / denom).T,X) ## Fisher-Informationsmatrix Matrix
        Cramer_Rao = np.linalg.inv(F_ij) ## Inverse Informationsmatrix
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.model.coef_[0] / sigma_estimates # z-Wert für jeden Modellkoeffizienten
        p_values = [stat.norm.sf(abs(x)) * 2 for x in z_scores] ### zweiseitiger Test für p-Werte

        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        self.p_values = p_values

In [ ]:
bool_cols = inputs_train.select_dtypes(include=['bool']).columns
inputs_train[bool_cols] = inputs_train[bool_cols].astype(int)

In [ ]:
reg = LogisticRegression_with_p_values()
# Wir erstellen eine Instanz eines Objekts der neu erstellten Klasse 'LogisticRegression_with_p_values()'.

In [ ]:
reg.fit(inputs_train, loan_data_targets_train)
# Schätzt die Koeffizienten des Objekts der 'LogisticRegression'-Klasse
# mit Eingabewerten (unabhängige Variablen) aus dem ersten DataFrame
# und Zielwerten (abhängige Variablen) aus dem zweiten DataFrame.

In [ ]:
# Same as above.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                            Feature name  Coefficients
0                              Intercept     -0.228885
1                                grade:A      0.913792
2                                grade:B      0.681085
3                                grade:C      0.485257
4                                grade:D      0.318656
5                                grade:E      0.181767
6                                grade:F      0.053971
7                     home_ownership:OWN      0.083392
8                home_ownership:MORTGAGE      0.118492
9        addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.018838
10             addr_state:MD_TN_AZ_PA_MI      0.004957
11                      addr_state:DE_AR      0.027799
12      addr_state:UT_MN_OH_IN_GA_ RI_WA      0.074784
13                   addr_state:OR_KY_MA      0.077783
14                   addr_state:MT_MS_SD      0.144377
15                addr_state:WI_IL_CT_AK      0.207789
16                      addr_state:CO_SC      0.225165
17             addr_state:KS_NH_WV_VT_ID      0.283073
18                   addr_state:WY_DC_ME      0.626016
19      verification_status:Not Verified      0.088719
20   verification_status:Source Verified     -0.014449
21                   purpose:credit_card      0.289924
22            purpose:debt_consolidation      0.179567
23            purpose:oth__med__vacation      0.205068
24   purpose:major_purch__car__home_impr      0.242245
25                 initial_list_status:w      0.040191
26                               term:36      0.061115
27                          emp_length:1      0.120199
28                        emp_length:2-4      0.107810
29                        emp_length:5-6      0.066000
30                        emp_length:7-9      0.059842
31                         emp_length:10      0.118218
32                mths_since_issue_d:<38      0.917850
33              mths_since_issue_d:38-39      0.795201
34              mths_since_issue_d:40-41      0.711479
35              mths_since_issue_d:42-48      0.537977
36              mths_since_issue_d:49-52      0.423475
37              mths_since_issue_d:53-64      0.205588
38              mths_since_issue_d:65-84     -0.021898
39                       int_rate:<9.548      0.995983
40                 int_rate:9.548-12.025      0.646956
41                 int_rate:12.025-15.74      0.401384
42                 int_rate:15.74-20.281      0.172412
43   mths_since_earliest_cr_line:141-164      0.078674
44   mths_since_earliest_cr_line:165-247      0.064155
45   mths_since_earliest_cr_line:248-270      0.105136
46   mths_since_earliest_cr_line:271-352      0.143445
47      mths_since_earliest_cr_line:>352      0.157460
48                       delinq_2yrs:1-3     -0.067827
49                      delinq_2yrs:4-16     -0.122018
50                      delinq_2yrs:>=17     -0.021309
51                      inq_last_6mths:0      0.308714
52                    inq_last_6mths:1-2      0.171033
53                    inq_last_6mths:3-6     -0.019036
54                          open_acc:1-3      0.037665
55                         open_acc:4-12     -0.015628
56                        open_acc:13-17     -0.025362
57                        open_acc:18-22     -0.051960
58                        open_acc:23-25     -0.056212
59                        open_acc:26-30     -0.032364
60                         open_acc:>=31     -0.030473
61                           pub_rec:3-4     -0.006645
62                           pub_rec:>=5      0.078014
63                       total_acc:16-70     -0.049775
64                       total_acc:71-90     -0.090521
65                         total_acc:>90     -0.006627
66                    acc_now_delinq:>=1      0.184663
67               total_rev_hi_lim:5K-10K     -0.016648
68              total_rev_hi_lim:10K-20K     -0.023746
69              total_rev_hi_lim:20K-30K     -0.023259
70              total_rev_hi_lim:30K-40K     -0.017043
71              total_rev_hi_lim:40K-55K      0.032698
72              total_rev_hi_lim:55K-95K      0.031528
73                    annual_inc:20K-30K     -0.156707
74                    annual_inc:30K-40K     -0.092721
75                    annual_inc:40K-50K      0.003725
76                    annual_inc:50K-60K      0.060133
77                    annual_inc:60K-70K      0.146672
78                    annual_inc:70K-80K      0.206741
79                    annual_inc:80K-90K      0.251517
80                   annual_inc:90K-100K      0.263293
81                  annual_inc:100K-120K      0.345081
82                  annual_inc:120K-140K      0.433301
83                      annual_inc:>140K      0.395978
84                             dti:<=1.4      0.056362
85                           dti:1.4-3.5      0.205738
86                           dti:3.5-7.7      0.185460
87                          dti:7.7-10.5      0.126893
88                         dti:10.5-16.1      0.083620
89                         dti:16.1-20.3     -0.017488
90                         dti:20.3-21.7     -0.028279
91                         dti:21.7-22.4     -0.084908
92                           dti:22.4-35     -0.111017
93        mths_since_last_delinq:Missing      0.070682
94           mths_since_last_delinq:4-30      0.119896
95          mths_since_last_delinq:31-56      0.116245
96           mths_since_last_delinq:>=57      0.105275
97           mths_since_last_record:3-20     -0.002696
98          mths_since_last_record:21-31      0.041011
99          mths_since_last_record:32-80      0.212705
100         mths_since_last_record:81-86     -0.106492
101           mths_since_last_record:>86     -0.064097

### **3.2. Lösung: Berechnung multivariater p-Werte**  
Da die standardmäßigen p-Werte in `sklearn` univariat sind (d.h. Wechselwirkungen zwischen Variablen ignorieren) und somit für die Bewertung in einem multivariaten Regressionsmodell ungeeignet sind, wurde eine **maßgeschneiderte Lösung** implementiert:  
- Eine neue Klasse `LogisticRegression_with_p_values` wurde erstellt, die von der originalen `LogisticRegression`-Klasse erbt.  
- Diese Klasse überschreibt die `fit`-Methode und berechnet therein **multivariate p-Werte** mittels linearer Algebra.  
- Die p-Werte wurden in einer Instanzvariable `p_values` gespeichert und der Zusammenfassungstabelle der Koeffizienten hinzugefügt.

In [ ]:
# Dies ist eine Liste.
# Wir nehmen das Ergebnis der neu hinzugefügten Methode 'p_values' und speichern es in einer Variable 'p_values'
p_values = reg.p_values

In [ ]:
# Füge den Achsenabschnitt der Vollständigkeit halber hinzu.
# Wir fügen den Wert 'NaN' am Anfang der Variable mit den p-Werten hinzu.
p_values = np.append(np.nan, np.array(p_values))

In [ ]:
# Im Dataframe 'summary_table' fügen wir eine neue Spalte namens 'p_values' hinzu, die die Werte aus der Variable 'p_values' enthält.
summary_table['p_values'] = p_values

In [ ]:
summary_table

                            Feature name  Coefficients       p_values
0                              Intercept     -0.228885            NaN
1                                grade:A      0.913792   9.764635e-26
2                                grade:B      0.681085   1.055110e-29
3                                grade:C      0.485257   4.681420e-18
4                                grade:D      0.318656   2.329082e-09
5                                grade:E      0.181767   1.505809e-04
6                                grade:F      0.053971   2.804286e-01
7                     home_ownership:OWN      0.083392   1.475807e-05
8                home_ownership:MORTGAGE      0.118492   9.141517e-23
9        addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.018838   1.610312e-01
10             addr_state:MD_TN_AZ_PA_MI      0.004957   7.693688e-01
11                      addr_state:DE_AR      0.027799   5.858440e-01
12      addr_state:UT_MN_OH_IN_GA_ RI_WA      0.074784   7.639809e-06
13                   addr_state:OR_KY_MA      0.077783   2.786149e-03
14                   addr_state:MT_MS_SD      0.144377   2.256075e-02
15                addr_state:WI_IL_CT_AK      0.207789   1.346709e-20
16                      addr_state:CO_SC      0.225165   1.303821e-12
17             addr_state:KS_NH_WV_VT_ID      0.283073   1.724198e-12
18                   addr_state:WY_DC_ME      0.626016   1.813641e-12
19      verification_status:Not Verified      0.088719   3.555678e-10
20   verification_status:Source Verified     -0.014449   2.637854e-01
21                   purpose:credit_card      0.289924   2.243088e-25
22            purpose:debt_consolidation      0.179567   2.616276e-12
23            purpose:oth__med__vacation      0.205068   1.813541e-11
24   purpose:major_purch__car__home_impr      0.242245   2.389618e-15
25                 initial_list_status:w      0.040191   1.252312e-03
26                               term:36      0.061115   7.354397e-06
27                          emp_length:1      0.120199   1.889611e-06
28                        emp_length:2-4      0.107810   3.329432e-09
29                        emp_length:5-6      0.066000   1.401355e-03
30                        emp_length:7-9      0.059842   2.906289e-03
31                         emp_length:10      0.118218   3.109624e-11
32                mths_since_issue_d:<38      0.917850  1.930063e-145
33              mths_since_issue_d:38-39      0.795201  3.848563e-131
34              mths_since_issue_d:40-41      0.711479  8.369960e-110
35              mths_since_issue_d:42-48      0.537977   2.139216e-79
36              mths_since_issue_d:49-52      0.423475   1.374878e-43
37              mths_since_issue_d:53-64      0.205588   9.254249e-13
38              mths_since_issue_d:65-84     -0.021898   4.402203e-01
39                       int_rate:<9.548      0.995983   1.916366e-43
40                 int_rate:9.548-12.025      0.646956   1.547924e-50
41                 int_rate:12.025-15.74      0.401384   2.467785e-29
42                 int_rate:15.74-20.281      0.172412   9.485437e-10
43   mths_since_earliest_cr_line:141-164      0.078674   1.158681e-03
44   mths_since_earliest_cr_line:165-247      0.064155   1.266807e-03
45   mths_since_earliest_cr_line:248-270      0.105136   4.788086e-05
46   mths_since_earliest_cr_line:271-352      0.143445   5.944097e-10
47      mths_since_earliest_cr_line:>352      0.157460   1.726744e-09
48                       delinq_2yrs:1-3     -0.067827   8.345006e-03
49                      delinq_2yrs:4-16     -0.122018   2.238059e-02
50                      delinq_2yrs:>=17     -0.021309   9.808430e-01
51                      inq_last_6mths:0      0.308714   1.226429e-02
52                    inq_last_6mths:1-2      0.171033   1.648768e-01
53                    inq_last_6mths:3-6     -0.019036   8.776276e-01
54                          open_acc:1-3      0.037665   8.106020e-01
55                         open_acc:4-12     -0.015628   9.187849e-01
56                        open_acc:13-17     -0.025362   8.688643e-01
57                        open_acc:18-22     -0.051960   7.364181e-01
58                        open_acc:23-25     -0.056212   7.228167e-01
59                        open_acc:26-30     -0.032364   8.426635e-01
60                         open_acc:>=31     -0.030473   8.626096e-01
61                           pub_rec:3-4     -0.006645   9.374524e-01
62                           pub_rec:>=5      0.078014   6.486077e-01
63                       total_acc:16-70     -0.049775   9.705290e-04
64                       total_acc:71-90     -0.090521   6.232081e-01
65                         total_acc:>90     -0.006627   9.897393e-01
66                    acc_now_delinq:>=1      0.184663   5.901118e-02
67               total_rev_hi_lim:5K-10K     -0.016648   4.584763e-01
68              total_rev_hi_lim:10K-20K     -0.023746   2.625116e-01
69              total_rev_hi_lim:20K-30K     -0.023259   3.135906e-01
70              total_rev_hi_lim:30K-40K     -0.017043   5.107981e-01
71              total_rev_hi_lim:40K-55K      0.032698   2.492419e-01
72              total_rev_hi_lim:55K-95K      0.031528   3.199486e-01
73                    annual_inc:20K-30K     -0.156707   2.647619e-04
74                    annual_inc:30K-40K     -0.092721   2.556237e-02
75                    annual_inc:40K-50K      0.003725   9.286658e-01
76                    annual_inc:50K-60K      0.060133   1.534558e-01
77                    annual_inc:60K-70K      0.146672   6.627895e-04
78                    annual_inc:70K-80K      0.206741   2.426266e-06
79                    annual_inc:80K-90K      0.251517   3.100434e-08
80                   annual_inc:90K-100K      0.263293   1.768274e-08
81                  annual_inc:100K-120K      0.345081   1.151398e-13
82                  annual_inc:120K-140K      0.433301   8.810766e-17
83                      annual_inc:>140K      0.395978   3.189560e-16
84                             dti:<=1.4      0.056362   5.173923e-01
85                           dti:1.4-3.5      0.205738   5.097612e-03
86                           dti:3.5-7.7      0.185460   3.792866e-03
87                          dti:7.7-10.5      0.126893   4.567245e-02
88                         dti:10.5-16.1      0.083620   1.750893e-01
89                         dti:16.1-20.3     -0.017488   7.766114e-01
90                         dti:20.3-21.7     -0.028279   6.584201e-01
91                         dti:21.7-22.4     -0.084908   2.083319e-01
92                           dti:22.4-35     -0.111017   6.839841e-02
93        mths_since_last_delinq:Missing      0.070682   1.798564e-01
94           mths_since_last_delinq:4-30      0.119896   1.478261e-02
95          mths_since_last_delinq:31-56      0.116245   3.113683e-02
96           mths_since_last_delinq:>=57      0.105275   5.610349e-02
97           mths_since_last_record:3-20     -0.002696   9.745072e-01
98          mths_since_last_record:21-31      0.041011   5.851637e-01
99          mths_since_last_record:32-80      0.212705   3.830378e-17
100         mths_since_last_record:81-86     -0.106492   7.795191e-02
101           mths_since_last_record:>86     -0.064097   3.736118e-03

In [ ]:
# Vollständige Dezimaldarstellung (kann bei sehr kleinen Werten zu 0.0000 führen)
summary_table['p_values'] = summary_table['p_values'].apply(
    lambda x: f'{x:.6f}' if not pd.isna(x) else 'NaN'
)

# Anzeige der Tabelle
summary_table

                            Feature name  Coefficients  p_values
0                              Intercept     -0.228885       NaN
1                                grade:A      0.913792  0.000000
2                                grade:B      0.681085  0.000000
3                                grade:C      0.485257  0.000000
4                                grade:D      0.318656  0.000000
5                                grade:E      0.181767  0.000151
6                                grade:F      0.053971  0.280429
7                     home_ownership:OWN      0.083392  0.000015
8                home_ownership:MORTGAGE      0.118492  0.000000
9        addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.018838  0.161031
10             addr_state:MD_TN_AZ_PA_MI      0.004957  0.769369
11                      addr_state:DE_AR      0.027799  0.585844
12      addr_state:UT_MN_OH_IN_GA_ RI_WA      0.074784  0.000008
13                   addr_state:OR_KY_MA      0.077783  0.002786
14                   addr_state:MT_MS_SD      0.144377  0.022561
15                addr_state:WI_IL_CT_AK      0.207789  0.000000
16                      addr_state:CO_SC      0.225165  0.000000
17             addr_state:KS_NH_WV_VT_ID      0.283073  0.000000
18                   addr_state:WY_DC_ME      0.626016  0.000000
19      verification_status:Not Verified      0.088719  0.000000
20   verification_status:Source Verified     -0.014449  0.263785
21                   purpose:credit_card      0.289924  0.000000
22            purpose:debt_consolidation      0.179567  0.000000
23            purpose:oth__med__vacation      0.205068  0.000000
24   purpose:major_purch__car__home_impr      0.242245  0.000000
25                 initial_list_status:w      0.040191  0.001252
26                               term:36      0.061115  0.000007
27                          emp_length:1      0.120199  0.000002
28                        emp_length:2-4      0.107810  0.000000
29                        emp_length:5-6      0.066000  0.001401
30                        emp_length:7-9      0.059842  0.002906
31                         emp_length:10      0.118218  0.000000
32                mths_since_issue_d:<38      0.917850  0.000000
33              mths_since_issue_d:38-39      0.795201  0.000000
34              mths_since_issue_d:40-41      0.711479  0.000000
35              mths_since_issue_d:42-48      0.537977  0.000000
36              mths_since_issue_d:49-52      0.423475  0.000000
37              mths_since_issue_d:53-64      0.205588  0.000000
38              mths_since_issue_d:65-84     -0.021898  0.440220
39                       int_rate:<9.548      0.995983  0.000000
40                 int_rate:9.548-12.025      0.646956  0.000000
41                 int_rate:12.025-15.74      0.401384  0.000000
42                 int_rate:15.74-20.281      0.172412  0.000000
43   mths_since_earliest_cr_line:141-164      0.078674  0.001159
44   mths_since_earliest_cr_line:165-247      0.064155  0.001267
45   mths_since_earliest_cr_line:248-270      0.105136  0.000048
46   mths_since_earliest_cr_line:271-352      0.143445  0.000000
47      mths_since_earliest_cr_line:>352      0.157460  0.000000
48                       delinq_2yrs:1-3     -0.067827  0.008345
49                      delinq_2yrs:4-16     -0.122018  0.022381
50                      delinq_2yrs:>=17     -0.021309  0.980843
51                      inq_last_6mths:0      0.308714  0.012264
52                    inq_last_6mths:1-2      0.171033  0.164877
53                    inq_last_6mths:3-6     -0.019036  0.877628
54                          open_acc:1-3      0.037665  0.810602
55                         open_acc:4-12     -0.015628  0.918785
56                        open_acc:13-17     -0.025362  0.868864
57                        open_acc:18-22     -0.051960  0.736418
58                        open_acc:23-25     -0.056212  0.722817
59                        open_acc:26-30     -0.032364  0.842663
60                         open_acc:>=31     -0.030473  0.862610
61                           pub_rec:3-4     -0.006645  0.937452
62                           pub_rec:>=5      0.078014  0.648608
63                       total_acc:16-70     -0.049775  0.000971
64                       total_acc:71-90     -0.090521  0.623208
65                         total_acc:>90     -0.006627  0.989739
66                    acc_now_delinq:>=1      0.184663  0.059011
67               total_rev_hi_lim:5K-10K     -0.016648  0.458476
68              total_rev_hi_lim:10K-20K     -0.023746  0.262512
69              total_rev_hi_lim:20K-30K     -0.023259  0.313591
70              total_rev_hi_lim:30K-40K     -0.017043  0.510798
71              total_rev_hi_lim:40K-55K      0.032698  0.249242
72              total_rev_hi_lim:55K-95K      0.031528  0.319949
73                    annual_inc:20K-30K     -0.156707  0.000265
74                    annual_inc:30K-40K     -0.092721  0.025562
75                    annual_inc:40K-50K      0.003725  0.928666
76                    annual_inc:50K-60K      0.060133  0.153456
77                    annual_inc:60K-70K      0.146672  0.000663
78                    annual_inc:70K-80K      0.206741  0.000002
79                    annual_inc:80K-90K      0.251517  0.000000
80                   annual_inc:90K-100K      0.263293  0.000000
81                  annual_inc:100K-120K      0.345081  0.000000
82                  annual_inc:120K-140K      0.433301  0.000000
83                      annual_inc:>140K      0.395978  0.000000
84                             dti:<=1.4      0.056362  0.517392
85                           dti:1.4-3.5      0.205738  0.005098
86                           dti:3.5-7.7      0.185460  0.003793
87                          dti:7.7-10.5      0.126893  0.045672
88                         dti:10.5-16.1      0.083620  0.175089
89                         dti:16.1-20.3     -0.017488  0.776611
90                         dti:20.3-21.7     -0.028279  0.658420
91                         dti:21.7-22.4     -0.084908  0.208332
92                           dti:22.4-35     -0.111017  0.068398
93        mths_since_last_delinq:Missing      0.070682  0.179856
94           mths_since_last_delinq:4-30      0.119896  0.014783
95          mths_since_last_delinq:31-56      0.116245  0.031137
96           mths_since_last_delinq:>=57      0.105275  0.056103
97           mths_since_last_record:3-20     -0.002696  0.974507
98          mths_since_last_record:21-31      0.041011  0.585164
99          mths_since_last_record:32-80      0.212705  0.000000
100         mths_since_last_record:81-86     -0.106492  0.077952
101           mths_since_last_record:>86     -0.064097  0.003736

### **3.3 Entscheidungskriterium für die Variablenselektion**  
Grundlage für die Entscheidung, eine Variable zu behalten oder zu entfernen, war ihr **p-Wert** (Signifikanzniveau von 0.05). Die Herausforderung bestand darin, dass originale Variablen oft durch **mehrere Dummy-Variablen** repräsentiert werden. Es wurde folgende Regel angewandt:  
- **Alle Dummy-Variablen signifikant:** Behalte die gesamte Variable.  
- **Keine Dummy-Variable signifikant:** Entferne die gesamte Variable.  
- **Einige signifikant, einige nicht:** Aus inhaltlich-konzeptionellen Gründen wurde die **gesamte originale Variable beibehalten**, um eine vollständige Repräsentation aller Ausprägungen im Modell zu gewährleisten. Das Entfernen einzelner Dummies würde zu einer unvollständigen und schwer interpretierbaren Variable führen.

Interpretation der p-Werte
Zur Erinnerung: In der statistischen Analyse:

p-Werte < 0.05 werden generally als statistisch signifikant betrachtet

p-Werte < 0.01 werden als hoch signifikant betrachtet

p-Werte < 0.001 werden als sehr hoch signifikant betrachtet

In Ihrer Tabelle sehen wir, dass viele Variablen extrem signifikante p-Werte haben (z.B., grade:A mit 9.76e-26), was auf eine sehr starke statistische Signifikanz hinweist.

Einige Variablen wie grade:F (0.2804) und delinq_2yrs:>=17 (0.9808) sind nicht signifikant, da ihre p-Werte deutlich über 0.05 liegen.

### **3.4 Durchführung der Selektion und Ergebnis**  
Angewendet auf das initiale Modell führte die Analyse der p-Werte zu folgenden Entscheidungen:  

*Entfernte Variablengruppen (da nicht signifikant):*  
- `delinq_2yrs` (Zahl der Zahlungsrückstände in den letzten 2 Jahren)  
- `open_acc` (Anzahl offener Kreditlinien)  
- `pub_rec` (Anzahl negativer öffentlicher Einträge)  
- `revol_lim` (Kreditlimit für revolving credit)  
- `total_acc` (Gesamtzahl der Kreditkonten)

*Beibehaltene Variablengruppen (da ganz oder teilweise signifikant):*  
- `grade`, `home_ownership`, `addr_state`, `verification_status`, `purpose`, `initial_list_status`, `term`, `emp_length`, `mths_since_issue_d`, `int_rate`, `mths_since_earliest_cr_line`, `annual_inc`, `dti` sowie andere.

| Variable                            | Entscheidung          | Begründung                                                                         |
| ----------------------------------- | --------------------- | ---------------------------------------------------------------------------------- |
| **grade**                           | Behalten              | Einige Dummies hoch signifikant, andere nicht → gesamte Variable bleibt (Regel 3). |
| **home\_ownership**                 | Behalten              | Alle Dummies hoch signifikant.                                                     |
| **addr\_state**                     | Behalten              | Gemischte Signifikanz, daher gesamte Variable beibehalten (Regel 3).               |
| **verification\_status**            | Behalten              | „Not Verified“ signifikant, „Source Verified“ nicht → Variable bleibt (Regel 3).   |
| **purpose**                         | Behalten              | Alle Dummies hoch signifikant.                                                     |
| **initial\_list\_status**           | Behalten              | Dummy „w“ signifikant.                                                             |
| **term**                            | Behalten              | Dummy „36“ signifikant.                                                            |
| **emp\_length**                     | Behalten              | Alle Dummies signifikant.                                                          |
| **mths\_since\_issue\_d**           | Behalten              | Mehrheit signifikant, eine nicht → gesamte Variable bleibt.                        |
| **int\_rate**                       | Behalten              | Alle Dummies hoch signifikant.                                                     |
| **mths\_since\_earliest\_cr\_line** | Behalten              | Alle Dummies signifikant.                                                          |
| **delinq\_2yrs**                    | Behalten              | Einige signifikant, eine nicht → gesamte Variable bleibt.                          |
| **inq\_last\_6mths**                | Behalten              | Teilweise signifikant, daher gesamte Variable bleibt.                              |
| **open\_acc**                       | Entfernen             | Keine Dummy-Variable signifikant (alle p > 0.7).                                   |
| **pub\_rec**                        | Entfernen             | Keine Dummy-Variable signifikant (alle p > 0.6).                                   |
| **total\_acc**                      | Behalten              | Eine Dummy signifikant, andere nicht → gesamte Variable bleibt.                    |
| **acc\_now\_delinq**                | Entfernen (Grenzfall) | Keine Dummy-Variable signifikant (p ≈ 0.059) → nach Regel entfernen.               |
| **total\_rev\_hi\_lim**             | Entfernen             | Keine Dummy-Variable signifikant (alle p > 0.2).                                   |
| **annual\_inc**                     | Behalten              | Mehrere Dummies hoch signifikant, andere nicht → gesamte Variable bleibt.          |
| **dti**                             | Behalten              | Einige signifikant, andere nicht → gesamte Variable bleibt.                        |
| **mths\_since\_last\_delinq**       | Behalten              | Teilweise signifikant, daher gesamte Variable bleibt.                              |
| **mths\_since\_last\_record**       | Behalten              | Gemischte Signifikanz, daher gesamte Variable bleibt.                              |

1. open_acc
2. pu_rec,
3. acc_now_dellin
4. total_rev_hi_lim

In [ ]:
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',

'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',

'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:OK_LA_NC_NM_MO_VA_NJ',
'addr_state:MD_TN_AZ_PA_MI',
'addr_state:DE_AR',
'addr_state:UT_MN_OH_IN_GA_ RI_WA',
'addr_state:OR_KY_MA',
'addr_state:MT_MS_SD',
'addr_state:WI_IL_CT_AK',
'addr_state:CO_SC',
'addr_state:KS_NH_WV_VT_ID',
'addr_state:WY_DC_ME',

'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',

'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',

'initial_list_status:f',
'initial_list_status:w',

'term:36',
'term:60',

'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',

'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',

'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',

'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',


'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:4-16',
'delinq_2yrs:>=17',


'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',


#'open_acc:0',
#'open_acc:1-3',
#'open_acc:4-12',
#'open_acc:13-17',
#'open_acc:18-22',
#'open_acc:23-25',
#'open_acc:26-30',
#'open_acc:>=31',

#'pub_rec:0-2',
#'pub_rec:3-4',
#'pub_rec:>=5',

'total_acc:0-15',
'total_acc:16-70',
'total_acc:71-90',
'total_acc:>90',

#'acc_now_delinq:0',
#'acc_now_delinq:>=1',

# 'total_rev_hi_lim:<=5K',
# 'total_rev_hi_lim:5K-10K',
# 'total_rev_hi_lim:10K-20K',
# 'total_rev_hi_lim:20K-30K',
# 'total_rev_hi_lim:30K-40K',
# 'total_rev_hi_lim:40K-55K',
# 'total_rev_hi_lim:55K-95K',


'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',

'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',


'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',

'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',

]]

In [ ]:
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:0',
'inq_last_6mths:>6',
#'open_acc:0',
#'pub_rec:0-2',
'total_acc:0-15',
#'acc_now_delinq:0',
#'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [ ]:
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
bool_cols = inputs_train.select_dtypes(include=['bool']).columns
inputs_train[bool_cols] = inputs_train[bool_cols].astype(int)

inputs_train.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:OK_LA_NC_NM_MO_VA_NJ,addr_state:MD_TN_AZ_PA_MI,...,dti:22.4-35,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
427211,0,0,0,1,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
206088,0,0,0,1,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
136020,0,1,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
412305,0,1,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
36159,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

### **3.5 Das finale Modell**  
- Das **finale Modell** wurde mit dem reduzierten Satz an Variablen neu trainiert.  
- Es umfasst **84 Dummy-Variablen**, die **17 originale unabhängige Variablen** repräsentieren.  
- Dieses Modell ist statistisch robuster, leichter interpretierbar und vermeidet Overfitting, da es nur die Variablen enthält, die einen gesicherten Beitrag zur Vorhersageleistung liefern.

In [ ]:
# Hier lassen wir ein neues Modell laufen.
reg2 = LogisticRegression_with_p_values()
reg2.fit(inputs_train, loan_data_targets_train)

In [ ]:
feature_name = inputs_train.columns.values

In [ ]:
# Same as above.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg2.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg2.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                           Feature name  Coefficients
0                             Intercept     -0.233534
1                               grade:A      0.922083
2                               grade:B      0.685872
3                               grade:C      0.488966
4                               grade:D      0.324109
5                               grade:E      0.189386
6                               grade:F      0.056816
7                    home_ownership:OWN      0.083058
8               home_ownership:MORTGAGE      0.116799
9       addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.017217
10            addr_state:MD_TN_AZ_PA_MI      0.007682
11                     addr_state:DE_AR      0.027290
12     addr_state:UT_MN_OH_IN_GA_ RI_WA      0.077894
13                  addr_state:OR_KY_MA      0.080659
14                  addr_state:MT_MS_SD      0.145519
15               addr_state:WI_IL_CT_AK      0.210400
16                     addr_state:CO_SC      0.239710
17            addr_state:KS_NH_WV_VT_ID      0.301183
18                  addr_state:WY_DC_ME      0.632358
19     verification_status:Not Verified      0.089282
20  verification_status:Source Verified     -0.014011
21                  purpose:credit_card      0.289341
22           purpose:debt_consolidation      0.179817
23           purpose:oth__med__vacation      0.210564
24  purpose:major_purch__car__home_impr      0.245352
25                initial_list_status:w      0.039322
26                              term:36      0.054479
27                         emp_length:1      0.117944
28                       emp_length:2-4      0.105776
29                       emp_length:5-6      0.064778
30                       emp_length:7-9      0.058536
31                        emp_length:10      0.118364
32               mths_since_issue_d:<38      0.930421
33             mths_since_issue_d:38-39      0.804655
34             mths_since_issue_d:40-41      0.723854
35             mths_since_issue_d:42-48      0.547772
36             mths_since_issue_d:49-52      0.434164
37             mths_since_issue_d:53-64      0.217185
38             mths_since_issue_d:65-84     -0.016931
39                      int_rate:<9.548      1.003119
40                int_rate:9.548-12.025      0.657169
41                int_rate:12.025-15.74      0.409855
42                int_rate:15.74-20.281      0.178900
43  mths_since_earliest_cr_line:141-164      0.079188
44  mths_since_earliest_cr_line:165-247      0.067263
45  mths_since_earliest_cr_line:248-270      0.108817
46  mths_since_earliest_cr_line:271-352      0.147488
47     mths_since_earliest_cr_line:>352      0.164264
48                      delinq_2yrs:1-3     -0.067749
49                     delinq_2yrs:4-16     -0.117282
50                     delinq_2yrs:>=17     -0.022076
51                     inq_last_6mths:0      0.307956
52                   inq_last_6mths:1-2      0.168522
53                   inq_last_6mths:3-6     -0.015544
54                      total_acc:16-70     -0.059204
55                      total_acc:71-90     -0.097449
56                        total_acc:>90     -0.008503
57                   annual_inc:20K-30K     -0.157414
58                   annual_inc:30K-40K     -0.094222
59                   annual_inc:40K-50K      0.000772
60                   annual_inc:50K-60K      0.058271
61                   annual_inc:60K-70K      0.144472
62                   annual_inc:70K-80K      0.207411
63                   annual_inc:80K-90K      0.252833
64                  annual_inc:90K-100K      0.264443
65                 annual_inc:100K-120K      0.346498
66                 annual_inc:120K-140K      0.460002
67                     annual_inc:>140K      0.404458
68                            dti:<=1.4      0.072443
69                          dti:1.4-3.5      0.214882
70                          dti:3.5-7.7      0.179443
71                         dti:7.7-10.5      0.120595
72                        dti:10.5-16.1      0.077134
73                        dti:16.1-20.3     -0.024415
74                        dti:20.3-21.7     -0.032009
75                        dti:21.7-22.4     -0.088171
76                          dti:22.4-35     -0.116832
77       mths_since_last_delinq:Missing      0.036970
78          mths_since_last_delinq:4-30      0.083589
79         mths_since_last_delinq:31-56      0.080119
80          mths_since_last_delinq:>=57      0.068261
81          mths_since_last_record:3-20     -0.004191
82         mths_since_last_record:21-31      0.036250
83         mths_since_last_record:32-80      0.214814
84         mths_since_last_record:81-86     -0.116621
85           mths_since_last_record:>86     -0.063665

In [ ]:
# Wir fügen hier die 'p_values' hinzu, genau wie zuvor.
# Hier erhalten wir die Ergebnisse für unser endgültiges PD-Modell.
p_values = reg2.p_values
p_values = np.append(np.nan,np.array(p_values))
summary_table['p_values'] = p_values
summary_table

                           Feature name  Coefficients       p_values
0                             Intercept     -0.233534            NaN
1                               grade:A      0.922083   2.245612e-26
2                               grade:B      0.685872   1.957918e-30
3                               grade:C      0.488966   1.392443e-18
4                               grade:D      0.324109   8.033190e-10
5                               grade:E      0.189386   5.465670e-05
6                               grade:F      0.056816   2.443885e-01
7                    home_ownership:OWN      0.083058   1.569663e-05
8               home_ownership:MORTGAGE      0.116799   3.374111e-22
9       addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.017217   1.999357e-01
10            addr_state:MD_TN_AZ_PA_MI      0.007682   6.493755e-01
11                     addr_state:DE_AR      0.027290   5.923922e-01
12     addr_state:UT_MN_OH_IN_GA_ RI_WA      0.077894   3.112915e-06
13                  addr_state:OR_KY_MA      0.080659   1.931274e-03
14                  addr_state:MT_MS_SD      0.145519   2.143695e-02
15               addr_state:WI_IL_CT_AK      0.210400   4.287881e-21
16                     addr_state:CO_SC      0.239710   5.420092e-14
17            addr_state:KS_NH_WV_VT_ID      0.301183   8.223204e-14
18                  addr_state:WY_DC_ME      0.632358   1.182069e-12
19     verification_status:Not Verified      0.089282   2.274448e-10
20  verification_status:Source Verified     -0.014011   2.775933e-01
21                  purpose:credit_card      0.289341   1.302769e-25
22           purpose:debt_consolidation      0.179817   1.695458e-12
23           purpose:oth__med__vacation      0.210564   4.061479e-12
24  purpose:major_purch__car__home_impr      0.245352   7.531693e-16
25                initial_list_status:w      0.039322   1.595419e-03
26                              term:36      0.054479   5.380339e-05
27                         emp_length:1      0.117944   2.867887e-06
28                       emp_length:2-4      0.105776   6.253709e-09
29                       emp_length:5-6      0.064778   1.708009e-03
30                       emp_length:7-9      0.058536   3.575858e-03
31                        emp_length:10      0.118364   2.895124e-11
32               mths_since_issue_d:<38      0.930421  2.526333e-154
33             mths_since_issue_d:38-39      0.804655  1.378712e-139
34             mths_since_issue_d:40-41      0.723854  3.077844e-118
35             mths_since_issue_d:42-48      0.547772   3.875426e-86
36             mths_since_issue_d:49-52      0.434164   1.166377e-47
37             mths_since_issue_d:53-64      0.217185   1.172805e-14
38             mths_since_issue_d:65-84     -0.016931   5.491879e-01
39                      int_rate:<9.548      1.003119   3.089236e-44
40                int_rate:9.548-12.025      0.657169   1.944217e-52
41                int_rate:12.025-15.74      0.409855   9.462213e-31
42                int_rate:15.74-20.281      0.178900   1.893634e-10
43  mths_since_earliest_cr_line:141-164      0.079188   1.038757e-03
44  mths_since_earliest_cr_line:165-247      0.067263   6.609394e-04
45  mths_since_earliest_cr_line:248-270      0.108817   2.273730e-05
46  mths_since_earliest_cr_line:271-352      0.147488   1.280826e-10
47     mths_since_earliest_cr_line:>352      0.164264   2.311885e-10
48                      delinq_2yrs:1-3     -0.067749   7.972865e-03
49                     delinq_2yrs:4-16     -0.117282   2.789643e-02
50                     delinq_2yrs:>=17     -0.022076   9.802203e-01
51                     inq_last_6mths:0      0.307956   1.677544e-04
52                   inq_last_6mths:1-2      0.168522   3.942092e-02
53                   inq_last_6mths:3-6     -0.015544   8.506607e-01
54                      total_acc:16-70     -0.059204   3.762604e-05
55                      total_acc:71-90     -0.097449   5.921002e-01
56                        total_acc:>90     -0.008503   9.868621e-01
57                   annual_inc:20K-30K     -0.157414   1.712048e-04
58                   annual_inc:30K-40K     -0.094222   1.957081e-02
59                   annual_inc:40K-50K      0.000772   9.847441e-01
60                   annual_inc:50K-60K      0.058271   1.541646e-01
61                   annual_inc:60K-70K      0.144472   5.497814e-04
62                   annual_inc:70K-80K      0.207411   1.102991e-06
63                   annual_inc:80K-90K      0.252833   1.019617e-08
64                  annual_inc:90K-100K      0.264443   6.042344e-09
65                 annual_inc:100K-120K      0.346498   1.720664e-14
66                 annual_inc:120K-140K      0.460002   2.092225e-19
67                     annual_inc:>140K      0.404458   9.371960e-18
68                            dti:<=1.4      0.072443   3.810562e-01
69                          dti:1.4-3.5      0.214882   1.873272e-03
70                          dti:3.5-7.7      0.179443   2.543906e-03
71                         dti:7.7-10.5      0.120595   4.106753e-02
72                        dti:10.5-16.1      0.077134   1.771262e-01
73                        dti:16.1-20.3     -0.024415   6.694018e-01
74                        dti:20.3-21.7     -0.032009   5.922806e-01
75                        dti:21.7-22.4     -0.088171   1.653127e-01
76                          dti:22.4-35     -0.116832   3.880905e-02
77       mths_since_last_delinq:Missing      0.036970   4.214176e-01
78          mths_since_last_delinq:4-30      0.083589   4.654768e-02
79         mths_since_last_delinq:31-56      0.080119   9.136716e-02
80          mths_since_last_delinq:>=57      0.068261   1.617825e-01
81          mths_since_last_record:3-20     -0.004191   9.595843e-01
82         mths_since_last_record:21-31      0.036250   6.249282e-01
83         mths_since_last_record:32-80      0.214814   2.890085e-18
84         mths_since_last_record:81-86     -0.116621   5.291031e-02
85           mths_since_last_record:>86     -0.063665   3.869272e-03

In [ ]:
import pickle
# pickle.dump(reg2, open('pd_model.sav', 'wb'))
# Here we export our model to a 'SAV' file with file name 'pd_model.sav'.

## 4.Test