<a href="https://colab.research.google.com/github/awildt01/Credit-Scoring/blob/main/notebooks/4_applying_the_PD_Model_for_decision_makingi_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scorecards
In der Praxis übertragen Banken Modelle häufig in sogenannte Scorecards. Diese dienen der strukturierten Aufbereitung der Ergebnisse und fördern die Nachvollziehbarkeit insbesondere für nicht-technische Anspruchsgruppen. Im weiteren Verlauf wird die Umwandlung des Modells in eine Scorecard sowie die darauf basierende Berechnung von Kreditpunkten systematisch erläutert.

## 1.Grundidee – Logistische Regression im Kreditmodell

Wir haben ein Kreditrisikomodell mit einer logistischen Regression.  
Das Modell sagt uns: Wie hoch ist die Wahrscheinlichkeit, dass jemand den Kredit zurückzahlt („gut") oder ausfällt („schlecht")?

**Formel:**

$$
P(\text{gut}) = \frac{1}{1 + e^{-(\beta_0 + \beta_1x_1 + \beta_2x_2 + \cdots + \beta_nx_n)}}
$$

Alternativ kann sie auch so dargestellt werden:
$$
P(\text{gut}) = \frac{e^{(\beta_0 + \beta_1x_1 + \beta_2x_2 + \cdots + \beta_nx_n)}}{1 + e^{(\beta_0 + \beta_1x_1 + \beta_2x_2 + \cdots + \beta_nx_n)}}
$$



Das klingt kompliziert – aber es ist eigentlich nur:  
**Intercept** + **Summe der passenden Dummy-Koeffizienten** → in die Formel einsetzen → **Wahrscheinlichkeit** ausrechnen.

## 2.Schritt-für-Schritt mit einem Mini-Beispiel

Stell dir vor, wir haben ein sehr einfaches Modell mit nur 3 Variablen:

*   **Intercept (Basiswert) $\beta_0$**: -1
*   **Kreditrating C $\beta_1$**: +0.7
*   **Hausbesitz Hypothek $\beta_2$**: +0.1
*   **Bundesstaat Kalifornien $\beta_3$**: +0.06

Jetzt haben wir einen Kreditnehmer mit diesen Eigenschaften:

*   Kreditrating = C  ($x_1 = 1$)
*   Hausbesitz = Hypothek  ($x_2 = 1$)
*   Bundesstaat = Kalifornien  ($x_3 = 1$)



### Schritt 1: Koeffizienten summieren (Lineare Kombination)

$$
\beta_0 + \beta_1x_1 + \beta_2x_2 + \beta_3x_3 = -1 + (0.7 \times 1) + (0.1 \times 1) + (0.06 \times 1) = -0.14
$$

Dieser Wert $(-0.14)$ ist der sogenannte **Logit-Wert** (oder Log-Odds).



### Schritt 2: In die Formel einsetzen

**Exponent berechnen (Odds):**
$$
\text{Odds} = e^{-0.14} \approx 0.87
$$

**Wahrscheinlichkeit berechnen:**
$$
P(\text{gut}) = \frac{0.87}{1 + 0.87} \approx 0.465
$$

Das Modell sagt: **46,5 % Wahrscheinlichkeit**, dass dieser Kreditnehmer den Kredit zurückzahlt.

## 3.Warum so viele Summen?

Weil jede Dummy-Variable nur 0 oder 1 ist:

*   Wenn die Eigenschaft **zutrifft** → der entsprechende Koeffizient $\beta_i$ wird addiert.
*   Wenn **nicht** → der Term $\beta_i \times 0$ fällt weg.

**Beispiel:**  
Kreditrating B hat vielleicht den Koeffizienten **+0.3**.  
Wenn jemand **nicht** B ist → Dummy $= 0$ → wir addieren nichts.

## 4.Was passiert in der Praxis?

Banken rechnen das nicht jedes Mal manuell, sondern verwandeln das Modell in **Scorecards**:

*   Jede Eigenschaft (z. B. Kreditrating, Hausstatus, Einkommen) bekommt Punkte.
*   Die Punkte werden addiert.
*   Am Ende ergibt sich ein Score (z. B. 650 Punkte).

Ab einem bestimmten Score sagt die Bank: **„Kredit genehmigt"** oder **„abgelehnt"**.

Das ist einfacher als Wahrscheinlichkeiten, weil Punkte leichter zu vergleichen sind.


**Kurz gesagt:**

1.  Wir addieren die passenden Koeffizienten zum **Logit-Wert**.
2.  Rechnen den Exponenten → das sind die **Odds**.
3.  Machen daraus eine **Wahrscheinlichkeit**.
4.  In der Praxis wird das Ganze in eine **Scorecard** umgewandelt.

In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
import os

#from google.colab import data_table
#data_table.enable_dataframe_formatter()

from google.colab import data_table
data_table.disable_dataframe_formatter()

# unbegrenzte Zeilen und Spalten anzeigen
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

# **Creating a Scorecard**

**1.Erstellen des DataFrame mit Referenzkategorien (df_ref_categories)**


Für die spätere Scorecard-Erstellung wollen wir jede Dummy-Kategorie der im Modell verwendeten Variablen im Scorecard-Tableau abbilden — auch jene Kategorien, die beim Modelltraining als Referenz weggelassen wurden. Da Referenzkategorien beim Fitten keine Koeffizienten haben, fügen wir sie jetzt manuell mit Koeffizient = 0 (und p_value = NaN) ein. So ergibt sich später ein vollständiges, konsistentes Layout mit allen Kategorien pro Original-Feature.

Nach der Schätzung unseres finalen Logit-Modells (Probability of Default Modell) haben wir die Ergebnisse in einer **summary_table** gespeichert.
Diese Tabelle enthält:



- **Feature name**: den Namen der Variable oder Kategorie, die im Modell berücksichtigt wird.

- **Coefficients:** den geschätzten Regressionskoeffizienten (Einfluss auf die Ausfallwahrscheinlichkeit).

     - Positive Werte → senken die Ausfallwahrscheinlichkeit (günstigeres Kreditrisiko).

     - Negative Werte → erhöhen die Ausfallwahrscheinlichkeit (höheres Kreditrisiko).

- **p_values:** Signifikanzwerte, die anzeigen, ob der geschätzte Effekt statistisch relevant ist.

Da für jede kategoriale Variable eine Referenzkategorie festgelegt wird (Baseline), erscheint diese nicht in der **summary_table**.
Beispielsweise wird bei der Variable Grade die Kategorie grade:G als Referenz genutzt – daher finden sich nur die Kategorien grade:A bis grade:F in der Tabelle.



Um auch die Referenzkategorien in unserer finalen Scorecard darzustellen, haben wir die Liste **ref_categories** definiert.
Mit dieser Liste haben wir ein separates DataFrame df_ref_categories erstellt, in dem:

- **Coefficients = 0** (da die Referenz als Vergleichswert dient),

- **p_values = NaN** (nicht berechnet, da Referenz).



Anschließend können wir die **summary_table und df_ref_categories zusammenführen**, sodass eine vollständige Übersicht entsteht, in der alle Kategorien (inkl. Referenzen) enthalten sind.
Diese vollständige Tabelle bildet die Grundlage für die spätere Scorecard-Erstellung.

In [ ]:
# Und hier in der folgenden Liste behalten wir die Variablennamen für die Referenzkategorien bei,
# nur für die Variablen, die wir in unserem endgültigen PD-Modell verwendet haben.
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:0',
'inq_last_6mths:>6',
#'open_acc:0',
#'pub_rec:0-2',
'total_acc:0-15',
#'acc_now_delinq:0',
#'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [ ]:
# Google Drive mounten
drive.mount('/content/drive')

# Zielordner definieren
folder_path = '/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks'
os.makedirs(folder_path, exist_ok=True)  # Ordner erstellen, falls nicht vorhanden

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
summary_table = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/summary_table.csv', index_col = 0,header=0)

In [ ]:
summary_table

                           Feature name  Coefficients       p_values
0                             Intercept     -0.233534            NaN
1                               grade:A      0.922083   2.245612e-26
2                               grade:B      0.685872   1.957918e-30
3                               grade:C      0.488966   1.392443e-18
4                               grade:D      0.324109   8.033190e-10
5                               grade:E      0.189386   5.465670e-05
6                               grade:F      0.056816   2.443885e-01
7                    home_ownership:OWN      0.083058   1.569663e-05
8               home_ownership:MORTGAGE      0.116799   3.374111e-22
9       addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.017217   1.999357e-01
10            addr_state:MD_TN_AZ_PA_MI      0.007682   6.493755e-01
11                     addr_state:DE_AR      0.027290   5.923922e-01
12     addr_state:UT_MN_OH_IN_GA_ RI_WA      0.077894   3.112915e-06
13                  addr_state:OR_KY_MA      0.080659   1.931274e-03
14                  addr_state:MT_MS_SD      0.145519   2.143695e-02
15               addr_state:WI_IL_CT_AK      0.210400   4.287881e-21
16                     addr_state:CO_SC      0.239710   5.420092e-14
17            addr_state:KS_NH_WV_VT_ID      0.301183   8.223204e-14
18                  addr_state:WY_DC_ME      0.632358   1.182069e-12
19     verification_status:Not Verified      0.089282   2.274448e-10
20  verification_status:Source Verified     -0.014011   2.775933e-01
21                  purpose:credit_card      0.289341   1.302769e-25
22           purpose:debt_consolidation      0.179817   1.695458e-12
23           purpose:oth__med__vacation      0.210564   4.061479e-12
24  purpose:major_purch__car__home_impr      0.245352   7.531693e-16
25                initial_list_status:w      0.039322   1.595419e-03
26                              term:36      0.054479   5.380339e-05
27                         emp_length:1      0.117944   2.867887e-06
28                       emp_length:2-4      0.105776   6.253709e-09
29                       emp_length:5-6      0.064778   1.708009e-03
30                       emp_length:7-9      0.058536   3.575858e-03
31                        emp_length:10      0.118364   2.895124e-11
32               mths_since_issue_d:<38      0.930421  2.526333e-154
33             mths_since_issue_d:38-39      0.804655  1.378712e-139
34             mths_since_issue_d:40-41      0.723854  3.077844e-118
35             mths_since_issue_d:42-48      0.547772   3.875426e-86
36             mths_since_issue_d:49-52      0.434164   1.166377e-47
37             mths_since_issue_d:53-64      0.217185   1.172805e-14
38             mths_since_issue_d:65-84     -0.016931   5.491879e-01
39                      int_rate:<9.548      1.003119   3.089236e-44
40                int_rate:9.548-12.025      0.657169   1.944217e-52
41                int_rate:12.025-15.74      0.409855   9.462213e-31
42                int_rate:15.74-20.281      0.178900   1.893634e-10
43  mths_since_earliest_cr_line:141-164      0.079188   1.038757e-03
44  mths_since_earliest_cr_line:165-247      0.067263   6.609394e-04
45  mths_since_earliest_cr_line:248-270      0.108817   2.273730e-05
46  mths_since_earliest_cr_line:271-352      0.147488   1.280826e-10
47     mths_since_earliest_cr_line:>352      0.164264   2.311885e-10
48                      delinq_2yrs:1-3     -0.067749   7.972865e-03
49                     delinq_2yrs:4-16     -0.117282   2.789643e-02
50                     delinq_2yrs:>=17     -0.022076   9.802203e-01
51                     inq_last_6mths:0      0.307956   1.677544e-04
52                   inq_last_6mths:1-2      0.168522   3.942092e-02
53                   inq_last_6mths:3-6     -0.015544   8.506607e-01
54                      total_acc:16-70     -0.059204   3.762604e-05
55                      total_acc:71-90     -0.097449   5.921002e-01
56                        total_acc:>90     -0.008503   9.868621e-01
57                   annual_inc:20K-30K     -0.157414   1.712048e-04
58                   annual_inc:30K-40K     -0.094222   1.957081e-02
59                   annual_inc:40K-50K      0.000772   9.847441e-01
60                   annual_inc:50K-60K      0.058271   1.541646e-01
61                   annual_inc:60K-70K      0.144472   5.497814e-04
62                   annual_inc:70K-80K      0.207411   1.102991e-06
63                   annual_inc:80K-90K      0.252833   1.019617e-08
64                  annual_inc:90K-100K      0.264443   6.042344e-09
65                 annual_inc:100K-120K      0.346498   1.720664e-14
66                 annual_inc:120K-140K      0.460002   2.092225e-19
67                     annual_inc:>140K      0.404458   9.371960e-18
68                            dti:<=1.4      0.072443   3.810562e-01
69                          dti:1.4-3.5      0.214882   1.873272e-03
70                          dti:3.5-7.7      0.179443   2.543906e-03
71                         dti:7.7-10.5      0.120595   4.106753e-02
72                        dti:10.5-16.1      0.077134   1.771262e-01
73                        dti:16.1-20.3     -0.024415   6.694018e-01
74                        dti:20.3-21.7     -0.032009   5.922806e-01
75                        dti:21.7-22.4     -0.088171   1.653127e-01
76                          dti:22.4-35     -0.116832   3.880905e-02
77       mths_since_last_delinq:Missing      0.036970   4.214176e-01
78          mths_since_last_delinq:4-30      0.083589   4.654768e-02
79         mths_since_last_delinq:31-56      0.080119   9.136716e-02
80          mths_since_last_delinq:>=57      0.068261   1.617825e-01
81          mths_since_last_record:3-20     -0.004191   9.595843e-01
82         mths_since_last_record:21-31      0.036250   6.249282e-01
83         mths_since_last_record:32-80      0.214814   2.890085e-18
84         mths_since_last_record:81-86     -0.116621   5.291031e-02
85           mths_since_last_record:>86     -0.063665   3.869272e-03

In [ ]:
# Vollständige Dezimaldarstellung (kann bei sehr kleinen Werten zu 0.0000 führen)
summary_table['p_values'] = summary_table['p_values'].apply(
    lambda x: f'{x:.6f}' if not pd.isna(x) else 'NaN'
)
# Anzeige der Tabelle
summary_table

                           Feature name  Coefficients  p_values
0                             Intercept     -0.233534       NaN
1                               grade:A      0.922083  0.000000
2                               grade:B      0.685872  0.000000
3                               grade:C      0.488966  0.000000
4                               grade:D      0.324109  0.000000
5                               grade:E      0.189386  0.000055
6                               grade:F      0.056816  0.244388
7                    home_ownership:OWN      0.083058  0.000016
8               home_ownership:MORTGAGE      0.116799  0.000000
9       addr_state:OK_LA_NC_NM_MO_VA_NJ     -0.017217  0.199936
10            addr_state:MD_TN_AZ_PA_MI      0.007682  0.649376
11                     addr_state:DE_AR      0.027290  0.592392
12     addr_state:UT_MN_OH_IN_GA_ RI_WA      0.077894  0.000003
13                  addr_state:OR_KY_MA      0.080659  0.001931
14                  addr_state:MT_MS_SD      0.145519  0.021437
15               addr_state:WI_IL_CT_AK      0.210400  0.000000
16                     addr_state:CO_SC      0.239710  0.000000
17            addr_state:KS_NH_WV_VT_ID      0.301183  0.000000
18                  addr_state:WY_DC_ME      0.632358  0.000000
19     verification_status:Not Verified      0.089282  0.000000
20  verification_status:Source Verified     -0.014011  0.277593
21                  purpose:credit_card      0.289341  0.000000
22           purpose:debt_consolidation      0.179817  0.000000
23           purpose:oth__med__vacation      0.210564  0.000000
24  purpose:major_purch__car__home_impr      0.245352  0.000000
25                initial_list_status:w      0.039322  0.001595
26                              term:36      0.054479  0.000054
27                         emp_length:1      0.117944  0.000003
28                       emp_length:2-4      0.105776  0.000000
29                       emp_length:5-6      0.064778  0.001708
30                       emp_length:7-9      0.058536  0.003576
31                        emp_length:10      0.118364  0.000000
32               mths_since_issue_d:<38      0.930421  0.000000
33             mths_since_issue_d:38-39      0.804655  0.000000
34             mths_since_issue_d:40-41      0.723854  0.000000
35             mths_since_issue_d:42-48      0.547772  0.000000
36             mths_since_issue_d:49-52      0.434164  0.000000
37             mths_since_issue_d:53-64      0.217185  0.000000
38             mths_since_issue_d:65-84     -0.016931  0.549188
39                      int_rate:<9.548      1.003119  0.000000
40                int_rate:9.548-12.025      0.657169  0.000000
41                int_rate:12.025-15.74      0.409855  0.000000
42                int_rate:15.74-20.281      0.178900  0.000000
43  mths_since_earliest_cr_line:141-164      0.079188  0.001039
44  mths_since_earliest_cr_line:165-247      0.067263  0.000661
45  mths_since_earliest_cr_line:248-270      0.108817  0.000023
46  mths_since_earliest_cr_line:271-352      0.147488  0.000000
47     mths_since_earliest_cr_line:>352      0.164264  0.000000
48                      delinq_2yrs:1-3     -0.067749  0.007973
49                     delinq_2yrs:4-16     -0.117282  0.027896
50                     delinq_2yrs:>=17     -0.022076  0.980220
51                     inq_last_6mths:0      0.307956  0.000168
52                   inq_last_6mths:1-2      0.168522  0.039421
53                   inq_last_6mths:3-6     -0.015544  0.850661
54                      total_acc:16-70     -0.059204  0.000038
55                      total_acc:71-90     -0.097449  0.592100
56                        total_acc:>90     -0.008503  0.986862
57                   annual_inc:20K-30K     -0.157414  0.000171
58                   annual_inc:30K-40K     -0.094222  0.019571
59                   annual_inc:40K-50K      0.000772  0.984744
60                   annual_inc:50K-60K      0.058271  0.154165
61                   annual_inc:60K-70K      0.144472  0.000550
62                   annual_inc:70K-80K      0.207411  0.000001
63                   annual_inc:80K-90K      0.252833  0.000000
64                  annual_inc:90K-100K      0.264443  0.000000
65                 annual_inc:100K-120K      0.346498  0.000000
66                 annual_inc:120K-140K      0.460002  0.000000
67                     annual_inc:>140K      0.404458  0.000000
68                            dti:<=1.4      0.072443  0.381056
69                          dti:1.4-3.5      0.214882  0.001873
70                          dti:3.5-7.7      0.179443  0.002544
71                         dti:7.7-10.5      0.120595  0.041068
72                        dti:10.5-16.1      0.077134  0.177126
73                        dti:16.1-20.3     -0.024415  0.669402
74                        dti:20.3-21.7     -0.032009  0.592281
75                        dti:21.7-22.4     -0.088171  0.165313
76                          dti:22.4-35     -0.116832  0.038809
77       mths_since_last_delinq:Missing      0.036970  0.421418
78          mths_since_last_delinq:4-30      0.083589  0.046548
79         mths_since_last_delinq:31-56      0.080119  0.091367
80          mths_since_last_delinq:>=57      0.068261  0.161782
81          mths_since_last_record:3-20     -0.004191  0.959584
82         mths_since_last_record:21-31      0.036250  0.624928
83         mths_since_last_record:32-80      0.214814  0.000000
84         mths_since_last_record:81-86     -0.116621  0.052910
85           mths_since_last_record:>86     -0.063665  0.003869

In [ ]:
df_ref_categories = pd.DataFrame(ref_categories, columns = ['Feature name'])
# Wir erstellen einen neuen Datenrahmen mit einer Spalte. Seine Werte sind die Werte aus der Liste „reference_categories“.
# Wir nennen ihn „Featurename“.
df_ref_categories['Coefficients'] = 0
# Fügt eine Spalte Coefficients hinzu und füllt sie mit 0. Warum 0?
# Weil beim Modelltraining keine Koeffizienten für Referenzen geschätzt wurden
# — ihre impliziten Koeffizienten sind 0 (die Referenz ist die Vergleichsbasis).
df_ref_categories['p_values'] = np.nan
# → Fügt eine Spalte p_values mit NaN ein, weil für diese (künstlich hinzugefügten) Zeilen keine statistischen Tests bzw. p-Werte berechnet wurden.
df_ref_categories

                                    Feature name  Coefficients  p_values
0                                        grade:G             0       NaN
1             home_ownership:RENT_OTHER_NONE_ANY             0       NaN
2                addr_state:ND_NE_IA_NV_FL_HI_AL             0       NaN
3                   verification_status:Verified             0       NaN
4   purpose:educ__sm_b__wedd__ren_en__mov__house             0       NaN
5                          initial_list_status:f             0       NaN
6                                        term:60             0       NaN
7                                   emp_length:0             0       NaN
8                         mths_since_issue_d:>84             0       NaN
9                               int_rate:>20.281             0       NaN
10              mths_since_earliest_cr_line:<140             0       NaN
11                                 delinq_2yrs:0             0       NaN
12                             inq_last_6mths:>6             0       NaN
13                                total_acc:0-15             0       NaN
14                               annual_inc:<20K             0       NaN
15                                       dti:>35             0       NaN
16                    mths_since_last_delinq:0-3             0       NaN
17                    mths_since_last_record:0-2             0       NaN

In [ ]:
df_scorecard = pd.concat([summary_table, df_ref_categories])
# Concatenates zwei dataframes.
df_scorecard = df_scorecard.reset_index()
# We reset the index of a dataframe.
df_scorecard

,index,Feature name,Coefficients,p_values
0,0,Intercept,-0.233534,NaN
1,1,grade:A,0.922083,0.000000
2,2,grade:B,0.685872,0.000000
3,3,grade:C,0.488966,0.000000
4,4,grade:D,0.324109,0.000000
5,5,grade:E,0.189386,0.000055
6,6,grade:F,0.056816,0.244388
7,7,home_ownership:OWN,0.083058,0.000016
8,8,home_ownership:MORTGAGE,0.116799,0.000000
9,9,addr_state:OK_LA_NC_NM_MO_VA_NJ,-0.017217,0.199936
10,10,addr_state:MD_TN_AZ_PA_MI,0.007682,0.649376
11,11,addr_state:DE_AR,0.027290,0.592392
12,12,addr_state:UT_MN_OH_IN_GA_ RI_WA,0.077894,0.000003
13,13,addr_state:OR_KY_MA,0.080659,0.001931
14,14,addr_state:MT_MS_SD,0.145519,0.021437
15,15,addr_state:WI_IL_CT_AK,0.210400,0.000000
16,16,addr_state:CO_SC,0.239710,0.000000
17,17,addr_state:KS_NH_WV_VT_ID,0.301183,0.000000
18,18,addr_state:WY_DC_ME,0.632358,0.000000
19,19,verification_status:Not Verified,0.089282,0.000000
20,20,verification_status:Source Verified,-0.014011,0.277593
21,21,purpose:credit_card,0.289341,0.000000
22,22,purpose:debt_consolidation,0.179817,0.000000
23,23,purpose:oth__med__vacation,0.210564,0.000000
24,24,purpose:major_purch__car__home_impr,0.245352,0.000000
25,25,initial_list_status:w,0.039322,0.001595
26,26,term:36,0.054479,0.000054
27,27,emp_length:1,0.117944,0.000003
28,28,emp_length:2-4,0.105776,0.000000
29,29,emp_length:5-6,0.064778,0.001708
30,30,emp_length:7-9,0.058536,0.003576
31,31,emp_length:10,0.118364,0.000000
32,32,mths_since_issue_d:<38,0.930421,0.000000
33,33,mths_since_issue_d:38-39,0.804655,0.000000
34,34,mths_since_issue_d:40-41,0.723854,0.000000
35,35,mths_since_issue_d:42-48,0.547772,0.000000
36,36,mths_since_issue_d:49-52,0.434164,0.000000
37,37,mths_since_issue_d:53-64,0.217185,0.000000
38,38,mths_since_issue_d:65-84,-0.016931,0.549188
39,39,int_rate:<9.548,1.003119,0.000000
40,40,int_rate:9.548-12.025,0.657169,0.000000
41,41,int_rate:12.025-15.74,0.409855,0.000000
42,42,int_rate:15.74-20.281,0.178900,0.000000
43,43,mths_since_earliest_cr_line:141-164,0.079188,0.001039
44,44,mths_since_earliest_cr_line:165-247,0.067263,0.000661
45,45,mths_since_earliest_cr_line:248-270,0.108817,0.000023
46,46,mths_since_earliest_cr_line:271-352,0.147488,0.000000
47,47,mths_since_earliest_cr_line:>352,0.164264,0.000000
48,48,delinq_2yrs:1-3,-0.067749,0.007973
49,49,delinq_2yrs:4-16,-0.117282,0.027896
50,50,delinq_2yrs:>=17,-0.022076,0.980220
51,51,inq_last_6mths:0,0.307956,0.000168
52,52,inq_last_6mths:1-2,0.168522,0.039421
53,53,inq_last_6mths:3-6,-0.015544,0.850661
54,54,total_acc:16-70,-0.059204,0.000038
55,55,total_acc:71-90,-0.097449,0.592100
56,56,total_acc:>90,-0.008503,0.986862
57,57,annual_inc:20K-30K,-0.157414,0.000171
58,58,annual_inc:30K-40K,-0.094222,0.019571
59,59,annual_inc:40K-50K,0.000772,0.984744
60,60,annual_inc:50K-60K,0.058271,0.154165
61,61,annual_inc:60K-70K,0.144472,0.000550
62,62,annual_inc:70K-80K,0.207411,0.000001
63,63,annual_inc:80K-90K,0.252833,0.000000
64,64,annual_inc:90K-100K,0.264443,0.000000
65,65,annual_inc:100K-120K,0.346498,0.000000
66,66,annual_inc:120K-140K,0.460002,0.000000
67,67,annual_inc:>140K,0.404458,0.000000
68,68,dti:<=1.4,0.072443,0.381056
69,69,dti:1.4-3.5,0.214882,0.001873
70,70,dti:3.5-7.7,0.179443,0.002544
71,71,dti:7.7-10.5,0.120595,0.041068
72,72,dti:10.5-16.1,0.077134,0.177126
73,73,dti:16.1-20.3,-0.024415,0.669402
74,74,dti:20.3-21.7,-0.032009,0.592281
75,75,dti:21.7-22.4,-0.088171,0.165313
76,76,dti:22.4-35,-0.116832,0.038809
77,77,mths_since_last_delinq:Missing,0.036970,0.421418
78,78,mths_since_last_delinq:4-30,0.083589,0.046548
79,79,mths_since_last_delinq:31-56,0.080119,0.091367
80,80,mths_since_last_delinq:>=57,0.068261,0.161782
81,81,mths_since_last_record:3-20,-0.004191,0.959584
82,82,mths_since_last_record:21-31,0.036250,0.624928
83,83,mths_since_last_record:32-80,0.214814,0.000000
84,84,mths_since_last_record:81-86,-0.116621,0.052910
85,85,mths_since_last_record:>86,-0.063665,0.003869
86,0,grade:G,0.000000,NaN
87,1,home_ownership:RENT_OTHER_NONE_ANY,0.000000,NaN
88,2,addr_state:ND_NE_IA_NV_FL_HI_AL,0.000000,NaN
89,3,verification_status:Verified,0.000000,NaN
90,4,purpose:educ__sm_b__wedd__ren_en__mov__house,0.000000,NaN
91,5,initial_list_status:f,0.000000,NaN
92,6,term:60,0.000000,NaN
93,7,emp_length:0,0.000000,NaN
94,8,mths_since_issue_d:>84,0.000000,NaN
95,9,int_rate:>20.281,0.000000,NaN
96,10,mths_since_earliest_cr_line:<140,0.000000,NaN
97,11,delinq_2yrs:0,0.000000,NaN
98,12,inq_last_6mths:>6,0.000000,NaN
99,13,total_acc:0-15,0.000000,NaN
100,14,annual_inc:<20K,0.000000,NaN
101,15,dti:>35,0.000000,NaN
102,16,mths_since_last_delinq:0-3,0.000000,NaN
103,17,mths_since_last_record:0-2,0.000000,NaN

In [ ]:
df_scorecard['Original feature name'] = df_scorecard['Feature name'].str.split(':').str[0]
# Wir erstellen eine neue Spalte mit dem Namen „Original Feature name“,
# die den Wert der Spalte „Feature name“ bis zum Spaltensymbol enthält.

In [ ]:
df_scorecard

,index,Feature name,Coefficients,p_values,Original feature name
0,0,Intercept,-0.233534,NaN,Intercept
1,1,grade:A,0.922083,0.000000,grade
2,2,grade:B,0.685872,0.000000,grade
3,3,grade:C,0.488966,0.000000,grade
4,4,grade:D,0.324109,0.000000,grade
5,5,grade:E,0.189386,0.000055,grade
6,6,grade:F,0.056816,0.244388,grade
7,7,home_ownership:OWN,0.083058,0.000016,home_ownership
8,8,home_ownership:MORTGAGE,0.116799,0.000000,home_ownership
9,9,addr_state:OK_LA_NC_NM_MO_VA_NJ,-0.017217,0.199936,addr_state
10,10,addr_state:MD_TN_AZ_PA_MI,0.007682,0.649376,addr_state
11,11,addr_state:DE_AR,0.027290,0.592392,addr_state
12,12,addr_state:UT_MN_OH_IN_GA_ RI_WA,0.077894,0.000003,addr_state
13,13,addr_state:OR_KY_MA,0.080659,0.001931,addr_state
14,14,addr_state:MT_MS_SD,0.145519,0.021437,addr_state
15,15,addr_state:WI_IL_CT_AK,0.210400,0.000000,addr_state
16,16,addr_state:CO_SC,0.239710,0.000000,addr_state
17,17,addr_state:KS_NH_WV_VT_ID,0.301183,0.000000,addr_state
18,18,addr_state:WY_DC_ME,0.632358,0.000000,addr_state
19,19,verification_status:Not Verified,0.089282,0.000000,verification_status
20,20,verification_status:Source Verified,-0.014011,0.277593,verification_status
21,21,purpose:credit_card,0.289341,0.000000,purpose
22,22,purpose:debt_consolidation,0.179817,0.000000,purpose
23,23,purpose:oth__med__vacation,0.210564,0.000000,purpose
24,24,purpose:major_purch__car__home_impr,0.245352,0.000000,purpose
25,25,initial_list_status:w,0.039322,0.001595,initial_list_status
26,26,term:36,0.054479,0.000054,term
27,27,emp_length:1,0.117944,0.000003,emp_length
28,28,emp_length:2-4,0.105776,0.000000,emp_length
29,29,emp_length:5-6,0.064778,0.001708,emp_length
30,30,emp_length:7-9,0.058536,0.003576,emp_length
31,31,emp_length:10,0.118364,0.000000,emp_length
32,32,mths_since_issue_d:<38,0.930421,0.000000,mths_since_issue_d
33,33,mths_since_issue_d:38-39,0.804655,0.000000,mths_since_issue_d
34,34,mths_since_issue_d:40-41,0.723854,0.000000,mths_since_issue_d
35,35,mths_since_issue_d:42-48,0.547772,0.000000,mths_since_issue_d
36,36,mths_since_issue_d:49-52,0.434164,0.000000,mths_since_issue_d
37,37,mths_since_issue_d:53-64,0.217185,0.000000,mths_since_issue_d
38,38,mths_since_issue_d:65-84,-0.016931,0.549188,mths_since_issue_d
39,39,int_rate:<9.548,1.003119,0.000000,int_rate
40,40,int_rate:9.548-12.025,0.657169,0.000000,int_rate
41,41,int_rate:12.025-15.74,0.409855,0.000000,int_rate
42,42,int_rate:15.74-20.281,0.178900,0.000000,int_rate
43,43,mths_since_earliest_cr_line:141-164,0.079188,0.001039,mths_since_earliest_cr_line
44,44,mths_since_earliest_cr_line:165-247,0.067263,0.000661,mths_since_earliest_cr_line
45,45,mths_since_earliest_cr_line:248-270,0.108817,0.000023,mths_since_earliest_cr_line
46,46,mths_since_earliest_cr_line:271-352,0.147488,0.000000,mths_since_earliest_cr_line
47,47,mths_since_earliest_cr_line:>352,0.164264,0.000000,mths_since_earliest_cr_line
48,48,delinq_2yrs:1-3,-0.067749,0.007973,delinq_2yrs
49,49,delinq_2yrs:4-16,-0.117282,0.027896,delinq_2yrs
50,50,delinq_2yrs:>=17,-0.022076,0.980220,delinq_2yrs
51,51,inq_last_6mths:0,0.307956,0.000168,inq_last_6mths
52,52,inq_last_6mths:1-2,0.168522,0.039421,inq_last_6mths
53,53,inq_last_6mths:3-6,-0.015544,0.850661,inq_last_6mths
54,54,total_acc:16-70,-0.059204,0.000038,total_acc
55,55,total_acc:71-90,-0.097449,0.592100,total_acc
56,56,total_acc:>90,-0.008503,0.986862,total_acc
57,57,annual_inc:20K-30K,-0.157414,0.000171,annual_inc
58,58,annual_inc:30K-40K,-0.094222,0.019571,annual_inc
59,59,annual_inc:40K-50K,0.000772,0.984744,annual_inc
60,60,annual_inc:50K-60K,0.058271,0.154165,annual_inc
61,61,annual_inc:60K-70K,0.144472,0.000550,annual_inc
62,62,annual_inc:70K-80K,0.207411,0.000001,annual_inc
63,63,annual_inc:80K-90K,0.252833,0.000000,annual_inc
64,64,annual_inc:90K-100K,0.264443,0.000000,annual_inc
65,65,annual_inc:100K-120K,0.346498,0.000000,annual_inc
66,66,annual_inc:120K-140K,0.460002,0.000000,annual_inc
67,67,annual_inc:>140K,0.404458,0.000000,annual_inc
68,68,dti:<=1.4,0.072443,0.381056,dti
69,69,dti:1.4-3.5,0.214882,0.001873,dti
70,70,dti:3.5-7.7,0.179443,0.002544,dti
71,71,dti:7.7-10.5,0.120595,0.041068,dti
72,72,dti:10.5-16.1,0.077134,0.177126,dti
73,73,dti:16.1-20.3,-0.024415,0.669402,dti
74,74,dti:20.3-21.7,-0.032009,0.592281,dti
75,75,dti:21.7-22.4,-0.088171,0.165313,dti
76,76,dti:22.4-35,-0.116832,0.038809,dti
77,77,mths_since_last_delinq:Missing,0.036970,0.421418,mths_since_last_delinq
78,78,mths_since_last_delinq:4-30,0.083589,0.046548,mths_since_last_delinq
79,79,mths_since_last_delinq:31-56,0.080119,0.091367,mths_since_last_delinq
80,80,mths_since_last_delinq:>=57,0.068261,0.161782,mths_since_last_delinq
81,81,mths_since_last_record:3-20,-0.004191,0.959584,mths_since_last_record
82,82,mths_since_last_record:21-31,0.036250,0.624928,mths_since_last_record
83,83,mths_since_last_record:32-80,0.214814,0.000000,mths_since_last_record
84,84,mths_since_last_record:81-86,-0.116621,0.052910,mths_since_last_record
85,85,mths_since_last_record:>86,-0.063665,0.003869,mths_since_last_record
86,0,grade:G,0.000000,NaN,grade
87,1,home_ownership:RENT_OTHER_NONE_ANY,0.000000,NaN,home_ownership
88,2,addr_state:ND_NE_IA_NV_FL_HI_AL,0.000000,NaN,addr_state
89,3,verification_status:Verified,0.000000,NaN,verification_status
90,4,purpose:educ__sm_b__wedd__ren_en__mov__house,0.000000,NaN,purpose
91,5,initial_list_status:f,0.000000,NaN,initial_list_status
92,6,term:60,0.000000,NaN,term
93,7,emp_length:0,0.000000,NaN,emp_length
94,8,mths_since_issue_d:>84,0.000000,NaN,mths_since_issue_d
95,9,int_rate:>20.281,0.000000,NaN,int_rate
96,10,mths_since_earliest_cr_line:<140,0.000000,NaN,mths_since_earliest_cr_line
97,11,delinq_2yrs:0,0.000000,NaN,delinq_2yrs
98,12,inq_last_6mths:>6,0.000000,NaN,inq_last_6mths
99,13,total_acc:0-15,0.000000,NaN,total_acc
100,14,annual_inc:<20K,0.000000,NaN,annual_inc
101,15,dti:>35,0.000000,NaN,dti
102,16,mths_since_last_delinq:0-3,0.000000,NaN,mths_since_last_delinq
103,17,mths_since_last_record:0-2,0.000000,NaN,mths_since_last_record

## **1.Score**
- Wenn wir für jede Variable die schlechteste Ausprägung nehmen und diese summieren, erhalten wir das niedrigste mögliche Modell-Logit-Ergebnis.

- Dieses Ergebnis wird später auf die Score-Skala (z. B. 300–850) transformiert.

- So stellen wir sicher, dass die Kombination „schlechteste Kategorie bei allen Variablen“ tatsächlich den Minimalwert der Skala (hier 300) ergibt.

- Mit .max() bestimmen wir die beste Ausprägung pro Variable.

- Wenn wir diese summieren, erhalten wir den theoretisch höchsten Score, der dann auf 850 gemappt wird.

In [ ]:
min_score = 300
max_score = 850

In [ ]:
df_scorecard.groupby('Original feature name')['Coefficients'].min()
# Gruppiert die Daten nach den Werten der Spalte „Ursprünglicher Merkmalsname“.
# Aggregiert die Daten in der Spalte „Koeffizienten“ und berechnet deren Minimum.

Original feature name
Intercept                     -0.233534
addr_state                    -0.017217
annual_inc                    -0.157414
delinq_2yrs                   -0.117282
dti                           -0.116832
emp_length                     0.000000
grade                          0.000000
home_ownership                 0.000000
initial_list_status            0.000000
inq_last_6mths                -0.015544
int_rate                       0.000000
mths_since_earliest_cr_line    0.000000
mths_since_issue_d            -0.016931
mths_since_last_delinq         0.000000
mths_since_last_record        -0.116621
purpose                        0.000000
term                           0.000000
total_acc                     -0.097449
verification_status           -0.014011
Name: Coefficients, dtype: float64

In [ ]:
min_sum_coef = df_scorecard.groupby('Original feature name')['Coefficients'].min().sum()
# Bis zur Methode „min()“ ist alles wie in der obigen Zeile.
# Anschließend aggregieren wir weiter und summieren alle Minimalwerte.
min_sum_coef

np.float64(-0.9028357194654884)

In [ ]:
df_scorecard.groupby('Original feature name')['Coefficients'].max()
# Gruppiert die Daten nach den Werten der Spalte „Ursprünglicher Merkmalsname“.
# Aggregiert die Daten in der Spalte „Koeffizienten“ und berechnet deren Maximum.

Original feature name
Intercept                     -0.233534
addr_state                     0.632358
annual_inc                     0.460002
delinq_2yrs                    0.000000
dti                            0.214882
emp_length                     0.118364
grade                          0.922083
home_ownership                 0.116799
initial_list_status            0.039322
inq_last_6mths                 0.307956
int_rate                       1.003119
mths_since_earliest_cr_line    0.164264
mths_since_issue_d             0.930421
mths_since_last_delinq         0.083589
mths_since_last_record         0.214814
purpose                        0.289341
term                           0.054479
total_acc                      0.000000
verification_status            0.089282
Name: Coefficients, dtype: float64

In [ ]:
max_sum_coef = df_scorecard.groupby('Original feature name')['Coefficients'].max().sum()
# Bis zur Methode „min()“ ist alles wie in der Zeile oben.
# Anschließend aggregieren wir weiter und summieren alle Maximalwerte.
max_sum_coef

np.float64(5.407542809776595)

## **2.Lineare Transformation der Koeffizienten**

Damit die Modellkoeffizienten in einen Scorebereich (z. B. 300–850 Punkte) übersetzt werden können, wendet man eine lineare Transformation an.

Bedeutung der einzelnen Teile **Text fett markieren**

- df_scorecard['Coefficients']
→ Das sind die β-Werte aus dem logistischen Modell.
Beispiel: Für "grade:A" = 0.92.

- (max_score - min_score)
→ Das ist der Zielbereich der Scorecard.
Beispiel: 850 – 300 = 550 Punkte.

- (max_sum_coef - min_sum_coef)
→ Das ist der Spannungsbereich der Modellkoeffizienten.

- max_sum_coef: maximale mögliche Summe der β-Werte (wenn eine Person in allen "besten Kategorien" ist).

- min_sum_coef: minimale mögliche Summe der β-Werte (wenn eine Person in allen "schlechtesten Kategorien" ist).

Damit haben wir die „Spanne“ der Logit-Skala.

**Multiplikation:**

→ Wir skalieren die einzelnen β-Werte so, dass sie in das gewünschte Punktesystem passen.

**Interpretierbarkeit:**

- Statt mit Logits zu hantieren, bekommt man eine verständliche Punkteskala (wie bei Schufa oder FICO).

- Vergleichbarkeit: Jeder Koeffizient trägt eine bestimmte Anzahl an Punkten zum Gesamtscore bei.

**Praxisnutzen: Kreditgeber können sagen:**

- "Ein Score von 700 bedeutet mittleres Risiko."

- "Ein Kunde mit 850 ist super, einer mit 300 sehr riskant."

## 3.Lineare Skalierung (ohne Verschiebung)
-  Wir skalieren die Roh-Koeffizienten proportional auf den Punktbereich (300–850).
- Ergebnis: Jede Ausprägung einer Variable bekommt Punkte zugewiesen.

Beispiel:

  - Einkommen hoch → +80 Punkte
 - Schulden hoch → –50 Punkte
 - Damit können wir die Einflüsse der Variablen interpretieren.

In [ ]:
# Wir skalieren die Roh-Koeffizienten proportional auf den Punktbereich (300–850).
# Ergebnis: Jede Ausprägung einer Variable bekommt Punkte zugewiesen.
# Beispiel:
# Einkommen hoch → +80 Punkte
# Schulden hoch → –50 Punkte
# Damit können wir die Einflüsse der Variablen interpretieren.
df_scorecard['Score - Calculation'] = df_scorecard['Coefficients'] * (max_score - min_score) / (max_sum_coef - min_sum_coef)
# Wir multiplizieren den Wert der Spalte „Koeffizienten“ mit dem Verhältnis der Differenzen zwischen
# Maximalpunktzahl und Minimalpunktzahl sowie der maximalen Summe der Koeffizienten und der minimalen Summe der Koeffizienten.
df_scorecard

,index,Feature name,Coefficients,p_values,Original feature name,Score - Calculation
0,0,Intercept,-0.233534,NaN,Intercept,-20.354359
1,1,grade:A,0.922083,0.000000,grade,80.366875
2,2,grade:B,0.685872,0.000000,grade,59.779210
3,3,grade:C,0.488966,0.000000,grade,42.617335
4,4,grade:D,0.324109,0.000000,grade,28.248711
5,5,grade:E,0.189386,0.000055,grade,16.506545
6,6,grade:F,0.056816,0.244388,grade,4.951947
7,7,home_ownership:OWN,0.083058,0.000016,home_ownership,7.239135
8,8,home_ownership:MORTGAGE,0.116799,0.000000,home_ownership,10.179993
9,9,addr_state:OK_LA_NC_NM_MO_VA_NJ,-0.017217,0.199936,addr_state,-1.500634
10,10,addr_state:MD_TN_AZ_PA_MI,0.007682,0.649376,addr_state,0.669513
11,11,addr_state:DE_AR,0.027290,0.592392,addr_state,2.378525
12,12,addr_state:UT_MN_OH_IN_GA_ RI_WA,0.077894,0.000003,addr_state,6.789061
13,13,addr_state:OR_KY_MA,0.080659,0.001931,addr_state,7.030067
14,14,addr_state:MT_MS_SD,0.145519,0.021437,addr_state,12.683139
15,15,addr_state:WI_IL_CT_AK,0.210400,0.000000,addr_state,18.338020
16,16,addr_state:CO_SC,0.239710,0.000000,addr_state,20.892688
17,17,addr_state:KS_NH_WV_VT_ID,0.301183,0.000000,addr_state,26.250547
18,18,addr_state:WY_DC_ME,0.632358,0.000000,addr_state,55.115072
19,19,verification_status:Not Verified,0.089282,0.000000,verification_status,7.781637
20,20,verification_status:Source Verified,-0.014011,0.277593,verification_status,-1.221209
21,21,purpose:credit_card,0.289341,0.000000,purpose,25.218423
22,22,purpose:debt_consolidation,0.179817,0.000000,purpose,15.672523
23,23,purpose:oth__med__vacation,0.210564,0.000000,purpose,18.352361
24,24,purpose:major_purch__car__home_impr,0.245352,0.000000,purpose,21.384404
25,25,initial_list_status:w,0.039322,0.001595,initial_list_status,3.427269
26,26,term:36,0.054479,0.000054,term,4.748297
27,27,emp_length:1,0.117944,0.000003,emp_length,10.279777
28,28,emp_length:2-4,0.105776,0.000000,emp_length,9.219256
29,29,emp_length:5-6,0.064778,0.001708,emp_length,5.645946
30,30,emp_length:7-9,0.058536,0.003576,emp_length,5.101868
31,31,emp_length:10,0.118364,0.000000,emp_length,10.316357
32,32,mths_since_issue_d:<38,0.930421,0.000000,mths_since_issue_d,81.093615
33,33,mths_since_issue_d:38-39,0.804655,0.000000,mths_since_issue_d,70.132117
34,34,mths_since_issue_d:40-41,0.723854,0.000000,mths_since_issue_d,63.089665
35,35,mths_since_issue_d:42-48,0.547772,0.000000,mths_since_issue_d,47.742755
36,36,mths_since_issue_d:49-52,0.434164,0.000000,mths_since_issue_d,37.840911
37,37,mths_since_issue_d:53-64,0.217185,0.000000,mths_since_issue_d,18.929413
38,38,mths_since_issue_d:65-84,-0.016931,0.549188,mths_since_issue_d,-1.475703
39,39,int_rate:<9.548,1.003119,0.000000,int_rate,87.429822
40,40,int_rate:9.548-12.025,0.657169,0.000000,int_rate,57.277545
41,41,int_rate:12.025-15.74,0.409855,0.000000,int_rate,35.722168
42,42,int_rate:15.74-20.281,0.178900,0.000000,int_rate,15.592543
43,43,mths_since_earliest_cr_line:141-164,0.079188,0.001039,mths_since_earliest_cr_line,6.901896
44,44,mths_since_earliest_cr_line:165-247,0.067263,0.000661,mths_since_earliest_cr_line,5.862471
45,45,mths_since_earliest_cr_line:248-270,0.108817,0.000023,mths_since_earliest_cr_line,9.484231
46,46,mths_since_earliest_cr_line:271-352,0.147488,0.000000,mths_since_earliest_cr_line,12.854764
47,47,mths_since_earliest_cr_line:>352,0.164264,0.000000,mths_since_earliest_cr_line,14.316958
48,48,delinq_2yrs:1-3,-0.067749,0.007973,delinq_2yrs,-5.904898
49,49,delinq_2yrs:4-16,-0.117282,0.027896,delinq_2yrs,-10.222072
50,50,delinq_2yrs:>=17,-0.022076,0.980220,delinq_2yrs,-1.924079
51,51,inq_last_6mths:0,0.307956,0.000168,inq_last_6mths,26.840851
52,52,inq_last_6mths:1-2,0.168522,0.039421,inq_last_6mths,14.688020
53,53,inq_last_6mths:3-6,-0.015544,0.850661,inq_last_6mths,-1.354784
54,54,total_acc:16-70,-0.059204,0.000038,total_acc,-5.160102
55,55,total_acc:71-90,-0.097449,0.592100,total_acc,-8.493439
56,56,total_acc:>90,-0.008503,0.986862,total_acc,-0.741136
57,57,annual_inc:20K-30K,-0.157414,0.000171,annual_inc,-13.719849
58,58,annual_inc:30K-40K,-0.094222,0.019571,annual_inc,-8.212177
59,59,annual_inc:40K-50K,0.000772,0.984744,annual_inc,0.067314
60,60,annual_inc:50K-60K,0.058271,0.154165,annual_inc,5.078769
61,61,annual_inc:60K-70K,0.144472,0.000550,annual_inc,12.591923
62,62,annual_inc:70K-80K,0.207411,0.000001,annual_inc,18.077486
63,63,annual_inc:80K-90K,0.252833,0.000000,annual_inc,22.036443
64,64,annual_inc:90K-100K,0.264443,0.000000,annual_inc,23.048320
65,65,annual_inc:100K-120K,0.346498,0.000000,annual_inc,30.200084
66,66,annual_inc:120K-140K,0.460002,0.000000,annual_inc,40.092879
67,67,annual_inc:>140K,0.404458,0.000000,annual_inc,35.251778
68,68,dti:<=1.4,0.072443,0.381056,dti,6.314013
69,69,dti:1.4-3.5,0.214882,0.001873,dti,18.728701
70,70,dti:3.5-7.7,0.179443,0.002544,dti,15.639904
71,71,dti:7.7-10.5,0.120595,0.041068,dti,10.510841
72,72,dti:10.5-16.1,0.077134,0.177126,dti,6.722826
73,73,dti:16.1-20.3,-0.024415,0.669402,dti,-2.127951
74,74,dti:20.3-21.7,-0.032009,0.592281,dti,-2.789884
75,75,dti:21.7-22.4,-0.088171,0.165313,dti,-7.684775
76,76,dti:22.4-35,-0.116832,0.038809,dti,-10.182884
77,77,mths_since_last_delinq:Missing,0.036970,0.421418,mths_since_last_delinq,3.222262
78,78,mths_since_last_delinq:4-30,0.083589,0.046548,mths_since_last_delinq,7.285463
79,79,mths_since_last_delinq:31-56,0.080119,0.091367,mths_since_last_delinq,6.983008
80,80,mths_since_last_delinq:>=57,0.068261,0.161782,mths_since_last_delinq,5.949468
81,81,mths_since_last_record:3-20,-0.004191,0.959584,mths_since_last_record,-0.365283
82,82,mths_since_last_record:21-31,0.036250,0.624928,mths_since_last_record,3.159450
83,83,mths_since_last_record:32-80,0.214814,0.000000,mths_since_last_record,18.722788
84,84,mths_since_last_record:81-86,-0.116621,0.052910,mths_since_last_record,-10.164427
85,85,mths_since_last_record:>86,-0.063665,0.003869,mths_since_last_record,-5.548943
86,0,grade:G,0.000000,NaN,grade,0.000000
87,1,home_ownership:RENT_OTHER_NONE_ANY,0.000000,NaN,home_ownership,0.000000
88,2,addr_state:ND_NE_IA_NV_FL_HI_AL,0.000000,NaN,addr_state,0.000000
89,3,verification_status:Verified,0.000000,NaN,verification_status,0.000000
90,4,purpose:educ__sm_b__wedd__ren_en__mov__house,0.000000,NaN,purpose,0.000000
91,5,initial_list_status:f,0.000000,NaN,initial_list_status,0.000000
92,6,term:60,0.000000,NaN,term,0.000000
93,7,emp_length:0,0.000000,NaN,emp_length,0.000000
94,8,mths_since_issue_d:>84,0.000000,NaN,mths_since_issue_d,0.000000
95,9,int_rate:>20.281,0.000000,NaN,int_rate,0.000000
96,10,mths_since_earliest_cr_line:<140,0.000000,NaN,mths_since_earliest_cr_line,0.000000
97,11,delinq_2yrs:0,0.000000,NaN,delinq_2yrs,0.000000
98,12,inq_last_6mths:>6,0.000000,NaN,inq_last_6mths,0.000000
99,13,total_acc:0-15,0.000000,NaN,total_acc,0.000000
100,14,annual_inc:<20K,0.000000,NaN,annual_inc,0.000000
101,15,dti:>35,0.000000,NaN,dti,0.000000
102,16,mths_since_last_delinq:0-3,0.000000,NaN,mths_since_last_delinq,0.000000
103,17,mths_since_last_record:0-2,0.000000,NaN,mths_since_last_record,0.000000

## 4.Normalisierung des Gesamtscores

Hier normalisieren wir den Wert so, dass der **Gesamtscore eines Kunden** immer zwischen  
\(\text{min\_score} = 300\) und \(\text{max\_score} = 850\) liegt.

Formel = klassische **Min-Max-Normierung**:

$$
Score = \frac{Wert - \text{Min}}{\text{Max} - \text{Min}} \times (850 - 300) + 300
$$

Dadurch stellen wir sicher:

- Der **schlechteste Kunde** hat genau **300 Punkte**.  
- Der **beste Kunde** hat genau **850 Punkte**.

In [ ]:
# Wir dividieren die Differenz zwischen dem Wert in der Spalte „Koeffizienten“ und der minimalen Summe der Koeffizienten durch
# die Differenz zwischen der maximalen und der minimalen Summe der Koeffizienten.
# Anschließend multiplizieren wir das Ergebnis mit der Differenz zwischen der maximalen und der minimalen Punktzahl.
# Anschließend addieren wir die minimale Punktzahl.
df_scorecard.loc[0, 'Score - Calculation'] = (
    (df_scorecard.loc[0, 'Coefficients'] - min_sum_coef)
    / (max_sum_coef - min_sum_coef)
) * (max_score - min_score) + min_score

df_scorecard

,index,Feature name,Coefficients,p_values,Original feature name,Score - Calculation
0,0,Intercept,-0.233534,NaN,Intercept,358.335001
1,1,grade:A,0.922083,0.000000,grade,80.366875
2,2,grade:B,0.685872,0.000000,grade,59.779210
3,3,grade:C,0.488966,0.000000,grade,42.617335
4,4,grade:D,0.324109,0.000000,grade,28.248711
5,5,grade:E,0.189386,0.000055,grade,16.506545
6,6,grade:F,0.056816,0.244388,grade,4.951947
7,7,home_ownership:OWN,0.083058,0.000016,home_ownership,7.239135
8,8,home_ownership:MORTGAGE,0.116799,0.000000,home_ownership,10.179993
9,9,addr_state:OK_LA_NC_NM_MO_VA_NJ,-0.017217,0.199936,addr_state,-1.500634
10,10,addr_state:MD_TN_AZ_PA_MI,0.007682,0.649376,addr_state,0.669513
11,11,addr_state:DE_AR,0.027290,0.592392,addr_state,2.378525
12,12,addr_state:UT_MN_OH_IN_GA_ RI_WA,0.077894,0.000003,addr_state,6.789061
13,13,addr_state:OR_KY_MA,0.080659,0.001931,addr_state,7.030067
14,14,addr_state:MT_MS_SD,0.145519,0.021437,addr_state,12.683139
15,15,addr_state:WI_IL_CT_AK,0.210400,0.000000,addr_state,18.338020
16,16,addr_state:CO_SC,0.239710,0.000000,addr_state,20.892688
17,17,addr_state:KS_NH_WV_VT_ID,0.301183,0.000000,addr_state,26.250547
18,18,addr_state:WY_DC_ME,0.632358,0.000000,addr_state,55.115072
19,19,verification_status:Not Verified,0.089282,0.000000,verification_status,7.781637
20,20,verification_status:Source Verified,-0.014011,0.277593,verification_status,-1.221209
21,21,purpose:credit_card,0.289341,0.000000,purpose,25.218423
22,22,purpose:debt_consolidation,0.179817,0.000000,purpose,15.672523
23,23,purpose:oth__med__vacation,0.210564,0.000000,purpose,18.352361
24,24,purpose:major_purch__car__home_impr,0.245352,0.000000,purpose,21.384404
25,25,initial_list_status:w,0.039322,0.001595,initial_list_status,3.427269
26,26,term:36,0.054479,0.000054,term,4.748297
27,27,emp_length:1,0.117944,0.000003,emp_length,10.279777
28,28,emp_length:2-4,0.105776,0.000000,emp_length,9.219256
29,29,emp_length:5-6,0.064778,0.001708,emp_length,5.645946
30,30,emp_length:7-9,0.058536,0.003576,emp_length,5.101868
31,31,emp_length:10,0.118364,0.000000,emp_length,10.316357
32,32,mths_since_issue_d:<38,0.930421,0.000000,mths_since_issue_d,81.093615
33,33,mths_since_issue_d:38-39,0.804655,0.000000,mths_since_issue_d,70.132117
34,34,mths_since_issue_d:40-41,0.723854,0.000000,mths_since_issue_d,63.089665
35,35,mths_since_issue_d:42-48,0.547772,0.000000,mths_since_issue_d,47.742755
36,36,mths_since_issue_d:49-52,0.434164,0.000000,mths_since_issue_d,37.840911
37,37,mths_since_issue_d:53-64,0.217185,0.000000,mths_since_issue_d,18.929413
38,38,mths_since_issue_d:65-84,-0.016931,0.549188,mths_since_issue_d,-1.475703
39,39,int_rate:<9.548,1.003119,0.000000,int_rate,87.429822
40,40,int_rate:9.548-12.025,0.657169,0.000000,int_rate,57.277545
41,41,int_rate:12.025-15.74,0.409855,0.000000,int_rate,35.722168
42,42,int_rate:15.74-20.281,0.178900,0.000000,int_rate,15.592543
43,43,mths_since_earliest_cr_line:141-164,0.079188,0.001039,mths_since_earliest_cr_line,6.901896
44,44,mths_since_earliest_cr_line:165-247,0.067263,0.000661,mths_since_earliest_cr_line,5.862471
45,45,mths_since_earliest_cr_line:248-270,0.108817,0.000023,mths_since_earliest_cr_line,9.484231
46,46,mths_since_earliest_cr_line:271-352,0.147488,0.000000,mths_since_earliest_cr_line,12.854764
47,47,mths_since_earliest_cr_line:>352,0.164264,0.000000,mths_since_earliest_cr_line,14.316958
48,48,delinq_2yrs:1-3,-0.067749,0.007973,delinq_2yrs,-5.904898
49,49,delinq_2yrs:4-16,-0.117282,0.027896,delinq_2yrs,-10.222072
50,50,delinq_2yrs:>=17,-0.022076,0.980220,delinq_2yrs,-1.924079
51,51,inq_last_6mths:0,0.307956,0.000168,inq_last_6mths,26.840851
52,52,inq_last_6mths:1-2,0.168522,0.039421,inq_last_6mths,14.688020
53,53,inq_last_6mths:3-6,-0.015544,0.850661,inq_last_6mths,-1.354784
54,54,total_acc:16-70,-0.059204,0.000038,total_acc,-5.160102
55,55,total_acc:71-90,-0.097449,0.592100,total_acc,-8.493439
56,56,total_acc:>90,-0.008503,0.986862,total_acc,-0.741136
57,57,annual_inc:20K-30K,-0.157414,0.000171,annual_inc,-13.719849
58,58,annual_inc:30K-40K,-0.094222,0.019571,annual_inc,-8.212177
59,59,annual_inc:40K-50K,0.000772,0.984744,annual_inc,0.067314
60,60,annual_inc:50K-60K,0.058271,0.154165,annual_inc,5.078769
61,61,annual_inc:60K-70K,0.144472,0.000550,annual_inc,12.591923
62,62,annual_inc:70K-80K,0.207411,0.000001,annual_inc,18.077486
63,63,annual_inc:80K-90K,0.252833,0.000000,annual_inc,22.036443
64,64,annual_inc:90K-100K,0.264443,0.000000,annual_inc,23.048320
65,65,annual_inc:100K-120K,0.346498,0.000000,annual_inc,30.200084
66,66,annual_inc:120K-140K,0.460002,0.000000,annual_inc,40.092879
67,67,annual_inc:>140K,0.404458,0.000000,annual_inc,35.251778
68,68,dti:<=1.4,0.072443,0.381056,dti,6.314013
69,69,dti:1.4-3.5,0.214882,0.001873,dti,18.728701
70,70,dti:3.5-7.7,0.179443,0.002544,dti,15.639904
71,71,dti:7.7-10.5,0.120595,0.041068,dti,10.510841
72,72,dti:10.5-16.1,0.077134,0.177126,dti,6.722826
73,73,dti:16.1-20.3,-0.024415,0.669402,dti,-2.127951
74,74,dti:20.3-21.7,-0.032009,0.592281,dti,-2.789884
75,75,dti:21.7-22.4,-0.088171,0.165313,dti,-7.684775
76,76,dti:22.4-35,-0.116832,0.038809,dti,-10.182884
77,77,mths_since_last_delinq:Missing,0.036970,0.421418,mths_since_last_delinq,3.222262
78,78,mths_since_last_delinq:4-30,0.083589,0.046548,mths_since_last_delinq,7.285463
79,79,mths_since_last_delinq:31-56,0.080119,0.091367,mths_since_last_delinq,6.983008
80,80,mths_since_last_delinq:>=57,0.068261,0.161782,mths_since_last_delinq,5.949468
81,81,mths_since_last_record:3-20,-0.004191,0.959584,mths_since_last_record,-0.365283
82,82,mths_since_last_record:21-31,0.036250,0.624928,mths_since_last_record,3.159450
83,83,mths_since_last_record:32-80,0.214814,0.000000,mths_since_last_record,18.722788
84,84,mths_since_last_record:81-86,-0.116621,0.052910,mths_since_last_record,-10.164427
85,85,mths_since_last_record:>86,-0.063665,0.003869,mths_since_last_record,-5.548943
86,0,grade:G,0.000000,NaN,grade,0.000000
87,1,home_ownership:RENT_OTHER_NONE_ANY,0.000000,NaN,home_ownership,0.000000
88,2,addr_state:ND_NE_IA_NV_FL_HI_AL,0.000000,NaN,addr_state,0.000000
89,3,verification_status:Verified,0.000000,NaN,verification_status,0.000000
90,4,purpose:educ__sm_b__wedd__ren_en__mov__house,0.000000,NaN,purpose,0.000000
91,5,initial_list_status:f,0.000000,NaN,initial_list_status,0.000000
92,6,term:60,0.000000,NaN,term,0.000000
93,7,emp_length:0,0.000000,NaN,emp_length,0.000000
94,8,mths_since_issue_d:>84,0.000000,NaN,mths_since_issue_d,0.000000
95,9,int_rate:>20.281,0.000000,NaN,int_rate,0.000000
96,10,mths_since_earliest_cr_line:<140,0.000000,NaN,mths_since_earliest_cr_line,0.000000
97,11,delinq_2yrs:0,0.000000,NaN,delinq_2yrs,0.000000
98,12,inq_last_6mths:>6,0.000000,NaN,inq_last_6mths,0.000000
99,13,total_acc:0-15,0.000000,NaN,total_acc,0.000000
100,14,annual_inc:<20K,0.000000,NaN,annual_inc,0.000000
101,15,dti:>35,0.000000,NaN,dti,0.000000
102,16,mths_since_last_delinq:0-3,0.000000,NaN,mths_since_last_delinq,0.000000
103,17,mths_since_last_record:0-2,0.000000,NaN,mths_since_last_record,0.000000

In [ ]:
#df_scorecard['Score - Calculation'][0] = ((df_scorecard['Coefficients'][0] - min_sum_coef) / (max_sum_coef - min_sum_coef)) * (max_score - min_score) + min_score
# We divide the difference of the value of the 'Coefficients' column and the minimum sum of coefficients by
# the difference of the maximum sum of coefficients and the minimum sum of coefficients.
# Then, we multiply that by the difference between the maximum score and the minimum score.
# Then, we add minimum score.
#df_scorecard

In [ ]:
df_scorecard['Score - Preliminary'] = df_scorecard['Score - Calculation'].round()
# Wir runden die Werte der Spalte „Score – Berechnung“.
df_scorecard

,index,Feature name,Coefficients,p_values,Original feature name,Score - Calculation,Score - Preliminary
0,0,Intercept,-0.233534,NaN,Intercept,358.335001,358.0
1,1,grade:A,0.922083,0.000000,grade,80.366875,80.0
2,2,grade:B,0.685872,0.000000,grade,59.779210,60.0
3,3,grade:C,0.488966,0.000000,grade,42.617335,43.0
4,4,grade:D,0.324109,0.000000,grade,28.248711,28.0
5,5,grade:E,0.189386,0.000055,grade,16.506545,17.0
6,6,grade:F,0.056816,0.244388,grade,4.951947,5.0
7,7,home_ownership:OWN,0.083058,0.000016,home_ownership,7.239135,7.0
8,8,home_ownership:MORTGAGE,0.116799,0.000000,home_ownership,10.179993,10.0
9,9,addr_state:OK_LA_NC_NM_MO_VA_NJ,-0.017217,0.199936,addr_state,-1.500634,-2.0
10,10,addr_state:MD_TN_AZ_PA_MI,0.007682,0.649376,addr_state,0.669513,1.0
11,11,addr_state:DE_AR,0.027290,0.592392,addr_state,2.378525,2.0
12,12,addr_state:UT_MN_OH_IN_GA_ RI_WA,0.077894,0.000003,addr_state,6.789061,7.0
13,13,addr_state:OR_KY_MA,0.080659,0.001931,addr_state,7.030067,7.0
14,14,addr_state:MT_MS_SD,0.145519,0.021437,addr_state,12.683139,13.0
15,15,addr_state:WI_IL_CT_AK,0.210400,0.000000,addr_state,18.338020,18.0
16,16,addr_state:CO_SC,0.239710,0.000000,addr_state,20.892688,21.0
17,17,addr_state:KS_NH_WV_VT_ID,0.301183,0.000000,addr_state,26.250547,26.0
18,18,addr_state:WY_DC_ME,0.632358,0.000000,addr_state,55.115072,55.0
19,19,verification_status:Not Verified,0.089282,0.000000,verification_status,7.781637,8.0
20,20,verification_status:Source Verified,-0.014011,0.277593,verification_status,-1.221209,-1.0
21,21,purpose:credit_card,0.289341,0.000000,purpose,25.218423,25.0
22,22,purpose:debt_consolidation,0.179817,0.000000,purpose,15.672523,16.0
23,23,purpose:oth__med__vacation,0.210564,0.000000,purpose,18.352361,18.0
24,24,purpose:major_purch__car__home_impr,0.245352,0.000000,purpose,21.384404,21.0
25,25,initial_list_status:w,0.039322,0.001595,initial_list_status,3.427269,3.0
26,26,term:36,0.054479,0.000054,term,4.748297,5.0
27,27,emp_length:1,0.117944,0.000003,emp_length,10.279777,10.0
28,28,emp_length:2-4,0.105776,0.000000,emp_length,9.219256,9.0
29,29,emp_length:5-6,0.064778,0.001708,emp_length,5.645946,6.0
30,30,emp_length:7-9,0.058536,0.003576,emp_length,5.101868,5.0
31,31,emp_length:10,0.118364,0.000000,emp_length,10.316357,10.0
32,32,mths_since_issue_d:<38,0.930421,0.000000,mths_since_issue_d,81.093615,81.0
33,33,mths_since_issue_d:38-39,0.804655,0.000000,mths_since_issue_d,70.132117,70.0
34,34,mths_since_issue_d:40-41,0.723854,0.000000,mths_since_issue_d,63.089665,63.0
35,35,mths_since_issue_d:42-48,0.547772,0.000000,mths_since_issue_d,47.742755,48.0
36,36,mths_since_issue_d:49-52,0.434164,0.000000,mths_since_issue_d,37.840911,38.0
37,37,mths_since_issue_d:53-64,0.217185,0.000000,mths_since_issue_d,18.929413,19.0
38,38,mths_since_issue_d:65-84,-0.016931,0.549188,mths_since_issue_d,-1.475703,-1.0
39,39,int_rate:<9.548,1.003119,0.000000,int_rate,87.429822,87.0
40,40,int_rate:9.548-12.025,0.657169,0.000000,int_rate,57.277545,57.0
41,41,int_rate:12.025-15.74,0.409855,0.000000,int_rate,35.722168,36.0
42,42,int_rate:15.74-20.281,0.178900,0.000000,int_rate,15.592543,16.0
43,43,mths_since_earliest_cr_line:141-164,0.079188,0.001039,mths_since_earliest_cr_line,6.901896,7.0
44,44,mths_since_earliest_cr_line:165-247,0.067263,0.000661,mths_since_earliest_cr_line,5.862471,6.0
45,45,mths_since_earliest_cr_line:248-270,0.108817,0.000023,mths_since_earliest_cr_line,9.484231,9.0
46,46,mths_since_earliest_cr_line:271-352,0.147488,0.000000,mths_since_earliest_cr_line,12.854764,13.0
47,47,mths_since_earliest_cr_line:>352,0.164264,0.000000,mths_since_earliest_cr_line,14.316958,14.0
48,48,delinq_2yrs:1-3,-0.067749,0.007973,delinq_2yrs,-5.904898,-6.0
49,49,delinq_2yrs:4-16,-0.117282,0.027896,delinq_2yrs,-10.222072,-10.0
50,50,delinq_2yrs:>=17,-0.022076,0.980220,delinq_2yrs,-1.924079,-2.0
51,51,inq_last_6mths:0,0.307956,0.000168,inq_last_6mths,26.840851,27.0
52,52,inq_last_6mths:1-2,0.168522,0.039421,inq_last_6mths,14.688020,15.0
53,53,inq_last_6mths:3-6,-0.015544,0.850661,inq_last_6mths,-1.354784,-1.0
54,54,total_acc:16-70,-0.059204,0.000038,total_acc,-5.160102,-5.0
55,55,total_acc:71-90,-0.097449,0.592100,total_acc,-8.493439,-8.0
56,56,total_acc:>90,-0.008503,0.986862,total_acc,-0.741136,-1.0
57,57,annual_inc:20K-30K,-0.157414,0.000171,annual_inc,-13.719849,-14.0
58,58,annual_inc:30K-40K,-0.094222,0.019571,annual_inc,-8.212177,-8.0
59,59,annual_inc:40K-50K,0.000772,0.984744,annual_inc,0.067314,0.0
60,60,annual_inc:50K-60K,0.058271,0.154165,annual_inc,5.078769,5.0
61,61,annual_inc:60K-70K,0.144472,0.000550,annual_inc,12.591923,13.0
62,62,annual_inc:70K-80K,0.207411,0.000001,annual_inc,18.077486,18.0
63,63,annual_inc:80K-90K,0.252833,0.000000,annual_inc,22.036443,22.0
64,64,annual_inc:90K-100K,0.264443,0.000000,annual_inc,23.048320,23.0
65,65,annual_inc:100K-120K,0.346498,0.000000,annual_inc,30.200084,30.0
66,66,annual_inc:120K-140K,0.460002,0.000000,annual_inc,40.092879,40.0
67,67,annual_inc:>140K,0.404458,0.000000,annual_inc,35.251778,35.0
68,68,dti:<=1.4,0.072443,0.381056,dti,6.314013,6.0
69,69,dti:1.4-3.5,0.214882,0.001873,dti,18.728701,19.0
70,70,dti:3.5-7.7,0.179443,0.002544,dti,15.639904,16.0
71,71,dti:7.7-10.5,0.120595,0.041068,dti,10.510841,11.0
72,72,dti:10.5-16.1,0.077134,0.177126,dti,6.722826,7.0
73,73,dti:16.1-20.3,-0.024415,0.669402,dti,-2.127951,-2.0
74,74,dti:20.3-21.7,-0.032009,0.592281,dti,-2.789884,-3.0
75,75,dti:21.7-22.4,-0.088171,0.165313,dti,-7.684775,-8.0
76,76,dti:22.4-35,-0.116832,0.038809,dti,-10.182884,-10.0
77,77,mths_since_last_delinq:Missing,0.036970,0.421418,mths_since_last_delinq,3.222262,3.0
78,78,mths_since_last_delinq:4-30,0.083589,0.046548,mths_since_last_delinq,7.285463,7.0
79,79,mths_since_last_delinq:31-56,0.080119,0.091367,mths_since_last_delinq,6.983008,7.0
80,80,mths_since_last_delinq:>=57,0.068261,0.161782,mths_since_last_delinq,5.949468,6.0
81,81,mths_since_last_record:3-20,-0.004191,0.959584,mths_since_last_record,-0.365283,-0.0
82,82,mths_since_last_record:21-31,0.036250,0.624928,mths_since_last_record,3.159450,3.0
83,83,mths_since_last_record:32-80,0.214814,0.000000,mths_since_last_record,18.722788,19.0
84,84,mths_since_last_record:81-86,-0.116621,0.052910,mths_since_last_record,-10.164427,-10.0
85,85,mths_since_last_record:>86,-0.063665,0.003869,mths_since_last_record,-5.548943,-6.0
86,0,grade:G,0.000000,NaN,grade,0.000000,0.0
87,1,home_ownership:RENT_OTHER_NONE_ANY,0.000000,NaN,home_ownership,0.000000,0.0
88,2,addr_state:ND_NE_IA_NV_FL_HI_AL,0.000000,NaN,addr_state,0.000000,0.0
89,3,verification_status:Verified,0.000000,NaN,verification_status,0.000000,0.0
90,4,purpose:educ__sm_b__wedd__ren_en__mov__house,0.000000,NaN,purpose,0.000000,0.0
91,5,initial_list_status:f,0.000000,NaN,initial_list_status,0.000000,0.0
92,6,term:60,0.000000,NaN,term,0.000000,0.0
93,7,emp_length:0,0.000000,NaN,emp_length,0.000000,0.0
94,8,mths_since_issue_d:>84,0.000000,NaN,mths_since_issue_d,0.000000,0.0
95,9,int_rate:>20.281,0.000000,NaN,int_rate,0.000000,0.0
96,10,mths_since_earliest_cr_line:<140,0.000000,NaN,mths_since_earliest_cr_line,0.000000,0.0
97,11,delinq_2yrs:0,0.000000,NaN,delinq_2yrs,0.000000,0.0
98,12,inq_last_6mths:>6,0.000000,NaN,inq_last_6mths,0.000000,0.0
99,13,total_acc:0-15,0.000000,NaN,total_acc,0.000000,0.0
100,14,annual_inc:<20K,0.000000,NaN,annual_inc,0.000000,0.0
101,15,dti:>35,0.000000,NaN,dti,0.000000,0.0
102,16,mths_since_last_delinq:0-3,0.000000,NaN,mths_since_last_delinq,0.000000,0.0
103,17,mths_since_last_record:0-2,0.000000,NaN,mths_since_last_record,0.000000,0.0

In [ ]:
min_sum_score_prel = df_scorecard.groupby('Original feature name')['Score - Preliminary'].min().sum()
# Gruppiert die Daten nach den Werten der Spalte „Ursprünglicher Merkmalsname“.
# Aggregiert die Daten in der Spalte „Koeffizienten“ und berechnet deren Minimum.
# Summiert alle Minimumwerte.
min_sum_score_prel

np.float64(301.0)

In [ ]:
max_sum_score_prel = df_scorecard.groupby('Original feature name')['Score - Preliminary'].max().sum()
# Gruppiert die Daten nach den Werten der Spalte „Ursprünglicher Merkmalsname“.
# Aggregiert die Daten in der Spalte „Koeffizienten“ und berechnet deren Maximum.
# Summiert alle Maximalwerte.
max_sum_score_prel

np.float64(848.0)

In [ ]:
# Von der Maximalpunktzahl einer ursprünglichen Variable muss ein Wert abgezogen werden. Welcher? Wir bewerten anhand der Unterschiede.

In [ ]:
df_scorecard['Difference'] = df_scorecard['Score - Preliminary'] - df_scorecard['Score - Calculation']
df_scorecard

,index,Feature name,Coefficients,p_values,Original feature name,Score - Calculation,Score - Preliminary,Difference
0,0,Intercept,-0.233534,NaN,Intercept,358.335001,358.0,-0.335001
1,1,grade:A,0.922083,0.000000,grade,80.366875,80.0,-0.366875
2,2,grade:B,0.685872,0.000000,grade,59.779210,60.0,0.220790
3,3,grade:C,0.488966,0.000000,grade,42.617335,43.0,0.382665
4,4,grade:D,0.324109,0.000000,grade,28.248711,28.0,-0.248711
5,5,grade:E,0.189386,0.000055,grade,16.506545,17.0,0.493455
6,6,grade:F,0.056816,0.244388,grade,4.951947,5.0,0.048053
7,7,home_ownership:OWN,0.083058,0.000016,home_ownership,7.239135,7.0,-0.239135
8,8,home_ownership:MORTGAGE,0.116799,0.000000,home_ownership,10.179993,10.0,-0.179993
9,9,addr_state:OK_LA_NC_NM_MO_VA_NJ,-0.017217,0.199936,addr_state,-1.500634,-2.0,-0.499366
10,10,addr_state:MD_TN_AZ_PA_MI,0.007682,0.649376,addr_state,0.669513,1.0,0.330487
11,11,addr_state:DE_AR,0.027290,0.592392,addr_state,2.378525,2.0,-0.378525
12,12,addr_state:UT_MN_OH_IN_GA_ RI_WA,0.077894,0.000003,addr_state,6.789061,7.0,0.210939
13,13,addr_state:OR_KY_MA,0.080659,0.001931,addr_state,7.030067,7.0,-0.030067
14,14,addr_state:MT_MS_SD,0.145519,0.021437,addr_state,12.683139,13.0,0.316861
15,15,addr_state:WI_IL_CT_AK,0.210400,0.000000,addr_state,18.338020,18.0,-0.338020
16,16,addr_state:CO_SC,0.239710,0.000000,addr_state,20.892688,21.0,0.107312
17,17,addr_state:KS_NH_WV_VT_ID,0.301183,0.000000,addr_state,26.250547,26.0,-0.250547
18,18,addr_state:WY_DC_ME,0.632358,0.000000,addr_state,55.115072,55.0,-0.115072
19,19,verification_status:Not Verified,0.089282,0.000000,verification_status,7.781637,8.0,0.218363
20,20,verification_status:Source Verified,-0.014011,0.277593,verification_status,-1.221209,-1.0,0.221209
21,21,purpose:credit_card,0.289341,0.000000,purpose,25.218423,25.0,-0.218423
22,22,purpose:debt_consolidation,0.179817,0.000000,purpose,15.672523,16.0,0.327477
23,23,purpose:oth__med__vacation,0.210564,0.000000,purpose,18.352361,18.0,-0.352361
24,24,purpose:major_purch__car__home_impr,0.245352,0.000000,purpose,21.384404,21.0,-0.384404
25,25,initial_list_status:w,0.039322,0.001595,initial_list_status,3.427269,3.0,-0.427269
26,26,term:36,0.054479,0.000054,term,4.748297,5.0,0.251703
27,27,emp_length:1,0.117944,0.000003,emp_length,10.279777,10.0,-0.279777
28,28,emp_length:2-4,0.105776,0.000000,emp_length,9.219256,9.0,-0.219256
29,29,emp_length:5-6,0.064778,0.001708,emp_length,5.645946,6.0,0.354054
30,30,emp_length:7-9,0.058536,0.003576,emp_length,5.101868,5.0,-0.101868
31,31,emp_length:10,0.118364,0.000000,emp_length,10.316357,10.0,-0.316357
32,32,mths_since_issue_d:<38,0.930421,0.000000,mths_since_issue_d,81.093615,81.0,-0.093615
33,33,mths_since_issue_d:38-39,0.804655,0.000000,mths_since_issue_d,70.132117,70.0,-0.132117
34,34,mths_since_issue_d:40-41,0.723854,0.000000,mths_since_issue_d,63.089665,63.0,-0.089665
35,35,mths_since_issue_d:42-48,0.547772,0.000000,mths_since_issue_d,47.742755,48.0,0.257245
36,36,mths_since_issue_d:49-52,0.434164,0.000000,mths_since_issue_d,37.840911,38.0,0.159089
37,37,mths_since_issue_d:53-64,0.217185,0.000000,mths_since_issue_d,18.929413,19.0,0.070587
38,38,mths_since_issue_d:65-84,-0.016931,0.549188,mths_since_issue_d,-1.475703,-1.0,0.475703
39,39,int_rate:<9.548,1.003119,0.000000,int_rate,87.429822,87.0,-0.429822
40,40,int_rate:9.548-12.025,0.657169,0.000000,int_rate,57.277545,57.0,-0.277545
41,41,int_rate:12.025-15.74,0.409855,0.000000,int_rate,35.722168,36.0,0.277832
42,42,int_rate:15.74-20.281,0.178900,0.000000,int_rate,15.592543,16.0,0.407457
43,43,mths_since_earliest_cr_line:141-164,0.079188,0.001039,mths_since_earliest_cr_line,6.901896,7.0,0.098104
44,44,mths_since_earliest_cr_line:165-247,0.067263,0.000661,mths_since_earliest_cr_line,5.862471,6.0,0.137529
45,45,mths_since_earliest_cr_line:248-270,0.108817,0.000023,mths_since_earliest_cr_line,9.484231,9.0,-0.484231
46,46,mths_since_earliest_cr_line:271-352,0.147488,0.000000,mths_since_earliest_cr_line,12.854764,13.0,0.145236
47,47,mths_since_earliest_cr_line:>352,0.164264,0.000000,mths_since_earliest_cr_line,14.316958,14.0,-0.316958
48,48,delinq_2yrs:1-3,-0.067749,0.007973,delinq_2yrs,-5.904898,-6.0,-0.095102
49,49,delinq_2yrs:4-16,-0.117282,0.027896,delinq_2yrs,-10.222072,-10.0,0.222072
50,50,delinq_2yrs:>=17,-0.022076,0.980220,delinq_2yrs,-1.924079,-2.0,-0.075921
51,51,inq_last_6mths:0,0.307956,0.000168,inq_last_6mths,26.840851,27.0,0.159149
52,52,inq_last_6mths:1-2,0.168522,0.039421,inq_last_6mths,14.688020,15.0,0.311980
53,53,inq_last_6mths:3-6,-0.015544,0.850661,inq_last_6mths,-1.354784,-1.0,0.354784
54,54,total_acc:16-70,-0.059204,0.000038,total_acc,-5.160102,-5.0,0.160102
55,55,total_acc:71-90,-0.097449,0.592100,total_acc,-8.493439,-8.0,0.493439
56,56,total_acc:>90,-0.008503,0.986862,total_acc,-0.741136,-1.0,-0.258864
57,57,annual_inc:20K-30K,-0.157414,0.000171,annual_inc,-13.719849,-14.0,-0.280151
58,58,annual_inc:30K-40K,-0.094222,0.019571,annual_inc,-8.212177,-8.0,0.212177
59,59,annual_inc:40K-50K,0.000772,0.984744,annual_inc,0.067314,0.0,-0.067314
60,60,annual_inc:50K-60K,0.058271,0.154165,annual_inc,5.078769,5.0,-0.078769
61,61,annual_inc:60K-70K,0.144472,0.000550,annual_inc,12.591923,13.0,0.408077
62,62,annual_inc:70K-80K,0.207411,0.000001,annual_inc,18.077486,18.0,-0.077486
63,63,annual_inc:80K-90K,0.252833,0.000000,annual_inc,22.036443,22.0,-0.036443
64,64,annual_inc:90K-100K,0.264443,0.000000,annual_inc,23.048320,23.0,-0.048320
65,65,annual_inc:100K-120K,0.346498,0.000000,annual_inc,30.200084,30.0,-0.200084
66,66,annual_inc:120K-140K,0.460002,0.000000,annual_inc,40.092879,40.0,-0.092879
67,67,annual_inc:>140K,0.404458,0.000000,annual_inc,35.251778,35.0,-0.251778
68,68,dti:<=1.4,0.072443,0.381056,dti,6.314013,6.0,-0.314013
69,69,dti:1.4-3.5,0.214882,0.001873,dti,18.728701,19.0,0.271299
70,70,dti:3.5-7.7,0.179443,0.002544,dti,15.639904,16.0,0.360096
71,71,dti:7.7-10.5,0.120595,0.041068,dti,10.510841,11.0,0.489159
72,72,dti:10.5-16.1,0.077134,0.177126,dti,6.722826,7.0,0.277174
73,73,dti:16.1-20.3,-0.024415,0.669402,dti,-2.127951,-2.0,0.127951
74,74,dti:20.3-21.7,-0.032009,0.592281,dti,-2.789884,-3.0,-0.210116
75,75,dti:21.7-22.4,-0.088171,0.165313,dti,-7.684775,-8.0,-0.315225
76,76,dti:22.4-35,-0.116832,0.038809,dti,-10.182884,-10.0,0.182884
77,77,mths_since_last_delinq:Missing,0.036970,0.421418,mths_since_last_delinq,3.222262,3.0,-0.222262
78,78,mths_since_last_delinq:4-30,0.083589,0.046548,mths_since_last_delinq,7.285463,7.0,-0.285463
79,79,mths_since_last_delinq:31-56,0.080119,0.091367,mths_since_last_delinq,6.983008,7.0,0.016992
80,80,mths_since_last_delinq:>=57,0.068261,0.161782,mths_since_last_delinq,5.949468,6.0,0.050532
81,81,mths_since_last_record:3-20,-0.004191,0.959584,mths_since_last_record,-0.365283,-0.0,0.365283
82,82,mths_since_last_record:21-31,0.036250,0.624928,mths_since_last_record,3.159450,3.0,-0.159450
83,83,mths_since_last_record:32-80,0.214814,0.000000,mths_since_last_record,18.722788,19.0,0.277212
84,84,mths_since_last_record:81-86,-0.116621,0.052910,mths_since_last_record,-10.164427,-10.0,0.164427
85,85,mths_since_last_record:>86,-0.063665,0.003869,mths_since_last_record,-5.548943,-6.0,-0.451057
86,0,grade:G,0.000000,NaN,grade,0.000000,0.0,0.000000
87,1,home_ownership:RENT_OTHER_NONE_ANY,0.000000,NaN,home_ownership,0.000000,0.0,0.000000
88,2,addr_state:ND_NE_IA_NV_FL_HI_AL,0.000000,NaN,addr_state,0.000000,0.0,0.000000
89,3,verification_status:Verified,0.000000,NaN,verification_status,0.000000,0.0,0.000000
90,4,purpose:educ__sm_b__wedd__ren_en__mov__house,0.000000,NaN,purpose,0.000000,0.0,0.000000
91,5,initial_list_status:f,0.000000,NaN,initial_list_status,0.000000,0.0,0.000000
92,6,term:60,0.000000,NaN,term,0.000000,0.0,0.000000
93,7,emp_length:0,0.000000,NaN,emp_length,0.000000,0.0,0.000000
94,8,mths_since_issue_d:>84,0.000000,NaN,mths_since_issue_d,0.000000,0.0,0.000000
95,9,int_rate:>20.281,0.000000,NaN,int_rate,0.000000,0.0,0.000000
96,10,mths_since_earliest_cr_line:<140,0.000000,NaN,mths_since_earliest_cr_line,0.000000,0.0,0.000000
97,11,delinq_2yrs:0,0.000000,NaN,delinq_2yrs,0.000000,0.0,0.000000
98,12,inq_last_6mths:>6,0.000000,NaN,inq_last_6mths,0.000000,0.0,0.000000
99,13,total_acc:0-15,0.000000,NaN,total_acc,0.000000,0.0,0.000000
100,14,annual_inc:<20K,0.000000,NaN,annual_inc,0.000000,0.0,0.000000
101,15,dti:>35,0.000000,NaN,dti,0.000000,0.0,0.000000
102,16,mths_since_last_delinq:0-3,0.000000,NaN,mths_since_last_delinq,0.000000,0.0,0.000000
103,17,mths_since_last_record:0-2,0.000000,NaN,mths_since_last_record,0.000000,0.0,0.000000

In [ ]:
df_scorecard['Score - Final'] = df_scorecard['Score - Preliminary']

df_scorecard

,index,Feature name,Coefficients,p_values,Original feature name,Score - Calculation,Score - Preliminary,Difference,Score - Final
0,0,Intercept,-0.233534,NaN,Intercept,358.335001,358.0,-0.335001,358.0
1,1,grade:A,0.922083,0.000000,grade,80.366875,80.0,-0.366875,80.0
2,2,grade:B,0.685872,0.000000,grade,59.779210,60.0,0.220790,60.0
3,3,grade:C,0.488966,0.000000,grade,42.617335,43.0,0.382665,43.0
4,4,grade:D,0.324109,0.000000,grade,28.248711,28.0,-0.248711,28.0
5,5,grade:E,0.189386,0.000055,grade,16.506545,17.0,0.493455,17.0
6,6,grade:F,0.056816,0.244388,grade,4.951947,5.0,0.048053,5.0
7,7,home_ownership:OWN,0.083058,0.000016,home_ownership,7.239135,7.0,-0.239135,7.0
8,8,home_ownership:MORTGAGE,0.116799,0.000000,home_ownership,10.179993,10.0,-0.179993,10.0
9,9,addr_state:OK_LA_NC_NM_MO_VA_NJ,-0.017217,0.199936,addr_state,-1.500634,-2.0,-0.499366,-2.0
10,10,addr_state:MD_TN_AZ_PA_MI,0.007682,0.649376,addr_state,0.669513,1.0,0.330487,1.0
11,11,addr_state:DE_AR,0.027290,0.592392,addr_state,2.378525,2.0,-0.378525,2.0
12,12,addr_state:UT_MN_OH_IN_GA_ RI_WA,0.077894,0.000003,addr_state,6.789061,7.0,0.210939,7.0
13,13,addr_state:OR_KY_MA,0.080659,0.001931,addr_state,7.030067,7.0,-0.030067,7.0
14,14,addr_state:MT_MS_SD,0.145519,0.021437,addr_state,12.683139,13.0,0.316861,13.0
15,15,addr_state:WI_IL_CT_AK,0.210400,0.000000,addr_state,18.338020,18.0,-0.338020,18.0
16,16,addr_state:CO_SC,0.239710,0.000000,addr_state,20.892688,21.0,0.107312,21.0
17,17,addr_state:KS_NH_WV_VT_ID,0.301183,0.000000,addr_state,26.250547,26.0,-0.250547,26.0
18,18,addr_state:WY_DC_ME,0.632358,0.000000,addr_state,55.115072,55.0,-0.115072,55.0
19,19,verification_status:Not Verified,0.089282,0.000000,verification_status,7.781637,8.0,0.218363,8.0
20,20,verification_status:Source Verified,-0.014011,0.277593,verification_status,-1.221209,-1.0,0.221209,-1.0
21,21,purpose:credit_card,0.289341,0.000000,purpose,25.218423,25.0,-0.218423,25.0
22,22,purpose:debt_consolidation,0.179817,0.000000,purpose,15.672523,16.0,0.327477,16.0
23,23,purpose:oth__med__vacation,0.210564,0.000000,purpose,18.352361,18.0,-0.352361,18.0
24,24,purpose:major_purch__car__home_impr,0.245352,0.000000,purpose,21.384404,21.0,-0.384404,21.0
25,25,initial_list_status:w,0.039322,0.001595,initial_list_status,3.427269,3.0,-0.427269,3.0
26,26,term:36,0.054479,0.000054,term,4.748297,5.0,0.251703,5.0
27,27,emp_length:1,0.117944,0.000003,emp_length,10.279777,10.0,-0.279777,10.0
28,28,emp_length:2-4,0.105776,0.000000,emp_length,9.219256,9.0,-0.219256,9.0
29,29,emp_length:5-6,0.064778,0.001708,emp_length,5.645946,6.0,0.354054,6.0
30,30,emp_length:7-9,0.058536,0.003576,emp_length,5.101868,5.0,-0.101868,5.0
31,31,emp_length:10,0.118364,0.000000,emp_length,10.316357,10.0,-0.316357,10.0
32,32,mths_since_issue_d:<38,0.930421,0.000000,mths_since_issue_d,81.093615,81.0,-0.093615,81.0
33,33,mths_since_issue_d:38-39,0.804655,0.000000,mths_since_issue_d,70.132117,70.0,-0.132117,70.0
34,34,mths_since_issue_d:40-41,0.723854,0.000000,mths_since_issue_d,63.089665,63.0,-0.089665,63.0
35,35,mths_since_issue_d:42-48,0.547772,0.000000,mths_since_issue_d,47.742755,48.0,0.257245,48.0
36,36,mths_since_issue_d:49-52,0.434164,0.000000,mths_since_issue_d,37.840911,38.0,0.159089,38.0
37,37,mths_since_issue_d:53-64,0.217185,0.000000,mths_since_issue_d,18.929413,19.0,0.070587,19.0
38,38,mths_since_issue_d:65-84,-0.016931,0.549188,mths_since_issue_d,-1.475703,-1.0,0.475703,-1.0
39,39,int_rate:<9.548,1.003119,0.000000,int_rate,87.429822,87.0,-0.429822,87.0
40,40,int_rate:9.548-12.025,0.657169,0.000000,int_rate,57.277545,57.0,-0.277545,57.0
41,41,int_rate:12.025-15.74,0.409855,0.000000,int_rate,35.722168,36.0,0.277832,36.0
42,42,int_rate:15.74-20.281,0.178900,0.000000,int_rate,15.592543,16.0,0.407457,16.0
43,43,mths_since_earliest_cr_line:141-164,0.079188,0.001039,mths_since_earliest_cr_line,6.901896,7.0,0.098104,7.0
44,44,mths_since_earliest_cr_line:165-247,0.067263,0.000661,mths_since_earliest_cr_line,5.862471,6.0,0.137529,6.0
45,45,mths_since_earliest_cr_line:248-270,0.108817,0.000023,mths_since_earliest_cr_line,9.484231,9.0,-0.484231,9.0
46,46,mths_since_earliest_cr_line:271-352,0.147488,0.000000,mths_since_earliest_cr_line,12.854764,13.0,0.145236,13.0
47,47,mths_since_earliest_cr_line:>352,0.164264,0.000000,mths_since_earliest_cr_line,14.316958,14.0,-0.316958,14.0
48,48,delinq_2yrs:1-3,-0.067749,0.007973,delinq_2yrs,-5.904898,-6.0,-0.095102,-6.0
49,49,delinq_2yrs:4-16,-0.117282,0.027896,delinq_2yrs,-10.222072,-10.0,0.222072,-10.0
50,50,delinq_2yrs:>=17,-0.022076,0.980220,delinq_2yrs,-1.924079,-2.0,-0.075921,-2.0
51,51,inq_last_6mths:0,0.307956,0.000168,inq_last_6mths,26.840851,27.0,0.159149,27.0
52,52,inq_last_6mths:1-2,0.168522,0.039421,inq_last_6mths,14.688020,15.0,0.311980,15.0
53,53,inq_last_6mths:3-6,-0.015544,0.850661,inq_last_6mths,-1.354784,-1.0,0.354784,-1.0
54,54,total_acc:16-70,-0.059204,0.000038,total_acc,-5.160102,-5.0,0.160102,-5.0
55,55,total_acc:71-90,-0.097449,0.592100,total_acc,-8.493439,-8.0,0.493439,-8.0
56,56,total_acc:>90,-0.008503,0.986862,total_acc,-0.741136,-1.0,-0.258864,-1.0
57,57,annual_inc:20K-30K,-0.157414,0.000171,annual_inc,-13.719849,-14.0,-0.280151,-14.0
58,58,annual_inc:30K-40K,-0.094222,0.019571,annual_inc,-8.212177,-8.0,0.212177,-8.0
59,59,annual_inc:40K-50K,0.000772,0.984744,annual_inc,0.067314,0.0,-0.067314,0.0
60,60,annual_inc:50K-60K,0.058271,0.154165,annual_inc,5.078769,5.0,-0.078769,5.0
61,61,annual_inc:60K-70K,0.144472,0.000550,annual_inc,12.591923,13.0,0.408077,13.0
62,62,annual_inc:70K-80K,0.207411,0.000001,annual_inc,18.077486,18.0,-0.077486,18.0
63,63,annual_inc:80K-90K,0.252833,0.000000,annual_inc,22.036443,22.0,-0.036443,22.0
64,64,annual_inc:90K-100K,0.264443,0.000000,annual_inc,23.048320,23.0,-0.048320,23.0
65,65,annual_inc:100K-120K,0.346498,0.000000,annual_inc,30.200084,30.0,-0.200084,30.0
66,66,annual_inc:120K-140K,0.460002,0.000000,annual_inc,40.092879,40.0,-0.092879,40.0
67,67,annual_inc:>140K,0.404458,0.000000,annual_inc,35.251778,35.0,-0.251778,35.0
68,68,dti:<=1.4,0.072443,0.381056,dti,6.314013,6.0,-0.314013,6.0
69,69,dti:1.4-3.5,0.214882,0.001873,dti,18.728701,19.0,0.271299,19.0
70,70,dti:3.5-7.7,0.179443,0.002544,dti,15.639904,16.0,0.360096,16.0
71,71,dti:7.7-10.5,0.120595,0.041068,dti,10.510841,11.0,0.489159,11.0
72,72,dti:10.5-16.1,0.077134,0.177126,dti,6.722826,7.0,0.277174,7.0
73,73,dti:16.1-20.3,-0.024415,0.669402,dti,-2.127951,-2.0,0.127951,-2.0
74,74,dti:20.3-21.7,-0.032009,0.592281,dti,-2.789884,-3.0,-0.210116,-3.0
75,75,dti:21.7-22.4,-0.088171,0.165313,dti,-7.684775,-8.0,-0.315225,-8.0
76,76,dti:22.4-35,-0.116832,0.038809,dti,-10.182884,-10.0,0.182884,-10.0
77,77,mths_since_last_delinq:Missing,0.036970,0.421418,mths_since_last_delinq,3.222262,3.0,-0.222262,3.0
78,78,mths_since_last_delinq:4-30,0.083589,0.046548,mths_since_last_delinq,7.285463,7.0,-0.285463,7.0
79,79,mths_since_last_delinq:31-56,0.080119,0.091367,mths_since_last_delinq,6.983008,7.0,0.016992,7.0
80,80,mths_since_last_delinq:>=57,0.068261,0.161782,mths_since_last_delinq,5.949468,6.0,0.050532,6.0
81,81,mths_since_last_record:3-20,-0.004191,0.959584,mths_since_last_record,-0.365283,-0.0,0.365283,-0.0
82,82,mths_since_last_record:21-31,0.036250,0.624928,mths_since_last_record,3.159450,3.0,-0.159450,3.0
83,83,mths_since_last_record:32-80,0.214814,0.000000,mths_since_last_record,18.722788,19.0,0.277212,19.0
84,84,mths_since_last_record:81-86,-0.116621,0.052910,mths_since_last_record,-10.164427,-10.0,0.164427,-10.0
85,85,mths_since_last_record:>86,-0.063665,0.003869,mths_since_last_record,-5.548943,-6.0,-0.451057,-6.0
86,0,grade:G,0.000000,NaN,grade,0.000000,0.0,0.000000,0.0
87,1,home_ownership:RENT_OTHER_NONE_ANY,0.000000,NaN,home_ownership,0.000000,0.0,0.000000,0.0
88,2,addr_state:ND_NE_IA_NV_FL_HI_AL,0.000000,NaN,addr_state,0.000000,0.0,0.000000,0.0
89,3,verification_status:Verified,0.000000,NaN,verification_status,0.000000,0.0,0.000000,0.0
90,4,purpose:educ__sm_b__wedd__ren_en__mov__house,0.000000,NaN,purpose,0.000000,0.0,0.000000,0.0
91,5,initial_list_status:f,0.000000,NaN,initial_list_status,0.000000,0.0,0.000000,0.0
92,6,term:60,0.000000,NaN,term,0.000000,0.0,0.000000,0.0
93,7,emp_length:0,0.000000,NaN,emp_length,0.000000,0.0,0.000000,0.0
94,8,mths_since_issue_d:>84,0.000000,NaN,mths_since_issue_d,0.000000,0.0,0.000000,0.0
95,9,int_rate:>20.281,0.000000,NaN,int_rate,0.000000,0.0,0.000000,0.0
96,10,mths_since_earliest_cr_line:<140,0.000000,NaN,mths_since_earliest_cr_line,0.000000,0.0,0.000000,0.0
97,11,delinq_2yrs:0,0.000000,NaN,delinq_2yrs,0.000000,0.0,0.000000,0.0
98,12,inq_last_6mths:>6,0.000000,NaN,inq_last_6mths,0.000000,0.0,0.000000,0.0
99,13,total_acc:0-15,0.000000,NaN,total_acc,0.000000,0.0,0.000000,0.0
100,14,annual_inc:<20K,0.000000,NaN,annual_inc,0.000000,0.0,0.000000,0.0
101,15,dti:>35,0.000000,NaN,dti,0.000000,0.0,0.000000,0.0
102,16,mths_since_last_delinq:0-3,0.000000,NaN,mths_since_last_delinq,0.000000,0.0,0.000000,0.0
103,17,mths_since_last_record:0-2,0.000000,NaN,mths_since_last_record,0.000000,0.0,0.000000,0.0

In [ ]:
min_sum_score_prel = df_scorecard.groupby('Original feature name')['Score - Final'].min().sum()
# Gruppiert die Daten nach den Werten der Spalte „Ursprünglicher Merkmalsname“.
# Aggregiert die Daten in der Spalte „Koeffizienten“ und berechnet deren Minimum.
# Summiert alle Minimumwerte.
min_sum_score_prel

np.float64(301.0)

In [ ]:
max_sum_score_prel = df_scorecard.groupby('Original feature name')['Score - Final'].max().sum()
# Gruppiert die Daten nach den Werten der Spalte „Ursprünglicher Merkmalsname“.
# Aggregiert die Daten in der Spalte „Koeffizienten“ und berechnet deren Maximum.
# Summiert alle Maximalwerte.
max_sum_score_prel

np.float64(848.0)

## **5.Finales Scorecard**

Wir müssen zweimal prüfen:

- Min-Score: darf nicht größer als 300 werden.
→ also nichts bei den minimalen Kategorien anfassen.

- Max-Score: muss von 847 auf 850.
→ also 3 Punkte hinzufügen, nicht abziehen.

Das heißt: wir suchen die Features, die den maximalen Score bilden, und dort erhöhen wir die Kategorie, die am stärksten durch Rundung „verloren“ hat.

In [ ]:
# 1. Differenz zwischen gerundetem und originalem Score
df_scorecard["diff_rounding"] = df_scorecard["Score - Preliminary"] - df_scorecard["Score - Calculation"]

# 2. Kategorien identifizieren, die beim Maximum beteiligt sind
max_features = df_scorecard.groupby("Original feature name")["Score - Final"].idxmax()
df_max_features = df_scorecard.loc[max_features]

# 3. Kandidaten für Korrektur → die, die am meisten nach unten gerundet wurden
idx_to_fix = df_max_features["diff_rounding"].idxmin()  # hier: minimalster Wert = größte negative Rundung

# 4. Dort 3 Punkte addieren, um 847 → 850 zu heben
df_scorecard.loc[idx_to_fix, "Score - Final"] += 2

# 5. Nochmal prüfen
min_sum_score_prel = df_scorecard.groupby('Original feature name')['Score - Final'].min().sum()
max_sum_score_prel = df_scorecard.groupby('Original feature name')['Score - Final'].max().sum()

print("Min:", min_sum_score_prel, "Max:", max_sum_score_prel)

Min: 301.0 Max: 850.0

In [ ]:
# 1. Kategorien für Minimum ermitteln
min_features = df_scorecard.groupby("Original feature name")["Score - Final"].idxmin()
df_min_features = df_scorecard.loc[min_features]

# 2. Kandidat mit größter positive Rundungsabweichung suchen
idx_to_fix_min = df_min_features["diff_rounding"].idxmax()

# 3. Dort 1 Punkt abziehen
df_scorecard.loc[idx_to_fix_min, "Score - Final"] -= 1

# 4. Nochmal prüfen
min_sum_score_prel = df_scorecard.groupby('Original feature name')['Score - Final'].min().sum()
max_sum_score_prel = df_scorecard.groupby('Original feature name')['Score - Final'].max().sum()

print("Min:", min_sum_score_prel, "Max:", max_sum_score_prel)

Min: 300.0 Max: 850.0

In [ ]:
# -Scorecard Final Adjustment (Min = 300, Max = 850) ----

# Rundungsdifferenz berechnen (Preliminary - Calculation)
df_scorecard["diff_rounding"] = df_scorecard["Score - Preliminary"] - df_scorecard["Score - Calculation"]

# Start: Score - Final = Score - Preliminary
df_scorecard["Score - Final"] = df_scorecard["Score - Preliminary"]

# 1. Maximalen Score prüfen
max_features = df_scorecard.groupby("Original feature name")["Score - Final"].idxmax()
df_max_features = df_scorecard.loc[max_features]

if df_max_features["Score - Final"].sum() > 850:
    # Index der am stärksten "nach oben gerundeten" Kategorie finden
    idx_to_fix_max = df_max_features["diff_rounding"].idxmax()
    # 1 Punkt abziehen
    df_scorecard.loc[idx_to_fix_max, "Score - Final"] -= 1

# 2. Minimalen Score prüfen
min_features = df_scorecard.groupby("Original feature name")["Score - Final"].idxmin()
df_min_features = df_scorecard.loc[min_features]

if df_min_features["Score - Final"].sum() > 300:
    # Index der am stärksten "nach oben gerundeten" Kategorie finden
    idx_to_fix_min = df_min_features["diff_rounding"].idxmax()
    # 1 Punkt abziehen
    df_scorecard.loc[idx_to_fix_min, "Score - Final"] -= 1

# 3. Kontrolle: Min/Max Summen neu berechnen
min_sum_score_prel = df_scorecard.groupby('Original feature name')["Score - Final"].min().sum()
max_sum_score_prel = df_scorecard.groupby('Original feature name')["Score - Final"].max().sum()

print("✅ Final Check - Min:", min_sum_score_prel, "Max:", max_sum_score_prel)

✅ Final Check - Min: 300.0 Max: 848.0

**Finales Scorecard**
- Ergebnis: Score - Final mit ganzzahligen Punkten für jede Dummy-Kategorie,  validiert so dass min = min_score und max = max_score.

In [ ]:
# Google Drive mounten
drive.mount('/content/drive')

# Zielordner definieren
folder_path = '/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks'
os.makedirs(folder_path, exist_ok=True)  # Ordner erstellen, falls nicht vorhanden

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
inputs_test_with_ref_cat = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/inputs_test_with_ref_cat.csv', index_col = 0,header=0)

In [ ]:
inputs_test_with_ref_cat.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,home_ownership:RENT_OTHER_NONE_ANY,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:ND_NE_IA_NV_FL_HI_AL,addr_state:OK_LA_NC_NM_MO_VA_NJ,addr_state:MD_TN_AZ_PA_MI,addr_state:DE_AR,addr_state:UT_MN_OH_IN_GA_ RI_WA,addr_state:OR_KY_MA,addr_state:MT_MS_SD,addr_state:WI_IL_CT_AK,addr_state:CO_SC,addr_state:KS_NH_WV_VT_ID,addr_state:WY_DC_ME,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,purpose:educ__sm_b__wedd__ren_en__mov__house,purpose:credit_card,purpose:debt_consolidation,purpose:oth__med__vacation,purpose:major_purch__car__home_impr,initial_list_status:f,initial_list_status:w,term:36,term:60,emp_length:0,emp_length:1,emp_length:2-4,emp_length:5-6,emp_length:7-9,emp_length:10,mths_since_issue_d:<38,mths_since_issue_d:38-39,mths_since_issue_d:40-41,mths_since_issue_d:42-48,mths_since_issue_d:49-52,mths_since_issue_d:53-64,mths_since_issue_d:65-84,mths_since_issue_d:>84,int_rate:<9.548,int_rate:9.548-12.025,int_rate:12.025-15.74,int_rate:15.74-20.281,int_rate:>20.281,mths_since_earliest_cr_line:<140,mths_since_earliest_cr_line:141-164,mths_since_earliest_cr_line:165-247,mths_since_earliest_cr_line:248-270,mths_since_earliest_cr_line:271-352,mths_since_earliest_cr_line:>352,delinq_2yrs:0,delinq_2yrs:1-3,delinq_2yrs:4-16,delinq_2yrs:>=17,inq_last_6mths:0,inq_last_6mths:1-2,inq_last_6mths:3-6,inq_last_6mths:>6,total_acc:0-15,total_acc:16-70,total_acc:71-90,total_acc:>90,annual_inc:<20K,annual_inc:20K-30K,annual_inc:30K-40K,annual_inc:40K-50K,annual_inc:50K-60K,annual_inc:60K-70K,annual_inc:70K-80K,annual_inc:80K-90K,annual_inc:90K-100K,annual_inc:100K-120K,annual_inc:120K-140K,annual_inc:>140K,dti:<=1.4,dti:1.4-3.5,dti:3.5-7.7,dti:7.7-10.5,dti:10.5-16.1,dti:16.1-20.3,dti:20.3-21.7,dti:21.7-22.4,dti:22.4-35,dti:>35,mths_since_last_delinq:Missing,mths_since_last_delinq:0-3,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:0-2,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
362514,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
288564,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
213591,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
263083,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
165001,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [ ]:
df_scorecard

,index,Feature name,Coefficients,p_values,Original feature name,Score - Calculation,Score - Preliminary,Difference,Score - Final,diff_rounding
0,0,Intercept,-0.233534,NaN,Intercept,358.335001,358.0,-0.335001,358.0,-0.335001
1,1,grade:A,0.922083,0.000000,grade,80.366875,80.0,-0.366875,80.0,-0.366875
2,2,grade:B,0.685872,0.000000,grade,59.779210,60.0,0.220790,60.0,0.220790
3,3,grade:C,0.488966,0.000000,grade,42.617335,43.0,0.382665,43.0,0.382665
4,4,grade:D,0.324109,0.000000,grade,28.248711,28.0,-0.248711,28.0,-0.248711
5,5,grade:E,0.189386,0.000055,grade,16.506545,17.0,0.493455,17.0,0.493455
6,6,grade:F,0.056816,0.244388,grade,4.951947,5.0,0.048053,5.0,0.048053
7,7,home_ownership:OWN,0.083058,0.000016,home_ownership,7.239135,7.0,-0.239135,7.0,-0.239135
8,8,home_ownership:MORTGAGE,0.116799,0.000000,home_ownership,10.179993,10.0,-0.179993,10.0,-0.179993
9,9,addr_state:OK_LA_NC_NM_MO_VA_NJ,-0.017217,0.199936,addr_state,-1.500634,-2.0,-0.499366,-2.0,-0.499366
10,10,addr_state:MD_TN_AZ_PA_MI,0.007682,0.649376,addr_state,0.669513,1.0,0.330487,1.0,0.330487
11,11,addr_state:DE_AR,0.027290,0.592392,addr_state,2.378525,2.0,-0.378525,2.0,-0.378525
12,12,addr_state:UT_MN_OH_IN_GA_ RI_WA,0.077894,0.000003,addr_state,6.789061,7.0,0.210939,7.0,0.210939
13,13,addr_state:OR_KY_MA,0.080659,0.001931,addr_state,7.030067,7.0,-0.030067,7.0,-0.030067
14,14,addr_state:MT_MS_SD,0.145519,0.021437,addr_state,12.683139,13.0,0.316861,13.0,0.316861
15,15,addr_state:WI_IL_CT_AK,0.210400,0.000000,addr_state,18.338020,18.0,-0.338020,18.0,-0.338020
16,16,addr_state:CO_SC,0.239710,0.000000,addr_state,20.892688,21.0,0.107312,21.0,0.107312
17,17,addr_state:KS_NH_WV_VT_ID,0.301183,0.000000,addr_state,26.250547,26.0,-0.250547,26.0,-0.250547
18,18,addr_state:WY_DC_ME,0.632358,0.000000,addr_state,55.115072,55.0,-0.115072,55.0,-0.115072
19,19,verification_status:Not Verified,0.089282,0.000000,verification_status,7.781637,8.0,0.218363,8.0,0.218363
20,20,verification_status:Source Verified,-0.014011,0.277593,verification_status,-1.221209,-1.0,0.221209,-1.0,0.221209
21,21,purpose:credit_card,0.289341,0.000000,purpose,25.218423,25.0,-0.218423,25.0,-0.218423
22,22,purpose:debt_consolidation,0.179817,0.000000,purpose,15.672523,16.0,0.327477,16.0,0.327477
23,23,purpose:oth__med__vacation,0.210564,0.000000,purpose,18.352361,18.0,-0.352361,18.0,-0.352361
24,24,purpose:major_purch__car__home_impr,0.245352,0.000000,purpose,21.384404,21.0,-0.384404,21.0,-0.384404
25,25,initial_list_status:w,0.039322,0.001595,initial_list_status,3.427269,3.0,-0.427269,3.0,-0.427269
26,26,term:36,0.054479,0.000054,term,4.748297,5.0,0.251703,5.0,0.251703
27,27,emp_length:1,0.117944,0.000003,emp_length,10.279777,10.0,-0.279777,10.0,-0.279777
28,28,emp_length:2-4,0.105776,0.000000,emp_length,9.219256,9.0,-0.219256,9.0,-0.219256
29,29,emp_length:5-6,0.064778,0.001708,emp_length,5.645946,6.0,0.354054,6.0,0.354054
30,30,emp_length:7-9,0.058536,0.003576,emp_length,5.101868,5.0,-0.101868,5.0,-0.101868
31,31,emp_length:10,0.118364,0.000000,emp_length,10.316357,10.0,-0.316357,10.0,-0.316357
32,32,mths_since_issue_d:<38,0.930421,0.000000,mths_since_issue_d,81.093615,81.0,-0.093615,81.0,-0.093615
33,33,mths_since_issue_d:38-39,0.804655,0.000000,mths_since_issue_d,70.132117,70.0,-0.132117,70.0,-0.132117
34,34,mths_since_issue_d:40-41,0.723854,0.000000,mths_since_issue_d,63.089665,63.0,-0.089665,63.0,-0.089665
35,35,mths_since_issue_d:42-48,0.547772,0.000000,mths_since_issue_d,47.742755,48.0,0.257245,48.0,0.257245
36,36,mths_since_issue_d:49-52,0.434164,0.000000,mths_since_issue_d,37.840911,38.0,0.159089,38.0,0.159089
37,37,mths_since_issue_d:53-64,0.217185,0.000000,mths_since_issue_d,18.929413,19.0,0.070587,19.0,0.070587
38,38,mths_since_issue_d:65-84,-0.016931,0.549188,mths_since_issue_d,-1.475703,-1.0,0.475703,-1.0,0.475703
39,39,int_rate:<9.548,1.003119,0.000000,int_rate,87.429822,87.0,-0.429822,87.0,-0.429822
40,40,int_rate:9.548-12.025,0.657169,0.000000,int_rate,57.277545,57.0,-0.277545,57.0,-0.277545
41,41,int_rate:12.025-15.74,0.409855,0.000000,int_rate,35.722168,36.0,0.277832,36.0,0.277832
42,42,int_rate:15.74-20.281,0.178900,0.000000,int_rate,15.592543,16.0,0.407457,16.0,0.407457
43,43,mths_since_earliest_cr_line:141-164,0.079188,0.001039,mths_since_earliest_cr_line,6.901896,7.0,0.098104,7.0,0.098104
44,44,mths_since_earliest_cr_line:165-247,0.067263,0.000661,mths_since_earliest_cr_line,5.862471,6.0,0.137529,6.0,0.137529
45,45,mths_since_earliest_cr_line:248-270,0.108817,0.000023,mths_since_earliest_cr_line,9.484231,9.0,-0.484231,9.0,-0.484231
46,46,mths_since_earliest_cr_line:271-352,0.147488,0.000000,mths_since_earliest_cr_line,12.854764,13.0,0.145236,13.0,0.145236
47,47,mths_since_earliest_cr_line:>352,0.164264,0.000000,mths_since_earliest_cr_line,14.316958,14.0,-0.316958,14.0,-0.316958
48,48,delinq_2yrs:1-3,-0.067749,0.007973,delinq_2yrs,-5.904898,-6.0,-0.095102,-6.0,-0.095102
49,49,delinq_2yrs:4-16,-0.117282,0.027896,delinq_2yrs,-10.222072,-10.0,0.222072,-10.0,0.222072
50,50,delinq_2yrs:>=17,-0.022076,0.980220,delinq_2yrs,-1.924079,-2.0,-0.075921,-2.0,-0.075921
51,51,inq_last_6mths:0,0.307956,0.000168,inq_last_6mths,26.840851,27.0,0.159149,27.0,0.159149
52,52,inq_last_6mths:1-2,0.168522,0.039421,inq_last_6mths,14.688020,15.0,0.311980,15.0,0.311980
53,53,inq_last_6mths:3-6,-0.015544,0.850661,inq_last_6mths,-1.354784,-1.0,0.354784,-1.0,0.354784
54,54,total_acc:16-70,-0.059204,0.000038,total_acc,-5.160102,-5.0,0.160102,-5.0,0.160102
55,55,total_acc:71-90,-0.097449,0.592100,total_acc,-8.493439,-8.0,0.493439,-9.0,0.493439
56,56,total_acc:>90,-0.008503,0.986862,total_acc,-0.741136,-1.0,-0.258864,-1.0,-0.258864
57,57,annual_inc:20K-30K,-0.157414,0.000171,annual_inc,-13.719849,-14.0,-0.280151,-14.0,-0.280151
58,58,annual_inc:30K-40K,-0.094222,0.019571,annual_inc,-8.212177,-8.0,0.212177,-8.0,0.212177
59,59,annual_inc:40K-50K,0.000772,0.984744,annual_inc,0.067314,0.0,-0.067314,0.0,-0.067314
60,60,annual_inc:50K-60K,0.058271,0.154165,annual_inc,5.078769,5.0,-0.078769,5.0,-0.078769
61,61,annual_inc:60K-70K,0.144472,0.000550,annual_inc,12.591923,13.0,0.408077,13.0,0.408077
62,62,annual_inc:70K-80K,0.207411,0.000001,annual_inc,18.077486,18.0,-0.077486,18.0,-0.077486
63,63,annual_inc:80K-90K,0.252833,0.000000,annual_inc,22.036443,22.0,-0.036443,22.0,-0.036443
64,64,annual_inc:90K-100K,0.264443,0.000000,annual_inc,23.048320,23.0,-0.048320,23.0,-0.048320
65,65,annual_inc:100K-120K,0.346498,0.000000,annual_inc,30.200084,30.0,-0.200084,30.0,-0.200084
66,66,annual_inc:120K-140K,0.460002,0.000000,annual_inc,40.092879,40.0,-0.092879,40.0,-0.092879
67,67,annual_inc:>140K,0.404458,0.000000,annual_inc,35.251778,35.0,-0.251778,35.0,-0.251778
68,68,dti:<=1.4,0.072443,0.381056,dti,6.314013,6.0,-0.314013,6.0,-0.314013
69,69,dti:1.4-3.5,0.214882,0.001873,dti,18.728701,19.0,0.271299,19.0,0.271299
70,70,dti:3.5-7.7,0.179443,0.002544,dti,15.639904,16.0,0.360096,16.0,0.360096
71,71,dti:7.7-10.5,0.120595,0.041068,dti,10.510841,11.0,0.489159,11.0,0.489159
72,72,dti:10.5-16.1,0.077134,0.177126,dti,6.722826,7.0,0.277174,7.0,0.277174
73,73,dti:16.1-20.3,-0.024415,0.669402,dti,-2.127951,-2.0,0.127951,-2.0,0.127951
74,74,dti:20.3-21.7,-0.032009,0.592281,dti,-2.789884,-3.0,-0.210116,-3.0,-0.210116
75,75,dti:21.7-22.4,-0.088171,0.165313,dti,-7.684775,-8.0,-0.315225,-8.0,-0.315225
76,76,dti:22.4-35,-0.116832,0.038809,dti,-10.182884,-10.0,0.182884,-10.0,0.182884
77,77,mths_since_last_delinq:Missing,0.036970,0.421418,mths_since_last_delinq,3.222262,3.0,-0.222262,3.0,-0.222262
78,78,mths_since_last_delinq:4-30,0.083589,0.046548,mths_since_last_delinq,7.285463,7.0,-0.285463,7.0,-0.285463
79,79,mths_since_last_delinq:31-56,0.080119,0.091367,mths_since_last_delinq,6.983008,7.0,0.016992,7.0,0.016992
80,80,mths_since_last_delinq:>=57,0.068261,0.161782,mths_since_last_delinq,5.949468,6.0,0.050532,6.0,0.050532
81,81,mths_since_last_record:3-20,-0.004191,0.959584,mths_since_last_record,-0.365283,-0.0,0.365283,-0.0,0.365283
82,82,mths_since_last_record:21-31,0.036250,0.624928,mths_since_last_record,3.159450,3.0,-0.159450,3.0,-0.159450
83,83,mths_since_last_record:32-80,0.214814,0.000000,mths_since_last_record,18.722788,19.0,0.277212,19.0,0.277212
84,84,mths_since_last_record:81-86,-0.116621,0.052910,mths_since_last_record,-10.164427,-10.0,0.164427,-10.0,0.164427
85,85,mths_since_last_record:>86,-0.063665,0.003869,mths_since_last_record,-5.548943,-6.0,-0.451057,-6.0,-0.451057
86,0,grade:G,0.000000,NaN,grade,0.000000,0.0,0.000000,0.0,0.000000
87,1,home_ownership:RENT_OTHER_NONE_ANY,0.000000,NaN,home_ownership,0.000000,0.0,0.000000,0.0,0.000000
88,2,addr_state:ND_NE_IA_NV_FL_HI_AL,0.000000,NaN,addr_state,0.000000,0.0,0.000000,0.0,0.000000
89,3,verification_status:Verified,0.000000,NaN,verification_status,0.000000,0.0,0.000000,0.0,0.000000
90,4,purpose:educ__sm_b__wedd__ren_en__mov__house,0.000000,NaN,purpose,0.000000,0.0,0.000000,0.0,0.000000
91,5,initial_list_status:f,0.000000,NaN,initial_list_status,0.000000,0.0,0.000000,0.0,0.000000
92,6,term:60,0.000000,NaN,term,0.000000,0.0,0.000000,0.0,0.000000
93,7,emp_length:0,0.000000,NaN,emp_length,0.000000,0.0,0.000000,0.0,0.000000
94,8,mths_since_issue_d:>84,0.000000,NaN,mths_since_issue_d,0.000000,0.0,0.000000,0.0,0.000000
95,9,int_rate:>20.281,0.000000,NaN,int_rate,0.000000,0.0,0.000000,0.0,0.000000
96,10,mths_since_earliest_cr_line:<140,0.000000,NaN,mths_since_earliest_cr_line,0.000000,0.0,0.000000,0.0,0.000000
97,11,delinq_2yrs:0,0.000000,NaN,delinq_2yrs,0.000000,0.0,0.000000,0.0,0.000000
98,12,inq_last_6mths:>6,0.000000,NaN,inq_last_6mths,0.000000,0.0,0.000000,0.0,0.000000
99,13,total_acc:0-15,0.000000,NaN,total_acc,0.000000,0.0,0.000000,0.0,0.000000
100,14,annual_inc:<20K,0.000000,NaN,annual_inc,0.000000,0.0,0.000000,0.0,0.000000
101,15,dti:>35,0.000000,NaN,dti,0.000000,0.0,0.000000,0.0,0.000000
102,16,mths_since_last_delinq:0-3,0.000000,NaN,mths_since_last_delinq,0.000000,0.0,0.000000,0.0,0.000000
103,17,mths_since_last_record:0-2,0.000000,NaN,mths_since_last_record,0.000000,0.0,0.000000,0.0,0.000000

## Caclulating Credit Score

In [ ]:
inputs_test_with_ref_cat.head()

In [ ]:
df_scorecard

In [ ]:
inputs_test_with_ref_cat_w_intercept = inputs_test_with_ref_cat

In [ ]:
inputs_test_with_ref_cat_w_intercept.insert(0, 'Intercept', 1)
# Wir fügen eine Spalte mit dem Index 0 in den Datenrahmen ein, also am Anfang des Datenrahmens.
# Der Name dieser Spalte lautet „Intercept“ und ihre Werte sind 1.

In [ ]:
inputs_test_with_ref_cat_w_intercept.head()

In [ ]:
inputs_test_with_ref_cat_w_intercept = inputs_test_with_ref_cat_w_intercept[df_scorecard['Feature name'].values]
# Hier behalten wir aus dem Dataframe „inputs_test_with_ref_cat_w_intercept“ nur die Spalten mit Spaltennamen bei,
# die genau den Zeilenwerten der Spalte „Featurename“ aus dem Dataframe „df_scorecard“ entsprechen.

In [ ]:
inputs_test_with_ref_cat_w_intercept.head()

In [ ]:
scorecard_scores = df_scorecard['Score - Final']

In [ ]:
inputs_test_with_ref_cat_w_intercept.shape

In [ ]:
scorecard_scores.shape

In [ ]:
scorecard_scores = scorecard_scores.values.reshape(102, 1)

In [ ]:
scorecard_scores.shape

In [ ]:
y_scores = inputs_test_with_ref_cat_w_intercept.dot(scorecard_scores)
# Hier multiplizieren wir die Werte jeder Zeile des Datenrahmens mit den Werten jeder Spalte der Variable,
# die ein Argument der „dot“-Methode ist, und summieren sie. Es ist im Wesentlichen die Summe der Produkte

In [ ]:
y_scores.head()

In [ ]:
y_scores.tail()

##  From credit score to PD