<a href="https://colab.research.google.com/github/awildt01/Credit-Scoring/blob/main/notebooks/5_Monitoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
import os

#from google.colab import data_table
#data_table.enable_dataframe_formatter()

from google.colab import data_table
data_table.disable_dataframe_formatter()

# unbegrenzte Zeilen und Spalten anzeigen
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [6]:
# Google Drive mounten
drive.mount('/content/drive')

# Zielordner definieren
folder_path = '/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks'
os.makedirs(folder_path, exist_ok=True)  # Ordner erstellen, falls nicht vorhanden

Mounted at /content/drive

In [7]:
# Import Train and Test Data.
loan_data_inputs_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_train.csv', index_col = 0)
loan_data_targets_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_train.csv', index_col = 0,)
loan_data_inputs_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_test.csv', index_col = 0)
loan_data_targets_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_test.csv', index_col = 0, header = None)

In [8]:
loan_data_targets_train.head()

        good_bad
427211         1
206088         1
136020         1
412305         1
36159          0

In [9]:
loan_data_backup = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_2015.csv')

/tmp/ipython-input-3262726154.py:1: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_data_backup = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_2015.csv')

In [10]:
loan_data_backup.shape

(421094, 74)

In [11]:
loan_data = loan_data_backup.copy()

In [12]:
loan_data.head(5)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,68444620,73334399,35000,35000,35000.0,60 months,11.99,778.38,C,C1,Foreign Service Officer,10+ years,MORTGAGE,128000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home improvement,200xx,DC,6.46,0.0,Feb-90,0.0,46.0,NaN,17.0,0.0,14277,27.4,46.0,w,35000.0,35000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,56.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,321.0,146867.0,1.0,11.0,0.0,0.0,28.0,35367.0,49.3,0.0,1.0,5020.0,40.1,52200.0,1.0,4.0,0.0
1,68547583,73437441,8650,8650,8650.0,36 months,5.32,260.50,A,A1,Associate Consultant,< 1 year,MORTGAGE,100000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,462xx,IN,7.28,0.0,Jul-01,0.0,NaN,NaN,15.0,0.0,7158,26.7,24.0,w,8650.0,8650.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,165450.0,0.0,1.0,1.0,1.0,11.0,24041.0,88.8,0.0,3.0,3081.0,57.9,26800.0,1.0,0.0,5.0
2,67849662,72708407,4225,4225,4225.0,36 months,14.85,146.16,C,C5,mechanic,5 years,RENT,35000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,672xx,KS,15.22,2.0,Jul-11,0.0,18.0,NaN,6.0,0.0,1058,24.6,6.0,w,4225.0,4225.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,4888.0,0.0,1.0,0.0,0.0,47.0,3830.0,21.9,0.0,0.0,367.0,22.4,4300.0,0.0,0.0,0.0
3,68506885,73396712,10000,10000,10000.0,60 months,11.99,222.40,C,C1,CARDIOVASCULAR TECH,10+ years,RENT,42500.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,460xx,IN,31.04,0.0,Dec-98,1.0,NaN,NaN,10.0,0.0,5812,40.9,23.0,w,10000.0,10000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,41166.0,1.0,3.0,0.0,2.0,13.0,35354.0,75.5,1.0,1.0,3118.0,67.4,14200.0,1.0,1.0,1.0
4,68341763,72928789,20000,20000,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-00,0.0,NaN,NaN,6.0,0.0,7869,56.2,18.0,w,20000.0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Dec-15,0.0,NaN,1,JOINT,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,72.8,0.0,2.0,2081.0,64.7,14000.0,2.0,5.0,1.0

In [13]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421094 entries, 0 to 421093
Data columns (total 74 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           421094 non-null  int64
 1   member_id                    421094 non-null  int64
 2   loan_amnt                    421094 non-null  int64
 3   funded_amnt                  421094 non-null  int64
 4   funded_amnt_inv              421094 non-null  float64
 5   term                         421094 non-null  object
 6   int_rate                     421094 non-null  float64
 7   installment                  421094 non-null  float64
 8   grade                        421094 non-null  object
 9   sub_grade                    421094 non-null  object
 10  emp_title                    397220 non-null  object
 11  emp_length                   397277 non-null  object
 12  home_ownership               421094 non-null  object
 13  annual_inc                   421094 non-null  float64
 14  verification_status          421094 non-null  object
 15  issue_d                      421094 non-null  object
 16  loan_status                  421094 non-null  object
 17  pymnt_plan                   421094 non-null  object
 18  url                          421094 non-null  object
 19  desc                         45 non-null      object
 20  purpose                      421094 non-null  object
 21  title                        420962 non-null  object
 22  zip_code                     421094 non-null  object
 23  addr_state                   421094 non-null  object
 24  dti                          421094 non-null  float64
 25  delinq_2yrs                  421094 non-null  float64
 26  earliest_cr_line             421094 non-null  object
 27  inq_last_6mths               421094 non-null  float64
 28  mths_since_last_delinq       217133 non-null  float64
 29  mths_since_last_record       74415 non-null   float64
 30  open_acc                     421094 non-null  float64
 31  pub_rec                      421094 non-null  float64
 32  revol_bal                    421094 non-null  int64
 33  revol_util                   420932 non-null  float64
 34  total_acc                    421094 non-null  float64
 35  initial_list_status          421094 non-null  object
 36  out_prncp                    421094 non-null  float64
 37  out_prncp_inv                421094 non-null  float64
 38  total_pymnt                  421094 non-null  float64
 39  total_pymnt_inv              421094 non-null  float64
 40  total_rec_prncp              421094 non-null  float64
 41  total_rec_int                421094 non-null  float64
 42  total_rec_late_fee           421094 non-null  float64
 43  recoveries                   421094 non-null  float64
 44  collection_recovery_fee      421094 non-null  float64
 45  last_pymnt_d                 403811 non-null  object
 46  last_pymnt_amnt              421094 non-null  float64
 47  next_pymnt_d                 395337 non-null  object
 48  last_credit_pull_d           421083 non-null  object
 49  collections_12_mths_ex_med   421094 non-null  float64
 50  mths_since_last_major_derog  122729 non-null  float64
 51  policy_code                  421094 non-null  int64
 52  application_type             421094 non-null  object
 53  annual_inc_joint             511 non-null     float64
 54  dti_joint                    509 non-null     float64
 55  verification_status_joint    511 non-null     object
 56  acc_now_delinq               421094 non-null  float64
 57  tot_coll_amt                 421094 non-null  float64
 58  tot_cur_bal                  421094 non-null  float64
 59  open_acc_6m                  21372 non-null   float64
 60  open_il_6m                   21372 non-null   float64
 61  open_il_12m                  21372 non-null   float64
 62  open_il_24m                  21372 non-null   float64
 63  mths_since_rcnt_il           20810 non-null   float64
 64  total_bal_il                 21372 non-null   float64
 65  il_util                      18617 non-null   float64
 66  open_rv_12m                  21372 non-null   float64
 67  open_rv_24m                  21372 non-null   float64
 68  max_bal_bc                   21372 non-null   float64
 69  all_util                     21372 non-null   float64
 70  total_rev_hi_lim             421094 non-null  float64
 71  inq_fi                       21372 non-null   float64
 72  total_cu_tl                  21372 non-null   float64
 73  inq_last_12m                 21372 non-null   float64
dtypes: float64(45), int64(6), object(23)
memory usage: 237.7+ MB

# Population Stability Index: Preprocessing

### >>> The code from here to the other line starting with '>>>' is copied from the Data Preparation notebook, with minor adjustments. We have to perform the exact same data preprocessing, fine-classing, and coarse classing on the new data, in order to be able to calculate statistics for the exact same variables to the ones we used for training and testing the PD model.

### Preprocessing few continuous variables

## General Preprocessing

In [14]:
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '5 years', '3 years', '4 years', nan,
       '2 years', '8 years', '9 years', '1 year', '6 years', '7 years'],
      dtype=object)

In [15]:
# Ersetzt den String '10+ years' durch '10', um eine numerische Konvertierung zu ermöglichen.
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('10+ years', '10', regex=False)
# Ersetzt '< 1 year' durch '0', da dies einem Jahrzehnt von 0 Jahren entspricht.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0), regex=False)
# Ersetzt 'n/a' (Not Applicable) durch '0', da fehlende Werte hier als 0 Jahre betrachtet werden.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('n/a',  str(0), regex=False)
# Entfernt den String ' years' aus den Werten, um nur die numerischen Anteile zu behalten.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '', regex=False)
# Entfernt den String ' year' (Singular) aus den Werten.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '', regex=False)

In [16]:
type(loan_data['emp_length_int'][0])

str

In [17]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'], errors='coerce')

In [18]:
loan_data['emp_length_int'].head()

0    10.0
1     0.0
2     5.0
3    10.0
4    10.0
Name: emp_length_int, dtype: float64

In [19]:
loan_data['emp_length_int'].dtype

dtype('float64')

In [20]:
type(loan_data['emp_length_int'][0])

numpy.float64

Earliest credit line

In [21]:
loan_data['earliest_cr_line'].head()

0    Feb-90
1    Jul-01
2    Jul-11
3    Dec-98
4    Aug-00
Name: earliest_cr_line, dtype: object

In [22]:
# Konvertiert die Spalte 'earliest_cr_line' in ein Datumsformat. Das Format '%b-%y' gibt an, dass das Datum im Format 'Monat-Jahr' (z.B. 'Feb-90') vorliegt.
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'], format = '%b-%y')

In [23]:
type(loan_data['earliest_cr_line_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [24]:
pd.to_datetime('2018-12-01') - loan_data['earliest_cr_line_date'].head(1)

0   10530 days
Name: earliest_cr_line_date, dtype: timedelta64[ns]

In [25]:
# Berechnet die Zeitdifferenz zwischen dem 1. Dezember 2018 und dem Datum der frühesten Kreditlinie.
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2018-12-01') - loan_data['earliest_cr_line_date'])
/ np.timedelta64(1, 'D')) / 30.44)

In [26]:
# Zeigt deskriptive Statistiken für die Spalte 'mths_since_earliest_cr_line' an.
# Dies gibt uns einen Überblick über die Verteilung und mögliche Probleme (z.B. negative Werte).
loan_data['mths_since_earliest_cr_line'].describe()

count    421094.000000
mean        239.354876
std          98.123989
min        -600.000000
25%         179.000000
50%         224.000000
75%         289.000000
max         599.000000
Name: mths_since_earliest_cr_line, dtype: float64

In [27]:
#  Daten aus 1969 oder früher falsch konvertiert wurden
# (z.B. 1969 wurde zu 2069) und dadurch negative Differenzen berechnet wurden.
# Es gibt 2303 solche Werte, die das Problem belegen.
# Dieser Code filtert den DataFrame, um die Zeilen anzuzeigen, bei denen 'mths_since_earliest_cr_line' negativ ist.
# Dies hilft, die betroffenen Einträge zu identifizieren.
loan_data.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line'] < 0].head()

     earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
254            Jan-57            2057-01-01                       -457.0
618            Aug-64            2064-08-01                       -548.0
648            Jul-68            2068-07-01                       -595.0
1808           Jan-65            2065-01-01                       -553.0
2583           Sep-64            2064-09-01                       -549.0

In [28]:
# Es gibt 2303 solche Werte.
# Negative Werte werden durch den Maximalwert der Spalte ersetzt, da diese auf einer Fehlinterpretation des Jahres beruhen (z.B. '57' als 2057 anstatt 1957).
loan_data.loc[loan_data['mths_since_earliest_cr_line'] < 0, 'mths_since_earliest_cr_line'] = loan_data['mths_since_earliest_cr_line'].max()

In [29]:
min(loan_data['mths_since_earliest_cr_line'])

73.0

Term

In [30]:
# Zeigt deskriptive Statistiken für die Spalte 'int_rate' an. Dies umfasst Kennzahlen wie Mittelwert, Standardabweichung, Min/Max-Werte und Quartile.
loan_data['int_rate'].describe()

count    421094.000000
mean         12.601731
std           4.317873
min           5.320000
25%           9.170000
50%          12.290000
75%          15.590000
max          28.990000
Name: int_rate, dtype: float64

In [31]:
# Zeigt die ersten Werte der Spalte 'term' an. Diese Spalte enthält die Laufzeit des Kredits in Monaten als String.
loan_data['term'].head(5)

0     60 months
1     36 months
2     36 months
3     60 months
4     60 months
Name: term, dtype: object

In [32]:
# Zeigt deskriptive Statistiken für die Spalte 'term' an. Dies hilft, die Verteilung und die einzigartigen Werte zu verstehen.
loan_data['term'].describe()

count         421094
unique             2
top        36 months
freq          283172
Name: term, dtype: object

In [33]:
# Erstellt eine neue Spalte 'term_int', indem der String ' months' aus der 'term'-Spalte entfernt wird, um nur die numerischen Werte zu erhalten.
loan_data['term_int'] = loan_data['term'].str.replace(' months', '')

In [34]:
# Zeigt die ersten 5 Werte der neuen Spalte 'term_int' an, um die Änderung zu überprüfen.
loan_data['term_int'].head(5)

0     60
1     36
2     36
3     60
4     60
Name: term_int, dtype: object

In [35]:
# Überprüft den Datentyp der 'term_int'-Spalte und eines einzelnen Elements. Es wird erwartet, dass es sich noch um einen String handelt.
type(loan_data['term_int'])
type(loan_data['term_int'][25])

str

In [36]:
# Überprüft den Datentyp der 'term_int'-Spalte und eines einzelnen Elements. Es wird erwartet, dass es sich noch um einen String handelt.
loan_data['term_int'] = pd.to_numeric(loan_data['term'].str.replace(' months', ''))
loan_data['term_int'].head(5)

0    60
1    36
2    36
3    60
4    60
Name: term_int, dtype: int64

In [37]:
# Überprüft erneut den Datentyp eines Elements in 'term_int', um zu bestätigen, dass die Konvertierung erfolgreich war.
type(loan_data['term_int'][0])

numpy.int64

Time since the loan was funded

In [38]:
loan_data['issue_d'].head(5)

0    Dec-15
1    Dec-15
2    Dec-15
3    Dec-15
4    Dec-15
Name: issue_d, dtype: object

In [39]:
# Annahme: Wir befinden uns im Dezember 2017
# Konvertiert die Spalte 'issue_d' (Ausgabedatum) in ein Datumsformat.
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%y')

# Berechnet die Anzahl der Monate seit dem Ausgabedatum bis zum 01.12.2018.
# Hierfür wird die Differenz in Tagen berechnet und dann durch den durchschnittlichen Wert der Tage in einem Monat (30.44) geteilt.
loan_data['mths_since_issue_d'] = round(pd.to_numeric((pd.to_datetime('2018-12-01') - loan_data['issue_d_date']) / np.timedelta64(1, 'D')) / 30.44)

# Zeigt deskriptive Statistiken für die neu erstellte Spalte 'mths_since_issue_d' an.
loan_data['mths_since_issue_d'].describe()

count    421094.000000
mean         41.044629
std           3.458162
min          36.000000
25%          38.000000
50%          41.000000
75%          44.000000
max          47.000000
Name: mths_since_issue_d, dtype: float64

# Data preparation: preprocessing discrete variables

In [40]:
# Zeigt eine Zusammenfassung des DataFrames 'loan_data' an, einschließlich Spaltennamen, Non-Null-Werten und Datentypen.
# Dies ist nützlich, um den aktuellen Zustand des DataFrames und die Ergebnisse der vorherigen Preprocessing-Schritte zu überprüfen.
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421094 entries, 0 to 421093
Data columns (total 80 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           421094 non-null  int64
 1   member_id                    421094 non-null  int64
 2   loan_amnt                    421094 non-null  int64
 3   funded_amnt                  421094 non-null  int64
 4   funded_amnt_inv              421094 non-null  float64
 5   term                         421094 non-null  object
 6   int_rate                     421094 non-null  float64
 7   installment                  421094 non-null  float64
 8   grade                        421094 non-null  object
 9   sub_grade                    421094 non-null  object
 10  emp_title                    397220 non-null  object
 11  emp_length                   397277 non-null  object
 12  home_ownership               421094 non-null  object
 13  annual_inc                   421094 non-null  float64
 14  verification_status          421094 non-null  object
 15  issue_d                      421094 non-null  object
 16  loan_status                  421094 non-null  object
 17  pymnt_plan                   421094 non-null  object
 18  url                          421094 non-null  object
 19  desc                         45 non-null      object
 20  purpose                      421094 non-null  object
 21  title                        420962 non-null  object
 22  zip_code                     421094 non-null  object
 23  addr_state                   421094 non-null  object
 24  dti                          421094 non-null  float64
 25  delinq_2yrs                  421094 non-null  float64
 26  earliest_cr_line             421094 non-null  object
 27  inq_last_6mths               421094 non-null  float64
 28  mths_since_last_delinq       217133 non-null  float64
 29  mths_since_last_record       74415 non-null   float64
 30  open_acc                     421094 non-null  float64
 31  pub_rec                      421094 non-null  float64
 32  revol_bal                    421094 non-null  int64
 33  revol_util                   420932 non-null  float64
 34  total_acc                    421094 non-null  float64
 35  initial_list_status          421094 non-null  object
 36  out_prncp                    421094 non-null  float64
 37  out_prncp_inv                421094 non-null  float64
 38  total_pymnt                  421094 non-null  float64
 39  total_pymnt_inv              421094 non-null  float64
 40  total_rec_prncp              421094 non-null  float64
 41  total_rec_int                421094 non-null  float64
 42  total_rec_late_fee           421094 non-null  float64
 43  recoveries                   421094 non-null  float64
 44  collection_recovery_fee      421094 non-null  float64
 45  last_pymnt_d                 403811 non-null  object
 46  last_pymnt_amnt              421094 non-null  float64
 47  next_pymnt_d                 395337 non-null  object
 48  last_credit_pull_d           421083 non-null  object
 49  collections_12_mths_ex_med   421094 non-null  float64
 50  mths_since_last_major_derog  122729 non-null  float64
 51  policy_code                  421094 non-null  int64
 52  application_type             421094 non-null  object
 53  annual_inc_joint             511 non-null     float64
 54  dti_joint                    509 non-null     float64
 55  verification_status_joint    511 non-null     object
 56  acc_now_delinq               421094 non-null  float64
 57  tot_coll_amt                 421094 non-null  float64
 58  tot_cur_bal                  421094 non-null  float64
 59  open_acc_6m                  21372 non-null   float64
 60  open_il_6m                   21372 non-null   float64
 61  open_il_12m                  21372 non-null   float64
 62  open_il_24m                  21372 non-null   float64
 63  mths_since_rcnt_il           20810 non-null   float64
 64  total_bal_il                 21372 non-null   float64
 65  il_util                      18617 non-null   float64
 66  open_rv_12m                  21372 non-null   float64
 67  open_rv_24m                  21372 non-null   float64
 68  max_bal_bc                   21372 non-null   float64
 69  all_util                     21372 non-null   float64
 70  total_rev_hi_lim             421094 non-null  float64
 71  inq_fi                       21372 non-null   float64
 72  total_cu_tl                  21372 non-null   float64
 73  inq_last_12m                 21372 non-null   float64
 74  emp_length_int               397277 non-null  float64
 75  earliest_cr_line_date        421094 non-null  datetime64[ns]
 76  mths_since_earliest_cr_line  421094 non-null  float64
 77  term_int                     421094 non-null  int64
 78  issue_d_date                 421094 non-null  datetime64[ns]
 79  mths_since_issue_d           421094 non-null  float64
dtypes: datetime64[ns](2), float64(48), int64(7), object(23)
memory usage: 257.0+ MB

In [41]:
# loan_data['grade_factor'] = loan_data['grade'].astype('category')

In [42]:
#grade
#sub_grade
#home_ownership
#verification_status
#loan_status
#purpose
#addr_state
#initial_list_status

In [43]:
# Erstellt Dummy-Variablen für die Spalte 'grade'.
# Jede eindeutige Kategorie in 'grade' wird zu einer neuen Spalte (z.B. 'grade:A', 'grade:B') mit Binärwerten (0 oder 1).
# 'prefix' und 'prefix_sep' werden verwendet, um die Namen der neuen Spalten prägnant zu gestalten.
pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':').head(5)

   grade:A  grade:B  grade:C  grade:D  grade:E  grade:F  grade:G
0    False    False     True    False    False    False    False
1     True    False    False    False    False    False    False
2    False    False     True    False    False    False    False
3    False    False     True    False    False    False    False
4    False     True    False    False    False    False    False

In [44]:
# Erstellt Dummy-Variablen für mehrere kategoriale Spalten gleichzeitig und speichert sie in einer Liste.
# Diese Spalten sind: 'grade', 'sub_grade', 'home_ownership', 'verification_status', 'loan_status', 'purpose', 'addr_state', 'initial_list_status'.
# Jede get_dummies-Operation erstellt einen DataFrame mit den entsprechenden Binärvariablen.
loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['sub_grade'], prefix = 'sub_grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['home_ownership'], prefix = 'home_ownership', prefix_sep = ':'),
                     pd.get_dummies(loan_data['verification_status'], prefix = 'verification_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['loan_status'], prefix = 'loan_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['purpose'], prefix = 'purpose', prefix_sep = ':'),
                     pd.get_dummies(loan_data['addr_state'], prefix = 'addr_state', prefix_sep = ':'),
                     pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = ':')]
# Verkettet alle erstellten Dummy-DataFrames horizontal (axis = 1) zu einem einzigen DataFrame namens 'loan_data_dummies'.
# Dies kombiniert alle One-Hot-kodierten kategorialen Merkmale.
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)

In [45]:
# Überprüft den Datentyp des 'loan_data_dummies' Objekts. Es sollte ein pandas DataFrame sein.
type(loan_data_dummies)

pandas.core.frame.DataFrame

In [46]:
# Zeigt die Dimensionen (Anzahl der Zeilen und Spalten) des 'loan_data_dummies' DataFrames an.
# Dies hilft zu verstehen, wie viele neue Spalten durch die Dummy-Kodierung hinzugefügt wurden.
loan_data_dummies.shape

(421094, 122)

In [47]:
# Zeigt eine Zusammenfassung des 'loan_data_dummies' DataFrames an, einschließlich Spaltennamen und Datentypen.
# Dies bestätigt, dass die Dummy-Variablen als boolesche Typen oder Integer vorliegen.
loan_data_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421094 entries, 0 to 421093
Columns: 122 entries, grade:A to initial_list_status:w
dtypes: bool(122)
memory usage: 49.0 MB

In [48]:
# Fügt den DataFrame mit den neu erstellten Dummy-Variablen (loan_data_dummies) horizontal (axis = 1) an den ursprünglichen 'loan_data' DataFrame an.
# Dadurch werden die kategorialen Merkmale in eine für maschinelles Lernen geeignete Form gebracht.
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)

In [49]:
# Zeigt alle Spaltennamen des aktualisierten 'loan_data' DataFrames an.
# Dies bestätigt, dass die neuen Dummy-Variablen-Spalten erfolgreich hinzugefügt wurden.
loan_data.columns.values

array(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'emp_length_int',
       'earliest_cr_line_date', 'mths_since_earliest_cr_line', 'term_int',
       'issue_d_date', 'mths_since_issue_d', 'grade:A', 'grade:B',
       'grade:C', 'grade:D', 'grade:E', 'grade:F', 'grade:G',
       'sub_grade:A1', 'sub_grade:A2', 'sub_grade:A3', 'sub_grade:A4',
       'sub_grade:A5', 'sub_grade:B1', 'sub_grade:B2', 'sub_grade:B3',
       'sub_grade:B4', 'sub_grade:B5', 'sub_grade:C1', 'sub_grade:C2',
       'sub_grade:C3', 'sub_grade:C4', 'sub_grade:C5', 'sub_grade:D1',
       'sub_grade:D2', 'sub_grade:D3', 'sub_grade:D4', 'sub_grade:D5',
       'sub_grade:E1', 'sub_grade:E2', 'sub_grade:E3', 'sub_grade:E4',
       'sub_grade:E5', 'sub_grade:F1', 'sub_grade:F2', 'sub_grade:F3',
       'sub_grade:F4', 'sub_grade:F5', 'sub_grade:G1', 'sub_grade:G2',
       'sub_grade:G3', 'sub_grade:G4', 'sub_grade:G5',
       'home_ownership:ANY', 'home_ownership:MORTGAGE',
       'home_ownership:OWN', 'home_ownership:RENT',
       'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Issued', 'loan_status:Late (16-30 days)',
       'loan_status:Late (31-120 days)', 'purpose:car',
       'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:educational', 'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:IL', 'addr_state:IN', 'addr_state:KS', 'addr_state:KY',
       'addr_state:LA', 'addr_state:MA', 'addr_state:MD', 'addr_state:ME',
       'addr_state:MI', 'addr_state:MN', 'addr_state:MO', 'addr_state:MS',
       'addr_state:MT', 'addr_state:NC', 'addr_state:ND', 'addr_state:NE',
       'addr_state:NH', 'addr_state:NJ', 'addr_state:NM', 'addr_state:NV',
       'addr_state:NY', 'addr_state:OH', 'addr_state:OK', 'addr_state:OR',
       'addr_state:PA', 'addr_state:RI', 'addr_state:SC', 'addr_state:SD',
       'addr_state:TN', 'addr_state:TX', 'addr_state:UT', 'addr_state:VA',
       'addr_state:VT', 'addr_state:WA', 'addr_state:WI', 'addr_state:WV',
       'addr_state:WY', 'initial_list_status:f', 'initial_list_status:w'],
      dtype=object)

# Data preparation: check for missing values and clean

In [50]:
pd.options.display.max_rows = None
loan_data.isnull().sum().head()

id                 0
member_id          0
loan_amnt          0
funded_amnt        0
funded_amnt_inv    0
dtype: int64

In [51]:
pd.options.display.max_rows = 100

In [52]:
# loan_data$total_rev_hi_lim - There are 70276 missing values here.
# 'Total revolving high credit/credit limit', so it makes sense that the missing values are equal to funded_amnt.

# loan_data$acc_now_delinq
# loan_data$total_acc
# loan_data$pub_rec
# loan_data$open_acc
# loan_data$inq_last_6mths
# loan_data$delinq_2yrs
# loan_data$mths_since_earliest_cr_line
# - There are 29 missing values in all of these columns. They are likely the same observations.
# An eyeballing examination of the dataset confirms that.
# All of these are with loan_status 'Does not meet the credit policy. Status:Fully Paid'.
# We impute these values.

# loan_data$annual_inc
# - There are 4 missing values in all of these columns.

# loan_data$mths_since_last_record
# loan_data$mths_since_last_delinq

In [53]:
# Füllt fehlende Werte (NaN) in der Spalte 'total_rev_hi_lim' mit den entsprechenden Werten aus der Spalte 'funded_amnt' auf.
# Dies ist sinnvoll, da 'Total revolving high credit/credit limit' (Gesamter verfügbarer Kredit/Kreditlimit) oft dem 'funded_amnt' (finanzierter Betrag) entspricht, wenn keine spezifischen Kreditlimits angegeben sind.
loan_data['total_rev_hi_lim'] = loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'])

In [54]:
loan_data['mths_since_earliest_cr_line'] = loan_data['mths_since_earliest_cr_line'].fillna(0)

In [55]:
loan_data['acc_now_delinq'] = loan_data['acc_now_delinq'].fillna(0) # Füllt fehlende Werte (NaN) in der Spalte 'acc_now_delinq' mit 0 auf.
loan_data['total_acc'] = loan_data['total_acc'].fillna(0) # Füllt fehlende Werte (NaN) in der Spalte 'total_acc' mit 0 auf.
loan_data['pub_rec'] = loan_data['pub_rec'].fillna(0) # Füllt fehlende Werte (NaN) in der Spalte 'pub_rec' mit 0 auf.
loan_data['open_acc'] = loan_data['open_acc'].fillna(0) # Füllt fehlende Werte (NaN) in der Spalte 'open_acc' mit 0 auf.
loan_data['inq_last_6mths'] = loan_data['inq_last_6mths'].fillna(0) # Füllt fehlende Werte (NaN) in der Spalte 'inq_last_6mths' mit 0 auf.
loan_data['delinq_2yrs'] = loan_data['delinq_2yrs'].fillna(0) # Füllt fehlende Werte (NaN) in der Spalte 'delinq_2yrs' mit 0 auf.
loan_data['emp_length_int'] = loan_data['emp_length_int'].fillna(0) # Füllt fehlende Werte (NaN) in der Spalte 'emp_length_int' mit 0 auf.

In [56]:
# Füllt fehlende Werte (NaN) in der Spalte 'emp_length_int' mit mean auf
loan_data['annual_inc'] = loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean())

# PD model: Data preparation: Good/ Bad (DV for the PD model)

In [57]:
loan_data['loan_status'].unique()

array(['Issued', 'Current', 'Fully Paid', 'In Grace Period',
       'Late (16-30 days)', 'Late (31-120 days)', 'Charged Off',
       'Default'], dtype=object)

In [58]:
loan_data['loan_status'].value_counts()

loan_status
Current               377553
Fully Paid             22984
Issued                  8460
Late (31-120 days)      4691
In Grace Period         3107
Charged Off             2773
Late (16-30 days)       1139
Default                  387
Name: count, dtype: int64

In [59]:
loan_data['loan_status'].value_counts() / loan_data['loan_status'].count()

loan_status
Current               0.896600
Fully Paid            0.054582
Issued                0.020091
Late (31-120 days)    0.011140
In Grace Period       0.007378
Charged Off           0.006585
Late (16-30 days)     0.002705
Default               0.000919
Name: count, dtype: float64

In [60]:
# Good/ Bad Definition
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off', 'Default',
                                                       'Does not meet the credit policy. Status:Charged Off',
                                                       'Late (31-120 days)']), 0, 1)

In [61]:
#loan_data['good_bad'].sum()/loan_data['loan_status'].count()

In [62]:
loan_data['good_bad'].head(5)

0    1
1    1
2    1
3    1
4    1
Name: good_bad, dtype: int64

# PD model: Data Preparation: Splitting Data

In [63]:
# loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
# Here we don't split data into training and test
#train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])

In [66]:
#loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])

In [67]:
#loan_data_inputs_train.shape

In [68]:
#loan_data_targets_train.shape

In [69]:
#loan_data_inputs_test.shape

In [70]:
#loan_data_targets_test.shape

In [71]:
#loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'], test_size = 0.2, random_state = 42)

In [72]:
#loan_data_inputs_train.shape

In [73]:
#loan_data_targets_train.shape

In [74]:
#loan_data_inputs_test.shape

In [75]:
#loan_data_targets_test.shape

# PD model: Data Preparation: Discrete Variables